apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-organization-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage organizations (my job).
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - organizations
  verbs:
  - list
  - get
  - watch
  - update
  - patch
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - organizations/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
