/*
Copyright 2026 Nscale.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generate

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// The document types below are a minimal, hand-rolled model of the two Cerbos
// policy document shapes the generator emits.  They deliberately do not use
// the Cerbos SDK protos: the store must be byte-deterministic (golden tests,
// diffable ConfigMap contents) and protojson output is unstable by design, so
// the protos would still need a hand-written canonical marshaler.  The YAML
// tags pin the field names and order of the on-disk contract; CI compiles the
// output with the pinned Cerbos binary, so schema drift fails loudly.  Revisit
// if M2 grows the emitted surface (consent overlays, exported variables) or
// requires parsing policies rather than only emitting them.

// DerivedRolesDocument is a Cerbos derived-roles policy file.
type DerivedRolesDocument struct {
	APIVersion   string       `yaml:"apiVersion"`
	DerivedRoles DerivedRoles `yaml:"derivedRoles"`
}

// DerivedRoles is the body of a derived-roles document.
type DerivedRoles struct {
	Name        string        `yaml:"name"`
	Definitions []DerivedRole `yaml:"definitions"`
}

// DerivedRole is a single derived-role definition.  The generator emits one
// per (Role CR, scope bucket) pair; the condition is the binding-match
// expression that activates the role for a matching principal binding.
type DerivedRole struct {
	Name        string    `yaml:"name"`
	ParentRoles []string  `yaml:"parentRoles,flow"`
	Condition   Condition `yaml:"condition"`
}

// Condition wraps a Cerbos CEL match expression.
type Condition struct {
	Match Match `yaml:"match"`
}

// Match holds a CEL expression.
type Match struct {
	Expr string `yaml:"expr"`
}

// ResourcePolicyDocument is a Cerbos resource-policy file.
type ResourcePolicyDocument struct {
	APIVersion     string         `yaml:"apiVersion"`
	ResourcePolicy ResourcePolicy `yaml:"resourcePolicy"`
}

// ResourcePolicy is the body of a resource-policy document.  The generator
// emits one per distinct endpoint name, always at the root ("") scope with
// OVERRIDE_PARENT permissions (the grantor at the top of the scope chain).
type ResourcePolicy struct {
	Resource           string   `yaml:"resource"`
	Version            string   `yaml:"version"`
	Scope              string   `yaml:"scope"`
	ScopePermissions   string   `yaml:"scopePermissions"`
	ImportDerivedRoles []string `yaml:"importDerivedRoles,flow"`
	Rules              []Rule   `yaml:"rules"`
}

// Rule allows a set of actions to a set of derived roles.
type Rule struct {
	Actions      []string `yaml:"actions,flow"`
	DerivedRoles []string `yaml:"derivedRoles,flow"`
	Effect       string   `yaml:"effect"`
}

// generatedHeader marks emitted files as machine-generated so hand-written
// files (the Cerbos test suites) are distinguishable in a committed store.
const generatedHeader = "# Code generated by github.com/unikorn-cloud/identity/pkg/authz/cerbos/generate. DO NOT EDIT.\n"

// marshalDocument renders a policy document to deterministic YAML: a fixed
// generated-file header, struct-order fields and two-space indentation.
func marshalDocument(document any) ([]byte, error) {
	buffer := bytes.NewBufferString(generatedHeader)

	encoder := yaml.NewEncoder(buffer)
	encoder.SetIndent(2)

	if err := encoder.Encode(document); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMarshal, err)
	}

	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMarshal, err)
	}

	return buffer.Bytes(), nil
}
