apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-project-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-project-controller
  template:
    metadata:
      labels:
        app: unikorn-project-controller
    spec:
      containers:
      - name: unikorn-project-controller
        image: {{ include "unikorn.projectControllerImage" . }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-project-controller
      securityContext:
        runAsNonRoot: true
