apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-user-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - users
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - users/status
  verbs:
  - update
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - auth0users
  verbs:
  - get
  - list
  - watch
  - create
  - delete
