apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-group-subjects-migration-manager
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - groups
  verbs:
  - list
  - patch
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - organizationusers
  verbs:
  - list
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - users
  verbs:
  - list
