// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y96W7qyroo+ioW90hzTQlnmDaQ8+NcQkICCZDQpVmMm1O2C6hglx2XDYGhIe2H2E+4",
	"n+SqGhsbbAIko1sz2tpac4RyNV99XX3tt5RmmbaFIXZJ6uRbygYOMKELHfYvYBiWBlxk4frZjf8L/UGH",
	"RHOQTX9JnaQqkgOJ5TkalFZfSPWzo1Q6hegAG7iTVDqFgQlTJ5FZU+mUA1885EA9deI6HkyniDaBJqCr",
	"/C8HjlInqf/ny2qPX/iv5EtoEj31/Xs6NXYsz0b61m16GL14UGJDk/cnZjp4a+x7sSsLeO4ke+NYMx06",
	"24GIJT5Ysh1rhnToJO/QH/EO+K02xiYSu3XGAKPlDjeOpfDY5J1GZzx8t+Fp+F5tx3qGmvsGYopRW0HJ",
	"pzl4b/4MfFsOHEEHYg3uRi/B8ITtBb9v3Z67sOlg4joIj9k2CHRmSIMVTbM8/BaQxGAJ8NHJwFqf9WCY",
	"rU3EQecR6JybABnbaZhA5y8iQTpQArruQEKC7b540Fms9ssGpbZDis73BnzokGSg8AkOBgX7nALgO58B",
	"EvfU0hFcY8Ad/hP9o2ZhF2L2n8C2DcQHfHkmdLvfUvAVmLYB6X+a0AU6cNke/N1iHY4QhnqKYokNtegy",
	"JHXybyYTTOS69CiZdGqKsJ46SWmGR5hgoPukF0h/Vr6nI8NzwXA2Ym10Rvn+NZ1C9GeQh8cjXdfkfCmT",
	"lfPqCMjlvJqXs2omc5wH2jFUYCqYbOqp0MHQhUTsgiP5npLizkEu5JCOXnHVgcCFRAJxguxo42q/p1OU",
	"e1oOWu54N6/yfD6XR5Zjyp5jQKxZOtTXLkszEMTuE4OOVlDzWkktySNwrMr5sp6XQRlqMgAAjoqjQiGj",
	"FCgGWpQznKTUTvfWaTqdToXtVUcO1Nwnz0Gpk9TEdW1y8uULn/7IcsZHmmV+0YBhqECb8vuxLUzgkyAO",
	"ujlGNBb7p2VDjDi67AbvGNC0bY5cMbBv18+qEv0GYleASxJ0EAt5jd3VBZWx76aJDaEGDeRCieIzwLpF",
	"9QW2CUE7vQmUK3IPAjNMPI5lwPoZJZxUMa/li6NMUc7n1IycLxd0uQRhTlbyilrKZTNKQdFTXze5M/34",
	"q8+K2Eyqoim6Vs7Kaiabk/MZBcoq0IvycQFks8WCBoowk/r6/fteOkki/p9a+kLyIS25lsSBLAGuKm25",
	"h3ZIMH/0dWgmpKj6F4noGqH7AJoJwzcRHtbjuAz0iaXtwSzCU+wPLryx0wSw3XCd4aOYurmQhRYSBgfX",
	"Qzk+6boOi2U4klW1kKU8tyCXYRnKAOqlQlErKoXj0T74JJZLBJE4oE/J0updEQsVwxqjD2KjXOafpJ4t",
	"eKQa1nhM/l8gMIkyNRe4TDNYNCbqhYbaqFHvL+uZFqqTOu4UtGq9WJ/a94Nqo3wEF42lfldHbVR/bT43",
	"lVbvIdc+m87raI5Us+Y+dtngGbjIjzsXZYP+HdzVlPqz9drqnWebz81C86y+GN0edUfG1eu80+g24dVV",
	"LXvby4/mdhM2RrniTXtaXDQGT0C/JWRe0HbntGGobeGwdUwhxjkrhhokBDgLirZU2BkzSuYjqEMHuFCX",
	"ut128ACJvarow+GDab65iFDQX0SqeO5Eker6zRrdy3QbShjduYCrn6VOUtlipqgcZ6EMS1R8qgVVVrOl",
	"kVw+zmXUUbasA5hNpcUXXag50E2dpI5zeVUrZ1RZ0yCU87CoyUBRoAyzaiY/yhUzhVKZqoCEeNAJSVag",
	"mdYR2w5Dsj2YTQSUB7Gb6Isx9sJePMsF5KCL4p8ylXBTCXzxAHaRu0idZL+ngwErtW/1O1X7dgYKXzMR",
	"GBXDsOZEcidQItB1ER5L1kjiH8UePypruab30ZJq4wU1shxJt+jmiOuNRiHcNReyGCyLwUksWwFABSVF",
	"l4vHcCTnj8tlWS3qZblQHuWOYVaDWaDvw7KjgDhAF1g7ZCy0XWsKf4A+DAslPV9WoFzMjkpyvgxysnqs",
	"K7JaVqFazBR0oKqpNNdcI8y9dqt06tf9QY/y5odcp1B/tlDX0Pv03493hWf679tePdOa6me9bp3UzcEc",
	"LOpFuGg4+uWUz7Ggf28tdFQv1o2K2+rVX+n3kAmLGtKUwqSfOV085B4KnUGD3Jk1p305ONOyA6WXrWVB",
	"r5FXuxkX3Ndu7p4Hs1uz1upkbVdTClUVKXlwXsrf9stn6kUn2x40c/qZsdB7p+fq2QSoy9q51pu8ts+b",
	"hbu+rdxdNEZAeUDX1QY7y+1dPzfoZs60qUsecp1G+/5h2VQ6pHdXI13l8fRxWn7QqplbOCgvH5WHQu9Z",
	"B0AptG6nnbPOdHClKjWns8jUenjS05b1bPO8YEJznO/iBu7i047ar9XuLiezR8W27i7t7MPdY/O22yhf",
	"VxsOuLtlsvHxcpLTsuWrvvF4fmu+9h7M11nXLNNzNHrTxly/aPTUbOa+b5w+atPCNbxr1W4H5Q6FoX5p",
	"zIM7wcrRked0TPX1Mvuk4tJ10wBHD3MF5F6Ie9msXOFXMJ/WH7B7qc3a1Wfw+rycDTINw3xoytlqT61m",
	"UHbgVkirfmW1jVqjULzMtpSS3Xwot+3HrOZNq5c3mdPbV3LVJFo+M5gb9ceH2XPNWd7Vz+GZVStna6Zd",
	"7VzcLV1vrk1O7/Tjm/PbB3sEG7VG9hSOgXYxgbcvo879fa7QaZ0t5Me2ltfvpt6s5gxK9a5XKcnHTxo8",
	"vgTZQtfpeN0OcHqj5tPpdSXjnVWebsqVu+cJWVxcta+ytakHzvrKvXlvXN+dLYv6lX61KHcabucJ9/sa",
	"MZ5dUDcb98+t1k3FbLxkFNwoKJnzq6d6sVk+zfU6fecFGO1TMz8lx/LMrD2NtfMMAe1ZtqKh8/JN9rQ5",
	"1Yq5whSc5aqFS2Nx1ysXulO9WH2qzW37+bY/e+g/KIvj85dsy8aD0fQ+73VvzNKof5ZXne7zxR2+bLbO",
	"S8t8M/t0YzTzV93HCoLXHbNZeX4ovN6V7h+evOq9U8CqXOqalacb2XiuDto3N5X7s/vzV5B97b6qlcbM",
	"eXi5g95Ftj6rTKsKUIu29Wy89M1p527Wvi+4+P4WzAqzdvalXRlXH/qTbv3ufqnID6WJtuz0u+Oz3uLW",
	"LJQX/ePXl8FLFS3m1cn43mjnslfzyQQ7o+vXluE0T/OF+7axnDRuMlrurDo+frw7VttPt8cVpXTxPHPu",
	"X3vm8bh/5sjPRL8rT3pd1Grcek9Py26zdjMYtHoveJlpntXq0COoeNFA5UFVqTxZ3j3RJ1rrChefYf1s",
	"UNZx87WqPau3vcILqZ6/WHJfq17MLpWneR5UJ7ahN8ely4sb2O8+TsBp9zqzwOSprlTLlcpZDZZ1875V",
	"nFcvT71So7qQe/maBe87xqB7NfAushcNVCKjZaVWmxTR1eT2/vXSLFy1Kk/Ick4bg/N29z6nXxev2v37",
	"kU5OR73lOAea1vnCzqqNcgsAzb0wa4vGY7MMi83Xbqn/Om4Vry7h8YXuaUrrorY4dbxc1Wi+ZE+X2qT9",
	"qi7Pbp8sVHiwut7rtT2+MHKvqDFq4arxUuu93DcbxwWvO1We2tOr8cy8hKB8e9EBgLwW7ivXXRvYT9q0",
	"+jhrPTxfPFmPk7ySl696zzbIosb4vKUtYb+XreWfXwplp1qt9GuPg9HCy724pxXYMGF+MJ5gtTcD9V5D",
	"tWvwtL/ojh+uNO/i9sib3TafkdFHpYamLy5g7loF7jjFmf7TDDpohJha9nh3qzQvGs+PFw+LVm8yfTx7",
	"WDSzt/PW8nbR7j0orYum8nj3+Nxc9guPzx2zeTZdPj4Ppq2zxrT1PJi0niuvj2cPy8feYPqwfFCaZuv5",
	"8dZKURcDwK5vJYmYOZ6EzSTB9iKkGjO8cJVtZX/ZWX6HRes2ewrVmKXskSKxD/wXWFrSLEw8w2WqkwMN",
	"OAPYldjorASwLjFDDFVE0EiIacL0mJHnuBPoSDp0ATLilSzP1j+NMj/aKMOBvNUow4d8GmXC4NrBKMOH",
	"fhpl1qBCoPOO99Lhb5qVmQZoLpoxY7SnMkhSu84EH+kWXFl1dgcQPdEBDx/6WSKEEB5ZH/PgARq1zTwx",
	"tp06SY0sK7XXyUI7ecve7g8/Ej5L7gDgLifN6Ih/73ffYSpjP2HdthCLK/j3t4hvnVoHLBs6gcdJWEUZ",
	"iIGe8gkyRfduQBemvq78RrqahflMXs4AikGFUllWy7mcDHSlmMnpWf24NEqt3MNs7didIDxyAHEdT3M9",
	"BybtKLRwqViEQCnI2WKhIOczqiaXMrmCrJfLajEL9bwKi6k97BxAM2LtG5KBiEttGhwdqNh2HYvKXep2",
	"CvkDD7mjMJtiJ6RMGTF4ZJVsXlYKci7Ty+RPMpkTRXlMpVMTCAx30nWB65HUifjnIiWAAmG+MMrlVblc",
	"LBXkvKKX5NJxNi9nc1ouky1kNZAvptKbvse1UAM6lZ4vKopehDIsFwtyXs3nZVBSSnIpP1KzI5ArHivZ",
	"VHCv9T18iMw6RpCFER4HBwn++Ms9oVBRi6CgZ2U4KqtyflTMyCW9lJeVXE4tZYCeGx3nPtoT2qFkFod9",
	"OOL43HR0xiKdC1/dLxPXNFIn32IxmtqpqS5pcqszlz7C5kyt0hQlpZFjmUw55ezWD+n5PRAdZPLZUTGf",
	"kY9HelHOA7Usg9JxQc7l89oxVIGuFXIhHUh2qT76LizfGWVDqu5OsyeouimgwLJWzgE5B/LHch6CjFzW",
	"wEjOZo8Lx/lsCZQySiqqEO+23p4KcSJuirgthBmWRJU6H1vIIejy7098+b3w5eteCEO2y1E+hj1lY/GG",
	"Mq5zx7GcA7nbGGLoIE267DWvJUgnkmwwhmzu5/mUHMbApnAhJJAzo6q7XMhmmBSgWJHRX+fEanQGZ6dG",
	"VzWshjV3y/XWqe2qXcu869w8OK2rhXZeebql31AfTOq8mmJ3QQUSonaTV7r7i7uK6l2dYqy83JPnEtL1",
	"u8njc0F+7DXztbxecBrwSlWN9sVAkwu40ep3yI16PJWbk/MXp3xbQYXnK6wfG1NzetnPmhgYc3J7c5VK",
	"p+ialQq0q8Zdt9S0rq+ry5fmbVY1clfzZe0Ydh+uJ1rXIdPS9MHrgFYrXzDxwLsll/ncbbt+fX5auL8H",
	"l5NFt9sZD6rAbM4f7/rzijPLTPfRsyhs76B6BRdd6MZjSqPbbklzqEpTuKBepSOpN0FEQoQ5PRgSUULV",
	"JdtTDaTRYdQDBVwJOKEQPl1SF2yuIaaTMT2e0Llg6ENJA1hSmZBjjwxmuFqI2fg30hwQiaAx5jO6E0SG",
	"WJAgwypuQjoFutD2D8MwhqpMEZ4BA+lPQi6n0vyXpyiUxK+SSl9J4pPUnp5ORmVxV9AJTz4CyIC6xD+V",
	"2ELsDGlJULC/Fd2CRMKWy1RkgPAQA8MIRrBX3AhBQychoK381n+eVjG2rLEBZaRD7lf9OeIi5FbPZDJK",
	"sZzLlYrFvGxbmqKVMvqYjDzdURzVs58VD3vOszZzM1l4BGybHPE9UxEgoCziMGKc6Ey2+F+8y5O+Rbtd",
	"WUdXPvMN5PgzlYh/IHp8PQw/3lAYNnEkzEG67DW3TWHYke/yZ+ET/2c80xWs0LWEYNAMgMwP47oVLHkY",
	"vtpQc6FOmauHJwDrdEWuxlia5jkO1IU8NMGCSi4guQ7AhF67GAewPsT0V+JpGqRzYRZK6zqLI0mqj5gI",
	"kxDBf3HvgwYITEu2AQGhvNq2HFdCrgQINdayqw/Bu4/9JyjU3wdwYV/TIUbMBBEH8bVAVH4BHwfxuNl9",
	"sSbsPfymJ4BI8NWmQozDggXhVi08QmPP2dcCtOPmN9eINSDaENfPJC08jqszVMUGnmvJOiKaNYPOgpJT",
	"YH1jXibi2fS+oU6l9dhykDsx+S8jCKglTtBaxIXxB1oAaIiaZjn2nuxUt0yAsJjgSEwQ40IR49LhVKCT",
	"lFqEWjaf0WWYU/NyHow0GRwDIBcUZaSpxYKil+CBfpctMnXjRRX+wx/6IP+dr+/rIff3hsyLDD0KGdD/",
	"ROILed5+jhIUdnHBUUEpa3pG1o5hUc7TeDUA4LEMlEymmNe1oqJrBzj1kq1iYkD40v5Movsjru3rnvf2",
	"Bt35o9jt+ZG6h1BcKFQ36rPQ4Qh4hps6KcSE0krCiSDRoBYiwaPxkXQVeBhozIhpey5MS9DVqAdUR8Q2",
	"wKLFL6y68oPwCHN6TVBDJqBJdyMHwgSvSSh0OOJCYQYquu2944WTyOPWgw6CPF6Yj+RaSlRqAUNElVBn",
	"qGXAQ+mHBQgB1YDcQ5w+gKDWPPYGcJnfBOgmwoi4DnAt7q7/SMqzxTIyW4bsREa7UwKDaDwZCOsaGyHN",
	"kTtJMu7HR3H/eS7QmPDvn8/rRllFUZT8sZwp02jqbBHK5ZxalssjBRTUEVCgTiPLeRiGR1axCT0RmvA7",
	"Z8+kU+zdtOD3WZCVnJzJ9zLFk4zC7vPQgHmOc0loHA3/9/EqBnU/kfbnIe2PQYRkTWwNDUjM9f8umtkn",
	"AjzuI8LWLnG7ThePBgviQrP9aWf+tDMHeMJQwjcy64l2ZxH4fYjcWAsp/EyM+kyM+kyM+kyM+kyM+ick",
	"RnH/EXmiBulcUVGotI8VBf1l/7WJ+JNtotfK1sN9y6K8R79oXLaM2iWcFu4ezwsj7fmx+KCcLztGbXG7",
	"NIyWObhR+/ZNK2c43eca6dVOX1v9htJh8qKWeazWi3eLeuGhp7227/qvj93M5KE3zlz3OpPm87n70Ksv",
	"ml1l2XzuGK3lOPd49zhtLcfovktlUGYC7uZ0gy9qduJdm53ZY//UUO9qtlotPKtZhfJ6A15WUPv5PNvu",
	"nWday2a+tTwnddOY6NV6sdl7KDR7t/nW8jbX7M4RuG8t6bnAZUfRLpvF60XZ0e8ahmYWDP1isLw2B8uH",
	"7MTQzBZRc4PptdmaqfQs+NR+yHUymtmn+7H0y85cW1qz65ye0xcFrJm17MN9Z6Ihtq/Zw/3jRL+oLa6X",
	"E7Nl9gut53quddFcPNw1zNbzee6h1yy0z3SjtewY7bt+rtXT2fNXyw0Q259ZtlRUmKrZQUXAwXvIll0q",
	"ByoPr12rMp96V6NT2y5YGWKblcXLcjLtdo6LE/W5lmlXr2AeXXeLp9Wb8qL7+AAH8vS0qituTtOLg1e1",
	"XagNbhs3Hbc0VV5KJUfLZhqV3mJQmna1FnbkzHPNrDS8+3ZxDJRs5qrXucUXxdJZafnYKl/PzWa3M8ld",
	"3tTc9kv+uqqZt+fdLNBhY0Gsi3K5ZJqu15vb+VHFmQMW9jxyIJn8KjWkp12eKp1zJfeY7Qy088aglbWy",
	"nVwH96aFRec8M22aZfvx0sq07lrLJso42rndAcprr9NvnHZ7jz3duC10jU4Rnun3TWW66PfL5/q0cKZe",
	"1pr6xaTdutRz3fMJ6J8NzgeZ2jkwlZUa0i87t0phqk0Hd51MAw2WtUK7pl91nifzfu60CczWy8NzI9+6",
	"O18+9Ce37XMjf798PL3PtZb9bEZpnw+WD0anqZ7Vetpz56Gr0HH5xSBrYzB4yHYu7EH3Qm88KBnrDjcK",
	"/UXGa1XDakhj2ck85IFSXzxMO6PBspJ/HDTq2nPjvpPt3DQvJq8Ds3Df77s1cN7pDe7KGf3+Idc5Lzhh",
	"NUS/K9ggW16oKPOsXpQzj9XCTDO1mYZvHYB1hako7fpx6b6kKZNFV3Oezo6Pihdj9zrf1RpOychbr9Zx",
	"fwam8tW91XLd/tntq/mI61OtcVa6tcETbLTnxe7z3WWu2i0/G9PHTnWc04/7mWNXVhUykzOZO8+8M/qz",
	"406NHOfVczB1yn2YlbsDfeydgcr15bleHldn1zcvg+KpeXud6zpW7W488I6bECl9BVkOLJ7L8Ep+Ut1j",
	"86KvKK37i95sfNOcPlw8TufOfQlqjdICPF/LGVeWW5nFuNe5yMGzfh5PW+eN81o+476clifVB0KeKn2z",
	"iutE6dSAPfDk48nV+LnYW+ptXKzMb54dDyzmM6P+unyu2c36HVDHVr9ys3wBT922Y1zI4LhbzjS93GTZ",
	"OVYLRu0m2ytddPJWx5qQfsvpPLrl+vjRqzQutEHzOG8qbj73OGt0r846BQWax/Ky4RQK+RfdAPelFy87",
	"cV/dh/6pcSbfLF/neTL3zLmcyxWajSUg9zcX1XOndzbKw2X3/rSq1kmhfpnX1M7TzdI9fVGng95j9uHG",
	"Wxxr7U796hYtS4bRfKzOkUOyQD++vJx5xnVt3DQK3X7RmBWXEyTfPvRURe/NtNKZdnU5uTCeF2e3bvVh",
	"8Xpeky+8fm5wj84uS/jismGY2UGh8ww6Zs++nT5X8FP2tNw3Sqel+byb6bTbVb03sDVN74JMTcmjZb0A",
	"H3rtTD1PXl2gzsuOfK5kS4uiPmi7ZvfG1kbguVQ6Py0/Peg3OVi6c8Z6f6k8NW7OLX1x1++YuFDHVvWi",
	"aLUfZp41GqDufSN/33afm+fHs8kY5xe3o7YB1R5WB8aguHwoDgw1e3qDjwf3g161MlvWXXM0Mx5qOW2c",
	"l71pJjOVr3vd7q1i6oZRLI7xvHv58ty6rZtTPJ3bg2rPND0bGs8Xinp713czjSzJt1szfI1vaiXHwNhp",
	"351WZ3PczOX0dnayKM9dBer2lVxv5oyL7g3KoftM/ryXt+waRo/q9aPaQ3Z1fvO4nHXhxcRowvv73nJc",
	"ePFaty3Pnrt1vTZ+MBtAwzklAztW56jdtV8qx3Xdm1aO5ctrt5mvdvo0GJjxYD+H+RQCBzp7piDvENjC",
	"Alg99vYceQaL7nCg6zmYRfhEUkp4vAuPkvXz0HgwkWVz14xB4001w9NZLidLX/NtD/xjCY14/CyrWMcW",
	"FyGiInjGw2hqOVjWDMvTnzTLgU+zzFHm+CjzZE/HT5YNMbDRE/WbWfiJvpltNxpsFD1tLxSESgN1VAix",
	"5H/GTjtHhkFjpUaeMUIGDfIBZIG1iWNhyyPG4miIHyyPRVTZVhC06pcexLpkWhi5liMhl0hhMwn7kZtv",
	"JG7nGmLXksAcIJd56wzIoGqN2JxBTtsBcFB/fXxxOuU6QIO8BkzhWNUyeb2s6vliZqSoBXCc1dVSTsnk",
	"y2rxGOyRLLkXHOCvjFreb6s0JstA2jsvzJ8l4aZCRTKpx45tnQATshh5CRgOBPpCgq+IuOS3v0FxEP/I",
	"3AkpAWy5E+ikJY94jAGxAEYTAsw8yQtpAmYwevADbmtkOSrS9UNte/51BdMk3BerXqs5kPFMYBBJtxj+",
	"BWcI8M520AwZcAzJH0J5lNXzcE6aKBGRK2nJDcWsasAjfjYFjA4cYi5EBEgoj40AhQsVETRQuakHBM3g",
	"SqkZ/7UC5hCvKuytwEkDYuknQWVv3+F+ANYg7EIHA+PXxyH/3jjyu0c373dMbLk1y8PvjIDGlvs0otMk",
	"3HNITkF9xeYDkcWY+m9+731MA3Aoro4Q1kMlnQ+AusUiom8cy2VY5IuLwy4hWjDITwo/+TfzPVHXk+dO",
	"joKiFl/TKZVp508mdCeWTp6CyGn2DQQ6dOgo/3jhckMi4vooXPiUsrG1SfjxuCNuhAyYSovqqV9/0KUl",
	"wHO/KHPXkvz48vW60QKo0nxCQ+gRKw85xECy/RWDYPQjKcjx4y8TPjGjX+Zp5HOsv1aGmPMERCSImacQ",
	"MhlhcbWA5vYFe5tYczplaIuHoKBwJg+gQw4OhQ/KL/CFHThGFpY5sFLp1IzPnTpJ0X0Uj45/FM2unyU+",
	"juLUQ4YuiU1JKFS81k/hdTzM3kLhnMj9duL9Bkklv7n4PDhVhepF/+DqJAfFtvyYukjhUBgDELeioZkA",
	"ZkFWMnIm28soJ/nySSb3uGcVpeQgqKB6x6ok0WHSUg9JNN/gE5Zo8NVOnWRymUy2lCkfU+8WcP0/KPwP",
	"hLwxB/FUmnehZFUFlrNyEeRHcr6cKdJKBseyni3qxUIxmx2VyvuXYnqrFDdQLc9dvSSC8idh4goA+WfG",
	"jf3jSerrPkjzRrgQG3IUolO/XFdcQer4IlL8McvT7WzomIgQnu/DwGxDxxV9Z8aGpQJjhxJW50FprbW8",
	"rx2+DZcpXP+c7Pn9NX2YhBJgdvhcVMPjX9IwK24Tt1S/ZF/oePE1v+MgHAIrNxqsnlF0gU1Qc1KJNzGL",
	"D9mQ9HrvomjFsrehtRrstxritez+nRLzh6b7uh0cZG+Uo+dGLjTJHjiVWl0KcBywEJsIDhJbLHRt9ZAB",
	"PJ2C2DN3qjYXA+soBHc//gqo+4BgdcYEGKxR2vbubMxQybkaL2piQlOFjmSNNtERhq94H+JHejwWx/SJ",
	"2wDuO6g2jMdIT0LcDVax5QIjbOgN2O18n2usLuZKb/yChclN7H7pPUY76W32UVu7iHRoBwmXEr7KLffh",
	"I8cHXcXNqibrxi2Ee0ru1eUySH/zPHb2KHjSqVd5bMnij74einRyVIm2wgyGyci0LccNPd5DX6XSvAPd",
	"SWqM3ImnsrLSkWdfoOt+safjL/ST72vFI4Eezz1XB7NGwXljFISwXvlxr1Fx1V0qMkLWNqA3/eVCyt5u",
	"lQ67dPQ6fga7F7PFImh0imQFIAYrYgAW+vGtzfsTrpDD126SaDPYQv2Me8KtOWNdlEoifew2OC/Pzdw6",
	"Jx2y16xrwGZLpDlPCENhO9B5md7fEEf9BX8FSnrupEpdLzEKSNUjrmVyzwzxK3FQCxcR7jC/sju1SfZb",
	"9U0E1TS+4PrMZxBbrkihpSOEksMS3RxoO5BA7AZuFEQ9BVgmLsA6cHS+obDyxbMeUkFiFK9K58QqXZYz",
	"ruskHj/rZ2QlrYmQ1tZImk+QNvEf0myTIVkR9fU8e8T1000ZyNi3Q8xsucCBEnMQYddYRKy4+tEQhwVO",
	"gvJFtqo8Udmzhgz+XQQQ+Cpuv8l8AZuLdn2z/rpFXDgPItov76tDWNurJ9tiHp3oH1VAkEZ3bZAn8Qud",
	"N14x3tLucWOfQYrLl6DtY/BtYJsPt39cx1HnaQYMD8ZM3Qn8VsI8QlGPkFV5Pol/SWfFnmGE07Q3DhXq",
	"PRSHe/xnEYZE207EXrFIlt+c4pJ7BsTvDAN5iVzbsUzb3WmHfij30yTheWo7cIZYsBF3OupMOHCj0g7z",
	"sw0lTs63S3/lNQOYBYuHQewwtwlen8A4htU0wasExtCPXmKr7DSjaIT6La7WOfttp1k4+BOm2eNuol1A",
	"4oXrGBHuO/IbgYR7GcfMGGnR+qb+wAazWjPfg0au32Is/CviY4N2Op0wmG0IIE4T7New12anOT30RKWj",
	"EUfY1wCPPYYVdqBbvTHhGjuNQi9M3Wt3FSd0eazDFo7LBkQ4LLVdp4Pm0+x//QY1ujBcp1MjYCJj8SRs",
	"L2M0g9j/BwJuiluv0ykOFt+kmk7ZyK9XT23XcQxZs3RYnQDDgHgM3xYYdLik+ePjBEY3W6A2XdsACMeu",
	"yMpe9GKVh9U6bFBgA1uBKqaLjrifUMzSRhJBOuU5+ARBd3TCuliQE5Z6ecJWYU+oEzZQhq/aBOAxTNi4",
	"by/+tr18MNU2jrbI/GDUDrLeX1Z/a55DH5UX/FQ//D25qtadeBDmRHcg0H+Wdh423rz/GckOcbC6vvo6",
	"CT6bUAmKc2/fGMcB/1kYU557r8+5TSUGr4NMZTFiVfQYEFGgmAVNIMLPs6sZRswXRxtBtfDdT7B2NZvQ",
	"SAdgTbympOdmGI+52ZjHkjGLsf67vzk/AH/f5o27G7ZD5f03L35Vp3tzxXCB7iOpC2G0iVnj7qor6Zbm",
	"mRC7q1CRmMZlCfw7Mn8qBhQbf4hWFd86YaiiOIU4f0PTf3DXKItcxRJ85WGdUs7RJRs47kLy39BkiP2S",
	"XvBIqsa1cdvp8FFM5QXmv+12c6HLiXu7boAnrjP1pmJHBwVx8SHtLrpR0dA7To2mzOIvIrERYf15F02f",
	"BeLGTwtfqVMduat4XV9tOVQ5prOynyQ+lJVBNVBCSPIqSu1N4xpfL456w6VoN/ZzIXoW8Gg2ExICxpCX",
	"ewMuovGTLA6ezxFzJfGzViQXOgSKWcVJ4asNsE7/S3iiLnu9GzGE6ntHEtsjYWJFBQTq/sDAWJCNtiVM",
	"S6rHpRCfG+p8t3SPDoIujb3mXnq2ALeGVW7qRGJR/VSI0QUsAv15+T2s1gtrqJvpK+HgMWEeSaU3AsE8",
	"HMRaPq0/QPw5+cssvR6C7UKqrQGHvg88DGYAcaRbfRis6v+B6b1rq4baVcYpvzGRausXOoCOSsEkEETi",
	"v6p+jDyb4W0cTY4sT8Zbv4RKPd5PIdpWBvT5PoW5XYks+eM155hy9YmnjBSE+dMV6ujBD9ZMYqbZDX6b",
	"UFvVFdrB0CdcHsz8m2Az7DIL6tbZuJE1YRa/IlHc9zz3kQ1IU5GENJacNJ9AhwW829DhxSK9UIw07Wlo",
	"ABrbJLnWlufpPhfHLUvrTl++8/QKpG9fXbzRoBfyNASpnuEr9HkzL9KUSqdMpDkWsUZuKi1IMd6fEFk8",
	"2cWURHh/3gvghxDc1jdBbBWrHR8IcW08Nl8KcXXqT77tkD+weVlR8xNMjPbqhdWRlaOCPYcRRi4C1EMW",
	"9b1EJZKD4nkGtR0+BY1Yw/kZ63u4m0CmvvBv/D5Cq3QdhHU0QzpLWAzRuWpZBgQ4tNqWNVbXSNbsm7te",
	"YdCiYv3WWJvuwM4Yl9WSvJl4G+VqjzsjWJxtNNZA52tOe0OLfbrqNsZD5MP6/I4vZd+iGrO7wPVDTTAI",
	"j5+AMRZusR13y7+TQg0YVgegO/c9RbtTrpiy4s8Yu+9too2Ta50Nkf6FCOFZ0H/HSizaVi3ZuRIlT/hq",
	"WwQSvwWXf3bWw4vdEruhVcL2LmQriG4/uhUfBZRrA0JYYQAJSI27nsS5bTzl+gt6DvqQRWcISEDqd+pJ",
	"y4n3iknfT/uSgP+1xL7eGYX8z5qWHov2kUfU4ZtiX3PU2GChPtUmv8b3OkkSAW/m4u1ygpX82TOklg2P",
	"2wfnIgdKPRJk4/kuFj9bLhR+wBh3QGVkF9qKborFHewnLMgbsRDv5c2hOIwE+zX1fr4FVqrKBxD1ITmG",
	"roQ2UkQAjuSE/EWChuTbYZmknycoPRv4EHeYEO+NweMYFWML3W7hM7uiQZKo3lVI7qCWbFXStouCt/l2",
	"rK69lijzVnT3O20f4dV+guVjvaXQm8f76RYP5z32jbC15ODH1vokb8FoEzJ+H6JY9YhZy/mIoE7Q2mwB",
	"Nk0s4ialn/DXNw885B2MYrQQzMJkeYkEP1yKxxJq4kOqbfosmU8pmQCDMdSj2xpi5kNhaiEVP6vgPA9T",
	"BhqrKW72Xtr9An3xHe7RFB+J6INx5S+wKI9Osz/yAiLM4ePS5CDh8/GIAJ3/3D0a4vpIGgGDf4hE6Brl",
	"+hKQVA8ZVDgEa6RZ2SvH46tgNiqKFkMcxHxaGCYlXnDDgGa9DZvo4HXM3oDcW6jdS4g2pf9SBY7ESvBY",
	"pJWkii5NLG3tkyH2q/YAl2fQCccB7UaDZpCGduq60IgDvw93+vKQUTJBtiRVaE0uj7hDimoSkP6iYkVG",
	"mH73l/BdHUnSGaeqjW2vbYHGnzIX2RDTdd0JRE7Ui5Vmq/m9zjVAmDGMk8ymTYyk2ey0TIlNeCapoG+O",
	"FVuNaECfWFoq7fOMr29QUbLVbJNt/4H2so9m4GTnVKPdrWQbbfk21VCRSREfZBRN5TlUcxCJND9BaQi3",
	"QNtynD/cN+InvxyKdeHvk6EUk+sbCoJ7M3qDjlvfXPDDll0lxtdELu/P4xcfdGlklwS4nRlEpGVgLG+I",
	"Cv0kCSwq2BiWNfXsiIKT5vc1FIniw1Ra4nIxUFPGIsLA/2KIWaD4BVPwvjR9f00wUURx8adbkylMk9Lj",
	"PUFsH2tlBmJlGesCl8RKCMJU/2RjYnyFq8Z6cXogMFm6iSWqkYbywuZgQShQPBJWwxB24ZiXXw2a9MXN",
	"K37k+Qu+8hNsMW6yLS79ijQTTn2q7QAcJFLN6Z6DmSUDmcgl2/IaWomJ66wQJIMBmVieoVMjm/hIWIyw",
	"7pcziJnfF0ibW2cJB/StwF2MrK6eQFL+kdj8KtPDx49VW0IVYeAsYlGDdyzc52p9Uxj9Mv4ykhPs6C/h",
	"DLZYWKw6JcZNYYJXZHpm0vbid7Tqt7j3SUXeFDNXMXIGnmsRDRhQj1/LIwetI4yLcXPGJxcGYBJLirtM",
	"h0g2dPAoCkcJZkWLASLG8e2Ai7yVvcwG7s66g3njGDf7MVGSbuddvxsevnGPiTBnx/8RQOdwTYI6SZIY",
	"m0tG4c7/vvO1x0Y0izkSYUISceIDd7cC/B7b20xlfgtzWWyfC6bUR4dYaWuRxakvMDCRtpZ6/LME9DvJ",
	"5+fx3Hi6imWDu13YB9Pa5gLbfH3MF7glqWjT1egL/BcPOgsmB8DYhNiNFfgRR90uy9AZIsuIjCU/KSlo",
	"sMMdC1LkH6Ef2f9KsaPDf8UWjo/ddCwDJnEk+lvcKy9oTZzkK+aWJsOgpGc7CGvIBoY0sQydSJBFkq2K",
	"G3HLFLVRWgYcYlaynqeyOnBkOVCkeyGXubV4moDUCdr8SsF2uHnYGmJm+GTGuaAgJ7ECRY+6ainqGDNe",
	"Hz+UO2tK//Nf/031vyEWlc9o0SWL/Q9bOahJrgGHNYP+n//6b85m6AHoiWlUDcDYcoeY75tOe0JtcTxu",
	"GXIbLJ+NG2aZfiJO5M9PPXZDzEdxKyM0bfdEcqBMIA7mQiRoFpBmh7FMXqqU/jrEDjStGSQS4o8jdjWW",
	"w+rv+jdE98sUax/K8W78n+kfSX77rjAvluFYsUmfK/7CBuzOXnzCSHK7byPzlV/dJ++gQq6fzOlXyo0j",
	"yth+wTEnw3C+3iP0z7RYRQ/MbSDhAnl7fMu/ecuCEkweh0nRGeMtn2tgf6cFtLuWafbDDaExjYjfPuQn",
	"bn00biUXBIpiVyRr5WcbXmOBsMum2ci42huhDvAx7NrCY8lAM6hHqwOHA638QCE91E5hrdxpXJ6KaOIc",
	"61xmDlZxAr4gdbR6kMcl2ciBEQLXgQtlF8X5s9dgK1Z9G7LJ7/GEpvDJ5U1+L9N2HAUeYOFeb529LXJr",
	"o3H2rhFuMQ3aY+T/eozqNlVgI0Q2rBacdwuZbLwOsMpL3nZQNmprRQEsAUdFrsOT2ejwnUoLBMVrv8UW",
	"ZvZBm5ZY5xRu6Ne5DT6opudrujunYlawcF6PQq1RWHzCepojj0GLPUlSrR0hCFmZHbEAIn5GelpihTN2",
	"mX5L8DH/Tep3rncsbSgmi0N3N55BrsIoOZdyIE3iTeKyTwmzBJvV/bZptXAsY1Dswi+2wd83/NFDR/Gc",
	"/SGm4cbBK0vALvj2X51aVSoVyzmaqMQYVvYoe5QR+cpkiIeRXQ5TFJfcUPs2CeIZNFZdc4ICRARqnhO0",
	"bfs7mduLprVxx6fMmz4+CdQsrJPV4XnPNQMQ5iGIt+Ks+t/GJf3QkMxwjaR4HBJTPMUXS6vgUFWogB6C",
	"Mmkg3JwtFipHQ9wR6CaNtlzu/+avRjGKJ7auSqyQIU64xr8T7FORDq1xgLds8OJBSYzcAqVt4GGVr9aQ",
	"mEps12LB6X4tOb8VR2AJ4wmyR1LPT3qjWMi7Fw5TKyoIjpxMDohIqy8542Ntm8SOKGUgEtqJiMCJFkvi",
	"3VfoPeq0JqLrQGAGofZv85AQhNJRio/gfyJ72bnKWsBskuqpeTqCsZWzeqL8lgYM7s4TOOsChwYp+5Ja",
	"pB6GMiWxCxlZsgA4VkovFF+/hupSW7R43Irp8aic+XunfPwthdxEwar62ZEUUFzQ0G4YU5mIcjqsS8Mo",
	"tQxTYbrbZ1MkIVW0GkkT/embizW5RvGf5+3vvLFo6aedduDXy3ISwUNHSf6oneYN5cPvVqdKamOG+PHH",
	"Sm8CO03Z0mb1KjrWcqThvjWrhqkQ7icx7m2l5gSo/EEs4eeHXdsbMqQSFR0ByW/D2B3XFezlAMHsZxnv",
	"zqY4S4uXyMJzTHzxhagxOijLIvsFX/zPdL/1INtFv1Pn4siX6+/gequeYJu3QNcReas6K2dK4hi75YS6",
	"fK4x+SGOcnlpPyY/xHHQe89xkwocrt5bNtCgrEMW1EKt7hogzCZPEEuM51OJEF1utVnwrYaORRdZU912",
	"E2ND/P4T8ufONv0sCnbfkygUGX7HQRiwOAUvM2RR28wEGKMhZmFAog2NODnVhlRIn8ImiDD9HyayI2fd",
	"iZrj0DlE2GuQQULjG0ZXGqakIEPnZxzzNWIwjdVQArwKj+TlbV+ZY43j5IZCXale01oPUp9QHhOw+bgj",
	"7LhVEVG4fZdiUHiDfuNuhDd2ybfHhNAQv2N7GzbRmKI3K/15z1bgYbHIG67Gm3auBaMB0Zqqoh1hYAPl",
	"fCCweEbeOG8Yg2Im/ovwdtPcI+pn6uxkJtqzEzh7LiWVEuWPKZ/tOAAT1vKU52qEjGaiZWU6Rftlp9LC",
	"Qx9nRDt8d0mGN1GqX9221XASvLCJxPSN3NUk+Q4Iv/u+4GfRrw8v+rVWomu92le4s26ofzrHrCf6K41b",
	"mm9UBjOhjoBvChCrPXEp/eRa1pNB1TL2je1YdEnKCZ/8BnDpUPPvn1viK9y88ttGB15ELUVsQLw1LDBH",
	"fGThsP1oZOqp0MHQheQaqNAY0Ijh2GhpigfSVTBaMuhwHmEcLsLE4rNGYbWZMuNIoQGqN+vwdWVU0oEL",
	"KPIfcX+wCx265v/3b0UuV+RHIC+//uv/nKz+JT8dff2mpIuZ76ERf/+f/5V6NwtN6subVFUHxHTdDRWc",
	"2qvoTtAI+SP5aZLg/r6tq/KPYuj+ysmvsl5E1vjj9pDvcRUlPu4wbPbY0M/gSOmEW40tEpB4Be8n6x2D",
	"EHhDnvaI9cj84anj39YI4K0M/422aZG3TsgsrkLqdifxhd225OfW40D9db31pH8CyZ+Gysu4hJxgPw4E",
	"tHT83rf2dt+nH3RhO8esrF/hlvzKcLO0j7i41VKH3pm/m4+6Ln+Cy0ir2Dg48O6xovQt8yyHnzu+tuXh",
	"KbbmOGg+u2BZGGMH6KuW2h/wUNgIhNjsP7IBPebBNAwWqRKFG2PKcwe5ca2ntqpcke5aoZ9E1r8l3tOs",
	"6xCLXeYmDeaGYTqvaTnQf2XHigO/p+jHEUqsukS1QDD+YNHtgviy7uxMXw++9JuYNsIJlBuM2x1vbR7e",
	"u9auOPxPnnYE137+aNT+GTyTAgVpnc2oom8bRGDAVb/pRGd+hDHOWVyKAUXq7y6BW+stq3+EQI9wuu/x",
	"Tal/xLoxWBsjHtaHrEHkULFB+d67ZcVKd0w2y7DIC9GaOugwEWXBYeUyYoP5YFOX8H8MoEMSKxSdesjQ",
	"pRkfEqnXFbxwPcz5B58tTRmJabOHH7f6DTFPQ5WYkd6AgHBioCVEIA+ecVgutU6TDZiRyl9POaL/t0cb",
	"6SCqbtUqXkp8SIhVts/k71gMTvO8pFnmKHuUe1ufEeWE/JXer/MnMKQfrONvYXyijMHpIrlrAfWzBOUO",
	"1s3Amx7xSOf+3TmpWGB3TpoUhOdxk06oz2jsPk1LZ4a1N08uqju8fXJ/xjdODqLnDhWPOCD0l4X4RUC+",
	"AwflfSV9NopIxBYk2BrrNwlfEXF53o9u4b9cn9HRJKpFVP2gY0IatEe4EVSFGI6Qy+v8gKBNCG1HMMTB",
	"FvjBI1XGDyUwF4xj7b6AOgVtm201CFYVZi/LT8KXpN4EEihNwAxK2OLWV2CwokgIj4fYDxIMKJOxf/r/",
	"3M0sRAB1NKuLVekAugTQdfr/iCvMQyx0YvZTAPw0+9xPDXMtSQMupFG9Sygyp3bhpBWfBuipk9lnvBmR",
	"4mmkeoMLxrszSjbn14+4xbfikqk2/4M8HC6Il84koccD5xXvy8/pk5/SzYHuNCkXh52C6k6h8r5/XjIO",
	"PcV+KTjsiw9IvAlWToLth+fYhHr47HJAuDXqPtSkSAPYwkE8JS1w4/E3Pt7sX/RGzx+xmr/T9PZEoNVO",
	"t7QlAhyaNEAWR4rDaTRAJvLCJR6xGVuOf7euLn7zygJWzVfzMWHz2gxA3ApfOnbT9Hdf8rOpROsLljRM",
	"/6qJgnyrntSuNPaAA7ALWQTCEKuQiRz61qTXoGnUYUENMnaQq+tPC7BGB2PiOgCJxJQdFYvY60jMGWJn",
	"4VrbF67E/GS+cWiy0IpDrCNrUl6QX1s4Bgzh/DGEXceik9AfpXhsUZHjTvREDKcrkb8kNkpiMOV35/Jc",
	"Nctht+1aUr3bLhWVDFdZpAUEjkSlBV1YVGFQFEVhdTdph3BtYlHPKUUt15IcOIPAkILe4Q5k5G0Ze6jf",
	"B7Q6i59j1W52a7Z/ZDZpAmioFy2GLz6OzyoPN67dtlXiOYl60pgyEGfr53xI/NerZrnbZhhZDkzcwcR1",
	"bXLyJUoeR5YzZvW9l7sUARet+L8HTXq3baZTqxaK+aJk+N2M41VA2spG1w349un4OCZM/kX+3moGToaQ",
	"ZxjJyixG2vTNKfxBsTP4zYo3QwQ61378k5hHDI2fhhXCdaD+RAfHb8nPLOEclFGmn1Yi8DuhQrCf0b/L",
	"HvlQyQbj+I3SlsyxwFqr3y4keOwc4u36BOLVCRy3IfrmZSIx9PDdmHgOVYLcnQ4qhsZOs7QwjOfbIayo",
	"V1qVUI9YZMJlfAniTdVmq7B4K/OlIvkjpZt2t7cl8+XNPDseBvVWenKShN+a5xqUvtvtnUWSWiFRjBOx",
	"rV06mB+Nb7wSKUEcG8nhrNKRkQNJqNVDJE4upquRYc03IzmqInEk8se+Y6ROAmbrP5+O8JQcQY/eiDyH",
	"xM0fYVbRiL24+P6/zLJfIjMFoQSpk29+ItS7Zud3H75B9lPqO/1TMobXxSrMJShKUVJnILdiM40SAZEJ",
	"5YyABgPrBfPdUaO6NRohagPhdXNCDV+5fZW7Fm3HekXMflIhEnLJyhpC5xIGJtMzXCS7ENMVmQgbYh3a",
	"hrVgfsM0LcADNJewLjNYAuOxA8f82mkxRieUPLjaBjuIv5f0EOuI2MDVJlRLMsI9W0MxrMJWzz5VgTaF",
	"WKdqVIwKRzUhwiN+VUAQ8Wu8iDBAQW+aRT8yJKA5FiG+C5ZCg+b6BRHdtuew7j7pIQ4TKodgJN+EhxqK",
	"BABuIBJlxwjkFY1s6NeVpI5Yjwyxr+ixIEUWA69ZmHimcI9IDDkt7DJFj6IYK2hkG8Clh5Q0+h0r461S",
	"cU9jzLFrSRATz/GTVh1L5IQiqn9h3aAgcC1TRJWpi9U+RQAgNx0GAdNkiOkyOqIcSfXE4SDQJoG5HmHi",
	"shcMWWBt4ljY8ohoEYZcKvlSYZwOmeZPUpmjTO5I8ZuuARulTlK5I+UoJ2wljAt8OZpDw5CZL/QLDyWT",
	"te3d2ep+ZgyJYNsqhozubhyXHNdhvnfXb6ESfMCEsh9vseCp+0YUOf0YXg7CIQ41iolk+Vs+a6SGqdQF",
	"dO+gYVzR07VjOs+tqogxYGQVJYmhB+O+xHSw64gfGUN6lSc8qFOEvL/K2JJ9pJfFgRj4+Aj6TdwtBDFl",
	"cnLs2fpVbEaaf/jFrK0wg85OcN+MTzwE9h8SGfn+2wI2+jLLfAGaEReo7TJ2TfM4ACGWhpizJEjkYO1/",
	"RDuMUB8mv/0nZaua1DmtVCUm3k3LhVHZ4lo+gx3i/v2WK3U9B5N1nrzSpCIFH2KvsGKjQaaiGQddFdCM",
	"FaDTqbyS+ejrDbdyDi9V+HhMYvoABgaPRmXh7xEs8hGGuSvjdbh/f/3+NQHdoqrSBprx+ewt/TtpdDoR",
	"jVcorrK0uQVxoemHjcU19uSWkiCvTCAZzaYPhUY7cIyIC4OU07iGFMwrGGhTHpHAKtlwFUNHcReIxGju",
	"UptDCcMo+q813wioJlw2PBbdqXeE+Ife2CFJxu/2GnQPwXW+bDvaZ/UXYX9eyX30UkGewp9JZRFaeqO7",
	"RxwlRb6hKv1aZXtqXmQV71kPmyGO4nBapOByvyeBBtRc0TRmk5BMgJljIT3EluO3gRG69Rpl0EnT/pcr",
	"4ow2ouGqupiH+rjpU4BONgYIE3ejE0+gnm5sbYiRyRvsGAtxCqivmubE7hFwaNJrHTsrgmZteJzV1tff",
	"XmsMibwt4uJ7snAmE9iVEB0Y1Ek6kqT6SAJ4iKN2VERWGxOZHizXjYd3ihMJvwWDOfHYg5BxO9tBM2TA",
	"MfdUT6A2pfZmIOocxeyC+c6j+CVUAyv0xBendCXTIi7joZQ+AjUd6hL2xIRDHJlN+peH/WeTuvBz3P8W",
	"rN9ydL4jdRHUZMXApCJgjC2WC6YB4veoov77V6C5kaGr37i3N4HHRqgunQpydUlifM9qCLOhnNNLuvH/",
	"xkI4DtDcw9v4D2fPeSX/0etgy61ZHv5jdC3imSbtFuFn+K4hIY9+/ncqipw0SNm2YiMtOO0HlQBZZDEt",
	"B7vefy9KAzcWiScCYYc5pQm1iSD0hyBIvrCVYTvSQIr9nvq+QQ3Z/aghijkffqUq0MVWP5Wi310p+vLN",
	"inQV/R5Eg8e2G6J/X+/1kxaGUmb5ZHpPWpQRTwf9kLglDOGRA4jreIH/KEo8fP5N8tlofBqH/ms280hO",
	"ll8Xg9fr1o8+pcB/qhRYQ/v0p8b/B2v8F9BdZzY7ap1vcQzlPQLzU479ErWOYkP4UrYrdXu9OaIyMPrw",
	"sL0YzOzzgK83kfPG2w0599QNeezAbrqh8oZwJB4zGdP4kkUQ7M99crzq7H+utCx/9Dp+OZE/j7gEQu9I",
	"Xztrk4c7TdK+LVv4reP6i/8JDpUtlP/pa/klvpaPEw67kwF/Dx1ggQ4aMkkX7D8kFQVZNRSb1+vws7AF",
	"h7c6oh4YOr+opRSk4vi0whPlRXgIS+YdoaDKOP2CzXM0xGJpwEtL4pC/yEB4KghQvPS4GTZozeSvSgPr",
	"VGTw0n5D7G9hrdxBQEIkTeXShO4qkma1+YLc0VTMwbhKWfXP6hPxu3VMDqOD6Jnv7dMo809SZpmNcuzj",
	"jC9nBRJ9sAK7n30z6Cexi2EzkQYOMnay75M12cyOpPRJSX+UOelTDw/xBd6KjhNhHGPYV+X48o39L9K3",
	"GnYFM2C2JFEJhLsreQo0lbwJbGE3ky3f/gXfSWqXJyobG32bBrVGPqntP96FJzwNiWSQ/tSjf4YeXfED",
	"IERcMwOi3wHGMkRf4wN15e3sYG85/8kQ/pMZAjX+buEGH6Qtp9/8VEjTHUzEAe2EiSaU9LW3oXiTag6y",
	"Gr+hZO8mi7fYiT/17U99+4+ze3+Avn1Y3HZcjdYfG73N9IpVMlxS7HZC5HbIAwzDCQ5hVgWMzWVFMKW0",
	"sDzGClm44cLyHMma42hiEa1QNsTtqQsS9RIe/r3mffuL7BcJnsxpPyJI3PpHhYd/6iqbkSc/2oInTAU7",
	"UMFh1rw4KthT44gSwbsse+tT/YeT0z9eRB8av7guh7988//zoODG3chpNyvYGkHdBPvaySJW35Dkn9ax",
	"z9DGT/XyferlTzMcrOQXI/mDY8x2lO+e+z5u9IME/RvBaHFXu7KZfHK2z1f/L1EpfJv81ooMYlCYAQcB",
	"zpJ0I6bgBXOjMW8iXtrPmRAVZSjy+5PKgnU7lgHluOIrR0Ncj5j0I+b+tbK6EyhVLdP2XN6tKNQwK1RJ",
	"xtI0zyFsfwhLwN/J1ic5SwQJHBgfFlrjw+6gd7i/nc+ol98l6sVeXadvbgtu+OtPezcTEe7ik21QlDwc",
	"1vkXOSjdbwv6HhQXI2Z4V/6f7c/xGRvz+UL/MUErAsXi6Xp/afvlm/ivnR7uxC8cwqg5Lqo8/LbQffLm",
	"gnWIo4WORNdjP8gcSBogGuCVhoNMfdZUChmGeHpT4cfL2gPm/dcMj7g85QuM/TAD8UdyqAnBB+iND5nU",
	"IbxgP4ShmobtrpPZJ+v4NGV8XKDPVtaR/lS6kxMkSXTYwcr1Fo6ifGoXnyzi14b+vMEffpoVL9BIdrbf",
	"baXPHcx08fR5UOTPm8+IGOvcjR9YGBP98xnw82n6+1MDfn7gW+ULdUVoSTXnmhH/TGgoLTyx+hervSwR",
	"g6WtWiPpxbNcQEQVFcm1XGBIGM6gM8TwVYOiP5sYJSqZMf1l9XcJrUKTR5ZDS6JhHc2Q7gFjlSJLXzRD",
	"rInYgtCG5hOIJeAHOtMZ1qKI6fwO1CCaQX1VEY16eIbY/4p316fNDEaIhg+LgmJBX0UeLh20Ypv7RfQ3",
	"VqK1s4PWo7+c/W+3M+EQHN9nQgqEQAhTDpEHq/28KyYjPM2n4vdpVvo9vDRJvPjLt9U/3jApBarbdtI9",
	"0GYTIt5KaEc71bVaffAZ/vEZ/vGpV/xQvWKLzWU7YzjE7rIzV1AOF8yffOEz7vjHasNvfxUWwvtYUd7Q",
	"or2PpbgfoFArnwr1p4nlU2/fTW9nbQQh1iD58i347606e12Hpm25cKOfFyv6Sl238JUfVVpN7jdmDxrb",
	"D/EGazlQy+8EiwT/tSnL83G1i8ToqIL/Wbr2H67gh7yeAf5Gor3xSsE9kiS//ZGP4pi3jgsiu6nGvJon",
	"+JLr+Ij4/ZhZgAPCE6SiUIxUUCTEwy6tRosXQ+xPxuss+9Ota+A+TRylfntFJdjsDlpKIvMBup7Eelhj",
	"u22M5xCdZieuk9mZ6wBd//TzfCoh7h9dBFJlavyeWgk3ecQ6RHlqSzTRJmCNrP8KZ5+QQF7rJcig4d+I",
	"yjBwiIP+k0GyAzXEsCl4yJppedH5N7KeqeljiEWzyyNJumX79ieURgA5kkfAGFIBEelB6i8uol+4CYWF",
	"xTAzC99FwJGAIcFX1m6fVYwJFtI8x4GYFg0Htm0sRLnWaGMa1tKUtg0zYLAWtlivTeKpzFYEdXpYPA6i",
	"g7fbX4RB6sNCzPlhDrK18K18hpf/LuHlL/5V+o5dcbc/oSp4d2/U3EHEh1BzT6OEj5nvMEjEIfenHvDp",
	"3fv5VgJWQ23HoipsLM8t5Y6JjSre0DERayXNCJXHgoaqA6/KsbkTaEozBPw6Tm+WHMYWXvXyFTuhMaG0",
	"3bTwn0RYgnRO+z/TcZIDbcuhpefmE8gea3QwVRwQk4sIa8gGBmtHwuvCIZdtDblE+r/sL7Sp9f+VRgYY",
	"/2++9BD7c0DHl7r8W3pM4tLXnV+/SSIW76EtnCkOJJYx40WeeGdx2of8sIpvHXZ7h3AgdoxP6fq7SFdH",
	"XKQvXPnFfv0lRdWFLcMv2bgjc1iv9Hg0xN21PwXas2HhsWwwx2O0Zz2V7h6BPLmkel1nWm21/qV6RgtH",
	"WpRiqd/VlWwHEoj9No6hRfhMfo9GYQ0oK5IOaDXIEXSRCUNbE+sGpMna5YcS8WkNSkrmb5VMMoxNABxC",
	"0N012B9C2mIjFTHHJ5H/LkS+jiEhel8nlV+QsblOSKsahNxLGCLUNK9rEUg4/tsQc9qjxGRhY8EpCuiS",
	"hTV4WIBeHDnsqa1HqYEf+V3RefETftLY75IuuYbH24nsYKn45VsUD96IfOswNxORQAKZzawp3CCzQyPj",
	"1qimu7bRncoircHK95Ox7Yb3KPb+6UD7B2UV7kVh6U/l8ac65dbZ0l4ZVWvwOMiwtgv3+aEyfG8V+dNN",
	"9ukm+zHpUL9MF/niWC7Y0pLkk/3+GvYb+w7rWG48//2LRPXBX/PqWufgfLsfYJr4R7ydPrnvz+e+HEPj",
	"2ctWHvyeyAbm69iR4bKxO9gUg3F7GxL75NAK62zNT4PG72I09MRF+kjLL/bnmwfpPvjr3y/4QoSklQgM",
	"9QI9TOSs0HXfEgwEOh9g1KPTfHrJ/3Gl1ei1x9DWnkz/yzf6PzuWUwMrStIRCRETc4lzijKMVWNduOBl",
	"liQTmip0JGt0qFmQna5Pdq6MTodG7X6rfYW3vtZh/NMS+M+xBCbQT3ovHeinvc04le5lEItvQr+DFWyd",
	"2H6AWFM+xdrn++pXWrfekp7QIezzJN+S6iFDl8QwmjNuOWYQ0Lk1GsydrH9NXGDakGbb8+gyyfEwa8mp",
	"IgychQRcP2dmiF1kwjTvbEBH8FYKRNirpDGXxhadGo0WtNSgRuOw5xOkTfxJREq7bVjbQrcEAA6i3L3u",
	"WLx0xYK/iOL/nLJ3vCEzv7zASjALbstHaP/+fLNApJhtyD7AF/4yy35ZG7GlrP2qW0jkGx5FmGwaCNIk",
	"QOSYXD2LTASIZItYx9VaxIYaGomPjob4wfJY3CP/O8uekIYUlzHShylRkQJhyXJYDxJLmoAZa53RtiGu",
	"n0lVC2OouUF3Cd8YGdgodY+1DNEsHUrwVZsAPIax5MLbZgyylfAhDqKcCBjC+JmLLfwiOVBHDj2ECmj9",
	"C849ZsBAvBUntSCzX/qd690ztiauaayh644EEvPl94QEHB/7Zao7IIdj1qpegUX+MQhETQzJGLRv0YEo",
	"Ar2n7sAnKm6wyOf5NMZK2ui2W9IcqtIULpg9CWLdthB231QFAJaA44AFfVLYnmogjc5BJD/fSkjxxl1P",
	"qp/5PiNEiMfyxWggN+K1gqGzlTE16L4PQQJ64F8sJt95ZYY1RjHSrDJy4aqng4QwcgNLxhovYeQ7Mqx5",
	"WgKSjoBhjSVEfE8gu6ghxnBssRk4z6HNpSi2Q8zu0SPwSKqKRANWukhwiDCtrNhIINURYInXNOXWgYRE",
	"mJHf5h2aABmSbpkAYckErjahPIfH50MDUo1QWq9kz9bTLMcJs69I66gEZ19IhRXF8vnyYoNpyXIkbWIR",
	"iGNaioVPO8TrjcXoD/41cB1ZwC+G2XM+uxtLvWYIcAArZZiTxELfYoICxkLkUN1+HcpSv1M/+ggMZ8DY",
	"UV/jgKMcBAgPa/xF1wnxYOAdpz4mh+Wsi2MlyVSp69ksX4Vf8TAVQbwnSknDlEg2oS53+gfZteTofUr/",
	"smyeXspqXFCUQ3g8xMmSl2/077QQ4cKd/sT+GlnQdQAmNnBY+zkHylHc8r/nj6onzYFsfmCQYBLGmdXF",
	"qoYZ4pm2zx7WGHoyc+L9UUEpi7eZpEHH5SCCIq2WrtKpVaVSsZxbw+Uh5uv8a5jyHHyCoDs6YVYgcsJu",
	"/IT9LLsLG56wL+Xgy9TfgdxYzQZCIlhkI/MFKTSARNCYsiEqYDTgOAt6xz7XWNepNAMgk2wntp7wUu5N",
	"bGxT79JXxAx7ZiVyMjo9PNuQT9B/z7OST/GD5J9HoEOtE8nMHGHXsSgdu2uWDAmolufGBfZuVWoOmC9R",
	"cen7uz/UgEg//iUmhY9893wYZMOkGgHtARZeDtl32nf/qOthhIV07Yv/ltkqdKNy0t891yb9CRJpicZK",
	"Bc19fZPjajbkL8NvX7cgkbAV9FilxXckrojwLkYrEUcrcboSwsSFQA9YvQhXyzm6ZAPHXcTohEPMav/4",
	"TxtugSSRj2LUZtp3NRT15et+G0ejUtEXWjqXTXhNusfzCaRrVf829lTRwrq36lhzAp0g/G7zKEd/zPPn",
	"+/f/fwBxyXoaFrYBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.1/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
