// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+z9aXPiuhYwCv8VF+9Ttc+pwokZA3k/PJeQkEACSZgyHPqmZFuAgi07lg2Brv7vtzTY",
	"2GAzJd29e+98OHV2B1nD0pq0xu8pzTJtC0PsktTp95QNHGBCFzrsX8AwLA24yML18zv/F/qDDonmIJv+",
	"kjpNVSQHEstzNCgtv5Dq50epdArRATZwx6l0CgMTpk4js6bSKQe+eciBeurUdTyYThFtDE1AV/k/Dhym",
	"TlP/v+PlHo/5r+Q4NIme+vEjnRo5lmcjfeM2PYzePCixocn7EzMdvDX2vdiVBTx3nL1zrKkOnc1AxBIf",
	"LNmONUU6dJJ36I/4APyWG2MTid06I4DRYocbx1J4bPJOozMevtvwNHyvtmO9Qs3dgphi1EZQ8mkO3ps/",
	"A9+WA4fQgViDu9FLMDxhe8HvG7fnzm06mLgOwiO2DQKdKdJgRdMsD28DkhgsAT46GVirsx4Ms5WJOOg8",
	"Ap0LEyBjMw0T6PxFJEgHSkDXHUhIsN03Dzrz5X7ZoNRmSNH5tsCHDkkGCp/gYFCwzykAfvAZIHHPLB3B",
	"FQbc5j/RP2oWdiFm/wls20B8wPErodv9noLvwLQNSP/ThC7Qgcv24O8W63CIMNRTFEtsqEWXIanT/zGZ",
	"YCLXpUfJpFMThPXUaUozPMIEA90nvUD6s/IjHRmeC4azESujM8qPb+kUoj+DPDwZ6rom50uZrJxXh0Au",
	"59W8nFUzmZM80E6gQnFeTDbxVOhg6EIidsGRfE9J8eAgF3JIR6+46kDgQiKBOEF2tHa1P9Ipyj0tR3Ck",
	"7XfzLs9mM3loOabsOQbEmqXTySKXpRkIYveFQUcrqHmtpJbkIThR5XxZz8ugDDUZAACHxWGhkFEKFAMt",
	"yhlOU2q7c+80nXa7wvaqIwdq7ovnoNRpauy6Njk9PubTH1nO6EizzGMNGIYKtAm/H9vCBL4I4qCbY0Rj",
	"sX9aNsSIo8tu8I4Bza3NkSsG9rf186pEv4HYFeCSBB3EQl5jd3VJZeyHaWJNqEEDuVCi+AywblF9gW1C",
	"0E53DOWK3IXADBOPYxmwfk4JJ1XMa/niMFOU8zk1I+fLBV0uQZiTlbyilnLZjFJQ9NS3de5MP/7msyI2",
	"k6poiq6Vs7KayebkfEaBsgr0onxSANlssaCBIsykvu1OBEwnScT/M0ufSz6kJdeSOJAlwFWlDfdwGxLM",
	"n30dmgkpqv5FIrpG6D6AZsLwTYSHdTkuA31saXswi/AU+4MLr+00AWx3XGf4LKZuzmWhhYTBwfVQjk+6",
	"rsNiGQ5lVS1kKc8tyGVYhjKAeqlQ1IpK4WS4Dz6J5RJBJA7oU7K0fFfEQsWwRuiT2CiX+aepVwseqYY1",
	"GpH/BwhMokzNBS7TDOaNsXqpoVvUqPcW9UwL1UkdtwtatV6sT+zHfrVRPoLzxkJ/qKNbVH9vvjaVVvcp",
	"d3s+mdXRDKlmzX3usMFTcJkftS/LBv07eKgp9VfrvdW9yDZfm4XmeX0+vD/qDI3r91m70WnC6+ta9r6b",
	"H87sJmwMc8W720lx3ui/AP2ekFlB253ThqG2gcPWMYUY56wYapAQ4Mwp2lJhZ0wpmQ+hDh3gQl3qdG6D",
	"B0jsVUUfDp9M8815hIL+IlLFc8eKVNfvVuhepttQwujOBVz9PHWayhYzReUkC2VYouJTLaiymi0N5fJJ",
	"LqMOs2UdwGwqLb7oQM2Bbuo0dZLLq1o5o8qaBqGch0VNBooCZZhVM/lhrpgplMpUBSTEo3piIFmBZlpH",
	"bDsMyfZgNhFQHsRuoi/G2At78ywXkIMuin/KVMJ1JfDNA9hF7jx1mqVK4Jrat/ydqn07A4WvmQiMimFY",
	"MyK5YygR6LoIjyRrKPGPYo8flbVc0/tsSbX2ghpajqRbdHPE9YbDEO6ac1kMlsXgJJatAKCCkqLLxRM4",
	"lPMn5bKsFvWyXCgPcycwq8Es0Pdh2VFAHKALrBwyFtquNYE/QR+GhZKeLytQLmaHJTlfBjlZPdEVWS2r",
	"UC1mCjpQVUrQVHONMPfavdKu3/T6Xcqbn3LtQv3VQh1D79F/Pz8UXum/77v1TGuin3c7dVI3+zMwrxfh",
	"vOHoVxM+x5z+vTXXUb1YNypuq1t/p99DJixqSFMK417mbP6Ueyq0+w3yYNac26v+uZbtK91sLQu6jbza",
	"ybjgsXb38Nqf3pu1Vjtru5pSqKpIyYOLUv6+Vz5XL9vZ234zp58bc717dqGej4G6qF1o3fH77UWz8NCz",
	"lYfLxhAoT+im2mBnuX/o5fqdzLk2cclTrt24fXxaNJU26T7USEd5PnuelJ+0auYe9suLZ+Wp0H3VAVAK",
	"rftJ+7w96V+rSs1pzzO1Lh53tUU927womNAc5Tu4gTv4rK32arWHq/H0WbGthys7+/Tw3LzvNMo31YYD",
	"Hu6ZbHy+Gue0bPm6Zzxf3Jvv3Sfzfdoxy/Qcje6kMdMvG101m3nsGWfP2qRwAx9atft+uU1hqF8Zs+BO",
	"sHJ05DltU32/yr6ouHTTNMDR00wBuTfiXjUr1/gdzCb1J+xeadPb6it4f11M+5mGYT415Wy1q1YzKNt3",
	"K6RVv7ZujVqjULzKtpSS3Xwq39rPWc2bVK/uMmf37+S6SbR8pj8z6s9P09eas3ioX8Bzq1bO1ky72r58",
	"WLjeTBufPegndxf3T/YQNmqN7BkcAe1yDO/fhu3Hx1yh3Tqfy8+3Wl5/mHjTmtMv1TtepSSfvGjw5Apk",
	"Cx2n7XXawOkOmy9nN5WMd155uStXHl7HZH55fXudrU08cN5THs1H4+bhfFHUr/XrebndcNsvuNfTiPHq",
	"grrZeHxtte4qZuMto+BGQclcXL/Ui83yWa7b7jlvwLg9M/MTciJPzdrLSLvIEHA7zVY0dFG+y541J1ox",
	"V5iA81y1cGXMH7rlQmeiF6svtZltv973pk+9J2V+cvGWbdm4P5w85r3OnVka9s7zqtN5vXzAV83WRWmR",
	"b2Zf7oxm/rrzXEHwpm02K69PhfeH0uPTi1d9dApYlUsds/JyJxuv1f7t3V3l8fzx4h1k3zvvaqUxdZ7e",
	"HqB3ma1PK5OqAtSibb0abz1z0n6Y3j4WXPx4D6aF6W327bYyqj71xp36w+NCkZ9KY23R7nVG5935vVko",
	"z3sn72/9tyqaz6rj0aNxm8tez8Zj7Axv3luG0zzLFx5vjcW4cZfRcufV0cnzw4l6+3J/UlFKl69T5/G9",
	"a56MeueO/Er0h/K420Gtxr338rLoNGt3/X6r+4YXmeZ5rQ49goqXDVTuV5XKi+U9En2sta5x8RXWz/tl",
	"HTffq9qret8tvJHqxZsl97Tq5fRKeZnlQXVsG3pzVLq6vIO9zvMYnHVuMnNMXupKtVypnNdgWTcfW8VZ",
	"9erMKzWqc7mbr1nwsW30O9d97zJ72UAlMlxUarVxEV2P7x/fr8zCdavygiznrNG/uO085vSb4vVt73Go",
	"k7NhdzHKgaZ1MbezaqPcAkBzL83avPHcLMNi871T6r2PWsXrK3hyqXua0rqszc8cL1c1mm/Zs4U2vn1X",
	"F+f3LxYqPFkd7/3GHl0auXfUGLZw1Xirdd8em42TgteZKC+3k+vR1LyCoHx/2QaAvBceKzcdG9gv2qT6",
	"PG09vV6+WM/jvJKXr7uvNsiixuiipS1gr5ut5V/fCmWnWq30as/94dzLvblnFdgwYb4/GmO1OwX1bkO1",
	"a/CsN++Mnq417/L+yJveN1+R0UOlhqbPL2HuRgXuSDD9lyl00BAxtez54V5pXjZeny+f5q3uePJ8/jRv",
	"Zu9nrcX9/Lb7pLQum8rzw/Nrc9ErPL+2zeb5ZPH82p+0zhuT1mt/3HqtvD+fPy2eu/3J0+JJaZqt1+d7",
	"K5VOjRyAXd9KEjFzvAibSYLtRUg1ZnjhKtvS/rKz/A6L1k32FKoxS9kjRWIf+C+wtKRZmHiGy1QnBxpw",
	"CrArsdFZCWBdYoYYqoigoRDThOkxQ89xx9CRdOgCZMQrWZ6tfxllfrZRhgN5o1GGD/kyyoTBtYNRhg/9",
	"MsqsQIVA5wPvpcPfNEszDdBcNGXGaE9lkDxNvVpjfKRbcGnV2R1A9EQHPHzoZ4kQQnhofc6DB2gaJOSF",
	"se3UaWpoWam9ThbayTZ7uz/8SPgsuQOAu5w0oy3+vd99h6mM/YR120IsruB/3yO+dZJKpywbOoHHSVhF",
	"GYiBnvIJMkX3bkAXpr4t/Ua6moX5TF7OAIpBhVJZVsu5nAx0pZjJ6Vn9pDRMLd3DbO3YnSA8dABxHU9z",
	"PQcm7Si0cKlYhEApyNlioSDnM6omlzK5gqyXy2oxC/W8CoupPewcQDNi7RuSgYgrWUOJowMV265jUbn7",
	"Ix3xBx5yR2E2xU5ImTJi8Mgq2bysFORcppvJn2Yyp4rynEqnxhAY7rjjAtcjVKNh/5ynBFAgzBeGubwq",
	"l4ulgpxX9JJcOsnm5WxOy2WyhawG8sWQpzTwPa6EGtCp9HxRUfQilGG5WJDzaj4vg5JSkkv5oZodglzx",
	"RMmmlm7/PXyIzDpGkIURHgUHCf742z2hUFGLoKBnZTgsq3J+WMzIJb2Ul5VcTi1lgJ4bnuQ+2xPapmQW",
	"h3044vhcd3TGIp0L393jsWsaqdPvsRhtjRCmuqTJrc5c+gibM7KwRFFSGjqWyZRTzm79kJ6/B6KDTD47",
	"LOYz8slQL8p5oJZlUDopyLl8XjuBKtC1Qi6kA8ku1Uc/hOU7o2xI1d1p9gRVNwUUWNbKOSDnQP5EzkOQ",
	"kcsaGMrZ7EnhJJ8tgVJGSUUV4t3W21MhTsRNEbeFMMOSqFLnYws5BF3+94Uvfy98+bYXwpDNcpSPYU/Z",
	"WLyhjOvCcSznQO42ghg6SJOuus0bCdKJJBuMIJv7dTYhhzGwCZwLCeRMqeouF7IZJgUoVmT09xmxGu3+",
	"+ZnRUQ2rYc3ccr11ZrtqxzIf2ndPTut6rl1UXu7pN+48dZq6qKbYXVCBhEapdOqd7v7yoaJ612cYK2+P",
	"5LWEdP1h/PxakJ+7zXwtrxecBrxWVeP2sq/JBdxo9drkTj2ZyM3xxZtTvq+gwus11k+MiTm56mVNDIwZ",
	"ub+7TqVTdM1KBdpV46FTalo3N9XFW/M+qxq569midgI7TzdjreOQSWny5LVBq5UvmLjv3ZOrfO7+tn5z",
	"cVZ4fARX43mn0x71q8Bszp4ferOKM81M9tGzKGwfoHoN5x3oxmNKo3PbkmZQlSZwLhHoHkndMSISIszp",
	"wZCIEqou2Z5qII0OI5I7Bq4EnFAIny6pczbXANPJmB5P6Fww9KGkASypTMixRwYzXM3FbMJkMwNEImiE",
	"+YzuGJEBFiTIsIqbkM6ALrT9wzCMoSpThKfAQPqLkMupNP/lJQolX2qr9JUkPknt6elkVBZ3Be3w5EOA",
	"DKhL/FOJLcTOkJYEBftb0S1IJGy5TEUGCA8wMIxgBHvFDRE0dBIC2tJv/edpFSPLGhlQRjrkftVfIy5C",
	"bvVMJqMUy7lcqVjMy7alKVopo4/I0NMdxVE9+1XxsOe8alM3k4VHwLbJEd8zFQECyiIOI8aJzmSL/8WH",
	"POkbtNuldXTpM19Djj9TifgXose3w/Bji8KwjiNhDtJhr7lNCsOOfJc/C1/4P+OZrmCFriUEg2YAZH4a",
	"161gycPw3YaaC3XKXD08BlinK3I1xtI0z3GgLuShCeZUcgHJdQAm9NrFOID1Aaa/Ek/TIJ0Ls1Ba15kf",
	"SVJ9yESYhAj+i3sfNEBgWrINCAjl1bbluBJyJUAkgCV29SF497D/BIX6xwAu7Gs6xIiZIOIgvhKIyi/g",
	"8yAeN7sv1oS9h9/0GBAJvttUiHFYsCDcqoWHaOQ5+1qAdtz8+hqxBkQb4vo5FbrLcVydoSo28FxL1hHR",
	"rCl05pScAusb8zIRz6b3DXUqrUeWg9yxyX8ZQuB6DhS0FnFh/IEWAM2EsmY59p7sVLdMwHIMhHWbTRDj",
	"QhHj0uFUoNOUWoRaNp/RZZhT83IeDDUZnAAgFxRlqKnFgqKX4IF+lw0yde1FFf7DH/og/ztf37dD7m+L",
	"zIsMPQoZ0P9E4gt53n6NEhR2ccFhQSlrekbWTmBRzmeHJRkAeCIDJZMp5nWtqOjaAU69ZKuYGBC+tD+T",
	"6P6Ia/u2571toTt/FLs9P1L3EIoLhepGfRY6HALPcFOnhZhQWkk4ESR3bkMiwaPRkXQdeBjSEj2X58K0",
	"BF3tKJVO6YjYBpi3+IVVl36QoQNhgoskFCcc8ZcwaxTd497BwUm0cO9BB0EeHMxHcpUkKqKAIUJIfqSZ",
	"LfTXEcuKN94ALvOJAN1EGBHXAa7FXfGfSVW2WEZmy5CdSGR3LGcAjEdxYTljI6QZcsdJhvv4CO0/z70Z",
	"E9r96/nYMKsoipI/kTPlYUnOZ4tQLufUslweKqCgDoECdT3FCE5M6scddEXYwd85MyadYm+iOb/Pgqzk",
	"5Ey+mymeZhR2n4cGw3OcS0LjaGi/j1cxqPuFtL8OaX8OIiRrWStoQGKu/++idX0hwPM+ImzlEjfra/Fo",
	"MCcuNG+/bMhfNuQATxhK+AZkPdGmLIK6D5EbK+GCX0lPX0lPX0lPX0lPX0lP/4akJ+4bIi8Ip05zRUWh",
	"0j5WFPQWvfcm4k+2sV4rW0+PLYvyHv2ycdUyaldwUnh4vigMtdfn4pNysWgbtfn9wjBaZv9O7dl3rZzh",
	"dF5rpFs7e2/1GkqbyYta5rlaLz7M64WnrvZ++9B7f+5kxk/dUeam2x43Xy/cp2593uwoi+Zr22gtRrnn",
	"h+dJazFCjx0qgzJj8DCjG3xTs2PvxmxPn3tnhvpQs9Vq4VXNKpTXG/Cqgm5fL7K33YtMa9HMtxYXpG4a",
	"Y71aLza7T4Vm9z7fWtznmp0ZAo+tBT0XuGor2lWzeDMvO/pDw9DMgqFf9hc3Zn/xlB0bmtkiaq4/uTFb",
	"U5WeBZ/ZT7l2RjN7dD+WftWeaQtrepPTc/q8gDWzln16bI81xPY1fXp8HuuXtfnNYmy2zF6h9VrPtS6b",
	"86eHhtl6vcg9dZuF23PdaC3axu1DL9fq6uz5q+X6iO3PLFsqKkzUbL8i4OA9ZcsulQOVp/eOVZlNvOvh",
	"mW0XrAyxzcr8bTGedNonxbH6WsvcVq9hHt10imfVu/K88/wE+/LkrKorbk7Ti/139bZQ69837tpuaaK8",
	"lUqOls00Kt15vzTpaC3syJnXmllpeI+3xRFQspnrbvseXxZL56XFc6t8MzObnfY4d3VXc2/f8jdVzby/",
	"6GSBDhtzYl2WyyXTdL3uzM4PK84MsJDmoQPJ+HepIV3t6kxpXyi552y7r100+q2slW3n2rg7KczbF5lJ",
	"0yzbz1dWpvXQWjRRxtEu7DZQ3rvtXuOs033u6sZ9oWO0i/Bcf2wqk3mvV77QJ4Vz9arW1C/Ht60rPde5",
	"GIPeef+in6ldAFNZqiG9snOvFCbapP/QzjRQf1Er3Nb06/breNbLnTWB2Xp7em3kWw8Xi6fe+P72wsg/",
	"Lp7PHnOtRS+bUW4v+osno91Uz2td7bX91FHouPy8n7Ux6D9l25d2v3OpN56UjPWAG4XePOO1qmE1pLFo",
	"Z57yQKnPnybtYX9RyT/3G3XttfHYzrbvmpfj975ZeOz13Bq4aHf7D+WM/viUa18UnLAaoj8UbJAtz1WU",
	"eVUvy5nnamGqmdpUw/cOwLrCVJTb+knpsaQp43lHc17OT46KlyP3Jt/RGk7JyFvv1klvCiby9aPVct3e",
	"+f27+YzrE61xXrq3wQts3M6KndeHq1y1U341Js/t6iinn/QyJ66sKmQqZzIPnvlg9KYn7Ro5yasXYOKU",
	"ezArd/r6yDsHlZurC708qk5v7t76xTPz/ibXcazaw6jvnTQhUnoKshxYvJDhtfyiuifmZU9RWo+X3eno",
	"rjl5unyezJzHEtQapTl4vZEzriy3MvNRt32Zg+e9PJ60LhoXtXzGfTsrj6tPhLxUemYV14nSrgG778kn",
	"4+vRa7G70G9xsTK7e3U8MJ9Njfr74rVmN+sPQB1Zvcrd4g28dG4d41IGJ51ypunlxov2iVowanfZbumy",
	"nbfa1pj0Wk772S3XR89epXGp9ZsneVNx87nnaaNzfd4uKNA8kRcNp1DIv+kGeCy9edmx++4+9c6Mc/lu",
	"8T7Lk5lnzuRcrtBsLAB5vLusXjjd82EeLjqPZ1W1Tgr1q7ymtl/uFu7Zmzrpd5+zT3fe/ES7bdev79Gi",
	"ZBjN5+oMOSQL9JOrq6ln3NRGTaPQ6RWNaXExRvL9U1dV9O5UK51r11fjS+N1fn7vVp/m7xc1+dLr5fqP",
	"6PyqhC+vGoaZ7Rfar6Btdu37yWsFv2TPyj2jdFaazTqZ9u1tVe/2bU3TOyBTU/JoUS/Ap+5tpp4n7y5Q",
	"Z2VHvlCypXlR79+6ZufO1obgtVS6OCu/POl3OVh6cEZ6b6G8NO4uLH3+0GubuFDHVvWyaN0+TT1r2Eed",
	"x0b+8dZ9bV6cTMcjnJ/fD28NqHax2jf6xcVTsW+o2bM7fNJ/7Herlemi7prDqfFUy2mjvOxNMpmJfNPt",
	"dO4VUzeMYnGEZ52rt9fWfd2c4MnM7le7punZ0Hi9VNT7h56baWRJ/rY1xTf4rlZyDIyd24ez6nSGm7mc",
	"fpsdz8szV4G6fS3XmznjsnOHcugxk7/o5i27htGzevOsdpFdnd09L6YdeDk2mvDxsbsYFd681n3Ls2du",
	"Xa+NnswG0HBOycC21T667dhvlZO67k0qJ/LVjdvMV9u9+5R4TPr5yWcQONDZM714h6AVFpzqsbfn0DNY",
	"5IYDXc/BLHonki7CY1l4BKyfY8YDhSybe2KMuYSwZng6y9NkqWm+7UEEwqAhj41l1ejY4iL8UwTGeBhN",
	"LAfLmmF5+otmOfDFBAi/2JPRi2VDDGz0olmmaeEX+mC23WgUUfSo3VB06RgQSYUQS/5n7KgzZBiSCqWh",
	"ZwyRYdC/kjnWxo6FLY8Y86MBfrI8FiplW0E0ql9TEOuSaWHkWo6EXCKFbSTsR267kbiRa4BdSwIzgFzm",
	"hjMgA6k15E4UP1ltXyCovz9qOJ1yHaBBXtmlcKJqmbxeVvV8MTNU1AI4yepqKadk8mW1eAL2SIHcHQjw",
	"dwYi77FPzcJDA2kfvCp/lqSQtyWCzpA75qWVgAlZzLsEDAcCfS7Bd0Rc8ve+O3EK/7zc6ygBbLlj6KQl",
	"j3iM47BoRBMCzDzFc2kMpjB66n3vaWg5KtL1Qy15/kUF0yTcFKtDqzmQcUhgEEm3GNoFBwjQzXbQFBlw",
	"BMmfQG2Uq/OoTEmdR0VIWtwWDz3VAIszZEkRMDqQcksqLwQ8KEeNQITLDxEOULmrB0TMgEopGP+1hOQA",
	"LwvlLWEpWdyDHRTo9n3r++ILwi50MDB+fyzx3xg7/u7hyXucEVtuzfLwB+OXseW+DOk0CTccEklQXzL1",
	"QDoxFv53vvEeBqoBKYoOEdZD1Zj3hTePZL5zLJchjy8ZDvSzRAr9+Mncp/9jfqXTY1bv+CgoRvEtnVKZ",
	"5v1iQnds6eQliHhm30CgQ4eO8s8WLhMkIqWPwgVLKd9amURUZGZOtiEyIMUHVvX028+4rgRg7hca7lqS",
	"HxS+WuxZQFSajSGWxojVdBxgQLksXzGIID+SgsQ8/uQQ/IzSLHMh8jlWnyEDzPkAIhLEzAUImUSwuPjX",
	"AF7ubWzN6JShLe6NfN7fIGHh78zWD86BoJL6X1z24qDAip9TcCcch2EA4lY0+pEfipGRM9luRjnNl08z",
	"uec9y/MkR+AEZSGWtW4OY+d6iOX61oYwy4Xvduo0k8tksqVM+URJpxBw/T8o/A+EbJmDeGrqNKUqWVWB",
	"5axcBPmhnC9ninJZAyeyni3qxUIxmx2WyvvX+NlW4xmolucuddugrkaYuAJA/plBS/96kvq2D9JsiVVh",
	"Q45CdOrXgYqrdBxfnYg/r3gelw0dExHCE0kYmG3ouKKhyciwVGDsUBvpIqjZtJJQtMO34fp3a/lIe35/",
	"Q3XmUGbFDp+LMmv8yx9pv+eMpfq14ELHiy8mHQfhEFj5M3ap4dMF1kHNSSXexCk+ZEPSq01xoqWwtkNr",
	"OdjvYcOLpP0vJeYPTfdtMzjI3ijHmvK40CR74FRqeSnAccBcbCI4SGwVypXVQwbYdApiz9ypjFkMrKMQ",
	"3P34S6DuA4LlGRNgsEJpm9t+MaMZ52q8WoYJTRU6kjVcR0cYvuJ9iB/p8Vgc04BsDbgfoNowHiM9CXHX",
	"WMWGC4ywoS2w2/k+V1hdzJXe+ZXwkruj/dZ7jLZoW2/QtXIR6dAOEi4lfJUb7sNHjk+6irtlsc+1Wwg3",
	"K9yrfSLX6qjG43HPSQQ86dS7PLJk8UdfD0U6OapEeywGw2Rk2pbjhsqUhr6idw3cceo0NULu2FNZveLI",
	"my/QdY/tyeiYfvJjpSoh0OO55/Jg1jA4b4yCENYrP+kpKu65Q+VFyBYE9Ka/VkjT261+XoeOXkXOYOti",
	"tljsjE6RLP1jUCIGWpFyhVsytcSES8zwVZskwgy2UD/nPlhrxvgWJZFId7Q1tsuTADfOSYfsNesKsNkS",
	"ac4QwlDYDHRe/PXvhqD+ar8DHz13XDUAMmNUj6pHXMvkjgLiF3cYWw4iwjXjFwuXXEvqterr2KlpfMHV",
	"mc8htlyRqElHCPWG5Vc50HYggdgNDPuISNjCMnEB1oGj8w2F1S4ebJ8K8nF4oTMnVt2ynFFdJ/HIWT8n",
	"SzlNhJy2htJsjLSx/4RmmwxJiaj34dUjrp/lyEDGvh1gZmkEDpSYywK7xjxiY9SPBjgsahLULrJR2YlK",
	"nRVk8O8igMA3cftNZqZeX7TjW5xX7bXCrh3Re3mrFsI6Kb3YFnMzRP+oAoI0umuDvIhf6LzxKvGGDoJr",
	"+wwyK46DToLLABRfVQh3FFzFUedlCgwPxkzdDpwpwjBCUY+QZcU3iX/Jqp97hgFUA/rNP9cOFWpnE4d7",
	"woDN5esQ8YLTa5OI/Ov1Ka643Vr8zjCQV121Hcu03Z126EcQv4wTHqa2A6eIhblwN5jOJAM3J+0wP9tQ",
	"4uR8u/RXnobObFfcGb/D3CZ4fwGjGFbTBO8SGEE/boatstOMorfm97jy2ey3nWbh4E+YZo+7iTaWiJes",
	"I0S4Z8PvLRFujxszY6Tr51blgQ1m5Ut+BL1Bv8fY9pfExwbtdDphKlsTQJwm2K8SWlo4d5rTQy9UOhpx",
	"hH0D8MhjWGEHitWWCVfYaRR6Yepeuas4octd7xs4Lhe5YQ4LPD3w8on/93ue6MJknU4NgYmM+YuwuozQ",
	"FGL/Hwi4PCUuRemQgsU3pqZTNvJLoBNPjWXImqXD6hgYBsQjuF1g0OGS5o+PExidbKFIVzYAwrErslYr",
	"3VjlYbkOGxRYv5agimnMIu4nFDyzFrueTnkOPkXQHZ6yxgjklGX8nbJV2OPplA2U4bs2BngEEzbuW4q/",
	"b65IS7WNow0yP9Klfous95fVt81z6HPykp/qp78klwWgEw/CXLwOBPovUc3DNpuPPyDZCQ7W1ZdfJwFn",
	"HSRBsectOdAMAfwHYUy5570+56aUGKQOsmPFiGURXUBEwVvmz0eEn2dX64vvWYkhjKD69O4nWLmadWik",
	"A7AmXlPSQzOMxNxazEObmKFY/1u/Nj8Bebdzxd2N2aFa8eu3viz6vL5iuNrzkdSBMNoRq/Fw3ZF0S/NM",
	"iF0RoxDfBSuBc0fmT8WAYu0P0RLVGycMladmTRPY65n+g7tDWfwkluA7jy+Uco4u2cBx55L/eiYD7NeH",
	"gkdSNa4n2E6Hj6Ipr1b+fbebC11O3Kt1DTxxbY7XVTr2fPAjskN63Yr1mneHjlOgKaf4i0hsRFhz3kXH",
	"Z+Gg8dPCd9tAGnKXUaO+wnKoWkxn5ToxH8pqahooITB2GT211abG14uj3nBd07X9XIoC+DzKyoSEgBHk",
	"tcOAi1RDxJXzOWKuJH7WiuRCh0AxqzgpfLcB1lnTX+59uup278QQqukdSWyPhMkUFRAe7EkHBmaCbLTH",
	"XVpSPS6C+NxQ57ule3QQdIEzF/kYbAFuB6vc1YnEosqpBKMLWAT68/J7WK4X1k3XsybC0WLCMJJKr0V+",
	"eTgIAHxZfXr4c/I3WXo1FtiFVE8DDn0ZeBhMAeJIt/wwWNX/A9N4V1YN9T6MU3tjQtNWL7QPHZWCSSCI",
	"xH9V/UhtNsN2HE0OcU7GW79mRz3eNyF6IAb0+TFVmc92t6zr+bN15pja54mnjFQg+aNV6eipD1ZLYqbZ",
	"DXjrIFtWsdnBvifcHMzqm2Aq9PvSb5iN21YTZvHr38R9zzPt2IA0lUdIY5kxszF0WPy1DR1emtALBe7O",
	"qYoAXDSlQza8Sve5OG5QWvXy8p2nlyDdfnXxtoJuyMEQJBaGr9BnzLwkUCqdMpHmWMQausyCQukw3o0Q",
	"07p/H6r7w3T/n0JtG18DsQWTdnwaxHWDWH8jxJU7X7fTxkS0xzgRIiYnmBjb1Q0rIkvnBHsFI4xcBFxI",
	"VvwtUVnkoHiGAZBJXoJ+nuF0gdU9PIwhU1yEW0+0o1nmjSCsoynSWapciMhVyzIgwKHVNqwRqoO1YtPc",
	"9QqDTgert8a6PQe2xbgki+TNxNsll3vcGcHi7KGxRjlfZ9obWuzTZdMqHhAf1uR3fCP7VtSY3QXuHoJG",
	"GOHRCzBGwhW24275d1Kojv/yAHTnvndod8oVU1b8GWP3vUmucXKtsyHSfxAhPPP2v7Hi6nU2IckOlSh5",
	"wnfbIpD4nZz8s7NWUOyW2A0tk4R3IVtBdPvRrfgooFwbEMLS0CUgNR66Eue28ZTrL+g56FMWnSIgAanX",
	"rictJ14qJn057UsC/tcS+3pnFPI/a1p6LNpHnk+Hb4oXzGaoscZCfapNfofvdZIkAl5PDdvlBEv5s2cA",
	"LX9fxuyDc5EDpR4J8sN8t4qfvxUKOWCMO6AysgttRTfFYg32ExZkS/zDR3lzKPYiwWyN8NDaBlaqxwcQ",
	"9SE5gm7YXSoSQgCOZID8RYK+1pthmaScJyg9a/gQd5gQ743B4xgVYwPdbuAzu6JBkqjeVUjuoJZsVNI2",
	"i4LtfDtW115Ji9kWy/1Bq0d4tV9g81jtTLP1eL/W1uF8xLIRtpMc/NJanWQbgNbB4veyidWNmJGcjwhK",
	"0qzMFqDS2CJuUqYJf3fzSEPeBSdGBcEsKJZn6fvxUTx4UBMfUlXT58d8SskEGIzYCzu0rQFmrhOmE1LZ",
	"s4zG8zDlnrFq4nr/nt0v0Jfd4T4/8aGHPhiXbgKLMug0j05n1SuYn8eFjum7ejwiQOe/dY8GuD6UhsDg",
	"HyIRq0ZYTrOkesigkiFYI83KKzkeXwWzUVG0GOAgyNPCMCnHglsF/JigLV1RQoNXMXsNcttQu5sQXsos",
	"ywJHYsV3LNJKUkWXxpa28skA+8VigMuT5YS/QDM8gqbQmEtA14U6HLh7uKOXx4iSMbIlqYJ1yfSIO6Co",
	"JgHpLypTZITpd38Jl9WRJJ1zqlrb9soWTDDn0WwDTNd1xxA5UedVmq3m98vWAGFmME4y69YwkmazD7AJ",
	"bMKTRgV9c6zYaD4D+tjSUmmfZ3zbQkXJ9rJ1nv2nWco+m3uTnVOKdrePrfV1W1dARdJEfEhRNGXnUJ1B",
	"JMz8AnUh3ENrw3H+ZH+In+RyKMqFv08GUUxCbyjebWu4Bh23urnghw27SoymidzcH8YpPunGyC4pbjuz",
	"hki3uViuEJX1SYJX1FExLGvi2RG9Js0vayBSwQeptMTFYaCd+A31/S8GmAWEXzK97rjpO2iCiSL6ij/d",
	"iihhCpQe7/rhKekrWeZxIoz1FEtiIgRhqnayMTHOwWVPtjj1D5gsrcQSxS5DyV8zMCcUKB4Ja18Iu3DE",
	"q3sG/d3i5hU/8jwFX+cJthg32QYHfkWaChc+VXIADrKlZnTPwcySgUzkkk35C63E1HRWc5AX/BxbnqFL",
	"KvSTGoSVCOt+wYKY+Xkbun0g7Fuh6JfxMElOZmM5bKFssdgtLdvfxU1hgndkembS9uJ3tGyit/dJRZoS",
	"sxQxqgKeaxENGJG3T2gt3qPvEIiuvKeCOeMT+QIwiSXFXaZDlBM6eBSToni7JIk4rhnQ8LbsYN5AcGfG",
	"ueQNMWyT/ZgoxDZzjr8b+m25vkSYs+P/DKBzuCZBnSTx6/Ulo3D3G2rueO2xocNijkSYkESc+MTdLQG/",
	"x/bWs4W3YS6Lo3PBBOGRhFjpYpErqc8xMJG2kt37q8TjB8nn17HaeLqK5X67Xdgn01oMRmzwrjHv24bU",
	"nXXnnq+OvXnQmTP2D0YmxG6sJhZxje2yDLPsR1JWeV6Qn/oTdE/hpnwp8o/Qj6Ioedzo8F+xhePjJB3L",
	"gEkcif72G63TSU+QWGyzYvPqlsjFBuyOWz5Ukrycm+546cb07zaoj+nny/l1MuNuJLYTaMzJMJytdv/7",
	"A80E0dPyt2e49Nge3/Jvtr1cg8nj0GgltSb+XbXSf/VjNqfOSjLPTzc9xfQX3X7IL8T6VMRKLrUSRa1I",
	"YsCvNnXFAmGXTbORcYUNQl2d49Lt8Ugy0BTq0aKr4YgWPyJDD9VNX6kiGZcKIBqzxjrymDNLnEBITSLp",
	"HuQBIDZyYIS6deBC2UVxvsPVvAC+6nbIJj/DEho9J9eO+BsZE+PI7wCb4mov3E3xMWudcHeNI4rpuBwj",
	"9lcjATdpAGuBiGFt4KJTyGTjRf8y6XPTQdmojbnaWAKOilyHJwvR4TslbQcFQb/HFrv1QZuWWH8EblrV",
	"udUzqFAmgaTU34RUtwoWXsJhqAECcwSvppHxSJ/YkyRVMREikBUwEQsg4qf7piVWkmCX6TeEePLfpF77",
	"ZsdycWKyOHR347njMliNsygHEs9wk1jsS8IswWZ1vw9SLRwxFpQR8MsYUEhpwHH82AaeED3AjYfusty5",
	"gF3w7X/atapUKpZzEoEa41bZo+xRRuSDkgEeRHY5SFFcckP9mCSIp9BY9sYISrsQqHlO0Ifpv8msXnSh",
	"jE29QCakr3MCNQvrJBQux/ooGYC4dNn4l/uyoWVcXkX9vBqpPhOPQ370VnwZqgoO1dsJ6CEoQAXCDZdi",
	"oXI0YHmpvMPPhsv9/0sWf8WzUTxxcFm8ggxwwjX+N8EmEWm5GFsb0wZvHj0KG7kBSpvAw2oKrSAxFdeu",
	"xUKA/Spdfgn+wPrBExCPpK6fV0SxkLcjG6SWVBAcOZkcEJGWX3LGx5qziB1RykAktBMR6hAtQ8NbLtB7",
	"1K0ZJq4DgRkENG/nISEIpaMUH8H/RPayc/2qgNkkVarydARjaxJ1RWEjDRjcgSJw1gXOCLqBpBbZXaFk",
	"NOxCRpYs0ogVKQtFMa+gunQrerZtxPR4VOaI/JESWaIUUP38SAooLuhWNYip+UI5HdalQZRaBqkw3e2z",
	"KZKQjVeNZOL98s3Fmtmi+M/zonfeWLSozk478CsROYngYVYyf9RO84byjXerACTdYob48cdKrwM7TdnS",
	"el0gOtZypMG+1YAGqRDuJzHuTUW8BKj8QSyt4qdd2xYZUomKjoDkN2HsjusK9nKAYPYTOXdnU5ylxUtk",
	"4SQkvvhCpm3AoOyF7BfUCN7AfoMxtoteu87FkS/XP8D1lo2A1m+BriOyA3VWKJLEMXbLCbXwW2HyAxzl",
	"8tJ+TF6celU6f+C4SaXjlu8tG2hQ1iELI4B6mkUuygRigljusXiPiSgBZrKZ862GjsXiZaOq225ibIA/",
	"fkL+3Nmkn0XB7nuPhCLD7ziIt/TjglkZFwtLKhwDYzjALPBCtPbw654gIqmQPoVNEGH6P01kR866EzXH",
	"oXOIsFcgg4TGN4iuNEhJQR7Erzjme8RaGquhBHgViTtihUPfXUp8HCfXFOpK9UZyrSOpRyiPCdh83BF2",
	"3KqI4dq8Sz9yLrRBvxOv0KKjZEO3x4RQMk/dv4pibFGRpf68T2/fsEzkbRXj7To3fjeFaKlK0YMssH5y",
	"JhDYOiMPnC2WoJiJ/yK8iyxvAeznQ+xkI9qntS97KCWVZ+TPKJ/hOAAT1tiQh8OHzGWiQ106pVr6nEV2",
	"wIhdNVRh87CtJdnbROFzddM+wxnGwhQS0yZuV0vkobD92DXBrypKn15FaaXm0Wr5pHDnzFA3ZI5TL/RX",
	"YBjWbK3Ukgl1BPy3v5+Ex8Xyi2tZLwbVw9g3tmOxfrGqAV/8LlrpUEPfX1szKdz+7/tak0305kGJDYg3",
	"fwX2h8+sxLQHgUw8FToYupDcABUafWB4sQojQwLpOhgtGXQ4j3UNV7VhETjDsJJMuW8keZtqyTp8X5qQ",
	"dOACivlH3O/rQoeu+f/+T5HLFfkZyItv//m/p8t/yS9H374r6WLmR2jEf//v/0l9jG0mtd5MKlMCYhpr",
	"hsr37FXFJGh0+mk8NElG/9jUMvWncHB/2eSnVzciWfxxe8jxuOT8TzoJmzo2oC84TzrhMmOTrROB/0E6",
	"3jHAgLcxuR2ytoI/N//2+wrGb8uRXmszFXnHhEzeKjQs9ia1tvPNlUXXgfxttVWff4JlN3N1HpveEOzH",
	"gUAn+zau3d4n52dc1c5hKKuXtyFDLdxW6jOubLnUobfl7+ZTLsr/+irSUTMOCLzJpqgWypzF4UeMr095",
	"eIKtGQ56dM5ZDP3IAfqy7fBHXwBrgQ3rnRrW4MY8kobBwk6iEGP8d+YgN65Dz0aNKtKEKPSTSJe2xPuY",
	"9Wdh8afcRMHcKkylNS0H+q/mWM7v9138JPqI1YaohgdGnymcXRBf/Zqd5tthd30X02E1gVSDcbvjqg3Z",
	"G2alk2v4nzxRBK78/Kno/NPZIwUH0trrYUHf17DegMsmvIne+AgPnLHAEgOKVMldwq5W+/h+usiOMLUf",
	"8W16P33RGEyNkQGrQ1ZgcahsoCzuYwJhqREm21VYxIRo0xuU3Y+y2rDKGDGifKaVKgGhf6YWuIFqRM7w",
	"2Ty5Jrg0G1tBbvGqHXDdHxrphb07GYoFdifDpBAsj7/vQ837YvdpWjqzsmw9uUil3n5yf8YtJwfRc4cy",
	"tQ+I+mQBXhGQ70CEvF+bT4mIRGwDgjhYHzf4joibZrqGbuG/XJ9cBhjgeVRqsffgUtnyCLeIqRDDIXJ5",
	"OQ0QFOFHC6gPcLAFfvBIGd+DHlwuGMVaAMFIMoFts30GcYrCBmL5PcwkqTuGBEpjMIUStrgdDhis8AjC",
	"owH248MCmuSNOxwo4kgEF/EIpEwtyNNl5UN0nf4Pcd1qgENOhyU6pNnnosc8/UkDLhyxyugScnftb13x",
	"CYCeOvF1Po23KVEkjaRKu2C0/XUgahvxOb99+Aq3xaNSxe9nmLgp9iQ1UNETY1Q/lo7RI7+kRDrdaVLq",
	"BTsFlbqhypl/WO4FPcJ+GRfsi0/IswhWTgLsp6dUhLpi7HJAuDHOOtT2QwPYwkEEXVryiMdfgXi9I8iW",
	"LhpiNX+n6c15H8udbmj0ATg0EZFQpOE80Fw0hZHHEPGIzbhx/BNnefHrVxZwaL6ajwnr12YA4lb40vHB",
	"iIC4vrRnU4l68lCXiEX/qolaV8v+rq408oADsAuZz3mAVcgkDX2c0GvQNM+hkNChOKpkYX9agDX2JCeu",
	"A5BIRdhRmYi9jsQUEXYWrqkdc8XlVzKNQ3NDluxhFVOT0kD8gp0xMAjnCiHsOhadhNkg41FFRY471hPR",
	"m6kIf0lslMQAyi/O5XlJlsOu2rWkeue2VFQyXE2R5hA4EpUTrDQaT7RWFEVh9ezGcC5pY8sikOGVa0kO",
	"nEJgSEETXgcy2raMPfTtAzoHxc+x7NuYWG7ZDUositmkMSCSCiH2gyj1+IrL4Q6Qm7ZKPCdRNxpR7uFs",
	"/JwPif962XVy0wxDy4GJOxi7rk1Oj6O0cWQ5I1Y0d7FLZV3R0/pH0O1y02batWqhmC9Kht8WNF7tS6dM",
	"pOsG3H46Po5Jkv+Q/260EiZDyDOMZAUWI22ydQp/UHzZRtH1c91B3L7xI17EPGJoQvVHOISOA/UXOjh+",
	"S34iAWefjDL9LAKB3wmVN/287V32yIdKNhglOOQ8NaGIQ7QoshDfsXOIx+oLiNclcNyG6COXycPQS3dt",
	"4hlUSazMWT+oGBo7zcLCMJ5vh7CiXmlVQv0WkQkX8aU91/WajcJiW6IDF590pHR32+luasm9La2KB8Fs",
	"S0VNEu8b0xqD2lK7Pa9IUn8RlkzJQxk7zGXMHY5s45VIac9Yb76zTD1FDiSh+umR+KiYViGGNVv35ldF",
	"nkDkjz3HSJ0GzNZ/OB3hCTmCHr0ReQaJmz/CrGgJe2vx/R9Ps8eRmQK/cur0u5/38qHZ+d2Hb5D9lPpB",
	"/5SM4XU/ZrZyV/drvRGqwjPjJ1MnERCJL84QaDCwWDDXDjAMyRoOkYaAMcAA6+H+iTzWmnuebMd6R8xm",
	"UiEScsnSAkLnEhYl0zNcJLsQA9Y43vL0AdahbVhz5lZKS8ilijBhrRuwBEYjB474tRtgLiJyeHjUchvc",
	"iiv2kh5gHREbuNqYaklGuAViKGpRmHjZpyrQJhDrVI2KUeGoJkR4gKcKCCJ+JQ8RBCboTbPoR4YENMci",
	"xPfQUWjULGcZwGt7DmuZkR7gMKFyCEbSC3igmYj35kYhUVmIQEIQV/RFPHtacsceGWBf0WMhaizkmT4A",
	"PFOY1CWGnBZ2maJHUQyoVDoYwGWNrTT6HSuPq1JxP4F4gFl1OeI5fo6iY4kUQET1L6wbFASuZYqwIraM",
	"2KcI/+K2wiA+lgwwXUZHlCOpnjgcBNo4CN1HmLjs+ULmWBs7Fmbt9RkzQy6VfKkwTqfSqSl0CEf4zFEm",
	"d6T4nYyAjVKnqdyRcpQTVhLGBY6PZtAwZOYzO+bhRLK2ueVR3U+EIBFsW8YR0d2N4nKh2sw16/p9CZaB",
	"R1Qo+474Oc/UNqLI6cduchAOcKj7QiSp2/JZY11nMZPuAzSMa3q625h2TstCQQwYWUVJYujBuOOYtlBt",
	"8SNjSO/ymIf0iQjndxlbso/0sjgQAx8fQb+Ju4UgukhOjkJavYr12OJPv5iVFaZCGm6D+3qM2iGw/3ho",
	"3MevCtjoeJo5BpoRF6PrMl5dqd5QDcrSEHONBEH7rKGGqDEf6mzid9OjPFWT2meVqsRku2m5MCpYXMvn",
	"rgPce9xwn67nULYZZchLNSqS3B97fxUb9TMVzTjonoBmLAGdTuWVzKfebbgnanidwifjEFMDMDB4LCKL",
	"eY7gj48qzCcZr7r979uPbwmIFtWQ1hCMz2dv6IVnUFVO9DGgWMqSo+bEhaYfRhTXJI8bSILsIYFeA4xI",
	"KCTWgSNEXBgkFsbVd2fev0CJ8ogElilly5gqirVApL9y19kMShhGEX+lln1AL+FyvLGIfoOoJiMOvV6y",
	"Phmzb1egewiW82Vvoz0Lfwfe55Xcp64ThKX/gcQVIaEtZfLjCChaMV+SVnsOmGDOC0izThADHEXdtMiv",
	"5J5NAg2ouaL1wjr9mAAzH0J6gC3Hb6YgNOkVgqCTpv0vlzQZbefAFXMxD6IHc7UxnWwEqBq51s8iUEbX",
	"tjbAyORtKqhyzE4B9WXridg9Ag5NVqDDWdIxa2bhLLe++tJa4UNku0yLb27AeUtgRUJ0YFAE50iS6kMJ",
	"4AGOWk1ZcQixMRHYz9KZeKyfOJFwUTCYE489/xiTsx00RQYccV/0GGoTCbFyO6yITcwumHd8rSNDAn+K",
	"oC5V2EU2I0kMgFkOYWaHC3rSO/9vLMzhAGU3vI1/LGvLK/lPXQRbbs3y8J+hmxDPNIEzD1IfVxCPh5H+",
	"LxVFyG8/0inbio1D4EQTFEdjgZoYztbaP0Xx/s4i8YgvzBVnlj5Php8/BEFyzN1vt5EWJjwN7McaBWT3",
	"o4AoznzufapAF/v80iD+phrE8fdIasb5jyCsNrbVBf37ap+JtLAhMqMgUxLSvDwbSQe9OLiRCOGhA4jr",
	"eIFrJUowfP51kllrtBeH8ivm5EgGi18hgD4/p1A/+uL2/yRuv4Lq6S+V+A9WiS+hu8pgdtQot3EJ5SOC",
	"8Utk/UqtjSJBpDPRRp1tr2dEVNxF3xK2F4OQPR7ztBUn77zdcHJP1Y970HdT/ZQtcpB4zHY69FiGuIhx",
	"554pXmrznygYy5+6iF9J4Q8jKIHEO9LUzsri4R6DtG/OFR7buI61f4I3YQO1fzkafrGj4fNEwe4EwB86",
	"B9hhxRPpSJIu2X9IKgqyRyger5YaZ6561mGEux/o/KJ6TJBy4lMJzx0WIREs3XGIgkLK9AveqWSAxdKA",
	"V8/DIWeJgfBEkJ54wnFjpF+oNlh1DCWgIoNXLxtgfwsrud8B8ZA0lUJjuqtILtH603BHgykH4zK7zz+r",
	"T74fViQ5jA6iZL63LwvLP11dZUbGkY8nvlQViPPJKup+BsqgTP4ulslEvD/IWsm+T9ZVMzuSzxf1/O0N",
	"Q186NuMCvI0WJ7k4NrCvUnH8nf0/0jfaZAXpM5OQqIbA3XI8k5fK1gQmsJu1lW//ku8ktcuTk42NvjWD",
	"egtf5PWP9LIJx0Ai6qe/tONfoR1XfOe+iNBlQPRbV1iGaMJ5oAa8mQXsLcm/mMA/jQlcQncTB/gkHTi9",
	"9VMhNXcw7Qb0EiaUUMrS3gbedUo5yNq7RXXeTeZusO9+adFfWvTf3FL9CVr0YcHGcSUmf27IMdMclolb",
	"SQHHCeHGIfcsDMfjhxkTMGLiiIWSNLc8xvhYkey55TmSNcPRJBh4NKITTniq+4aY5RUf2V9kv/DlZL76",
	"GZHN1r8kpvkrFCQcCvKzLW/i0b8D5h9mhYvD/D11iijif8gitzrVP5aE/sWi+NDAwVV5e/zd/8+Dogp3",
	"I6HdbFgrRHQX7Gsne1Z9TWJ/2ba+Ygq/VMf9VcdfZgJYyilG5gdHee0oxz33YxzoJwn0LeFgcVe7tH58",
	"cbOvJ/yv0Rt8E/rGUgC+xTzEcYNQYkm6863wrDprNORMRCb7GQmilAnFdn9S2W9QYBlQjqv6cTTA9YgF",
	"PmKdX6nhOoZS1TJtz+UNU0KtekIlTCxN8xzC9oewBPydbHxfszSLwN/wafEtPuwOelT72/mKPvnN0Sf2",
	"8hZ9k1lwsd9+2TuYiLATn1qDqtfhYMq/yEF5cxuw9qD4FDHDhxLpbH+OrxiVr+f2J8WPCJyKJ+T9pSp7",
	"hrNGPru8wolfooKRb1zwdvjRoAelNZkAHeBoJR3RRdWP5QaSBogGeB3boNoba2qDDEO8o6mQ47XSAXPK",
	"a4ZHX0FC7gvvv/gjOdQe4AP0zodM6hDi36cLnKZB210lrS9G8WWR+EC0zUZGkf5SpZMTDEl02MEq8wb+",
	"oXwpD1884RcH32xhCL/M+hYoHDvb3TYS5A7mtXiCPCj2ZuuzIMaqdueH88XE33yF3HzZ6/6MkJuf+PA4",
	"BoZhaUk1y5oRL0po6JEkVZb/YpV6JWKwVE9rKL15lguIKCwiuZYLDAnDKXQGGL5rULTvEqNEJSymniz/",
	"Tp8loYSxI0mqYx1Nke4BY5lWSp8nA6wJT39oQ7MxxBLwg4mZ7hKN1KXzO1CDaMo9LryiljsG7gD7X/Fm",
	"3NLQM4bIMKCe5sHGDjQgINAPSQ46dc38kutrKw1wqK3hb2f2m61EOATHjxmAApYfwpRDuP9yPx+KkAhP",
	"86XXfRmFfpMvJYn5Hn9f/mOLQSjQzDbT6oEWlxC1VkI72qm20/KDr0iMf30kxpfy8PnKwwa7yWZmcIjt",
	"ZGdOoBwufb94wVd47+erudu/CgvbfYwhW9Rj73Op7CdoysqXpvxlKfnSxuO0cdY7DmINkuPvwX9v1MTr",
	"OjRty4VrTZxYOVOERxJ850eVlpP77beD9uWs0/an6O7tYJHgv9aldT6ueI8YHVXbv4qy/gvV9pA/MsDZ",
	"SDg1XqqtR5LUDlRYjtaY9wgLQqepHrycZ6nwMs0dEb/rLgs0QHiMVBQKTgrqZnjYRYYE8Jwq2HwyXjXY",
	"n25Vr/bp4Ldb3LZ/FWx2Bz0kkeEAXU9iN5G29nHM5hCtZSdOk9mZ0wBd/3LIfKkZf1KdQ5Wp5XvqHdxs",
	"Eeun5Jki0byVgBGyboQiP4VAXvgkSEjh34gyKXCAg7aCQe4AwDqfggeKmZYXnX8tQVjSAGbBXsQz4ZEk",
	"3XNzix9TMgTIkTwCRpCKg0hrSX9xEYXCzSAsPIWZSvguAv4DDAm+sxbqrHxKsJDmOQ7ELuUMtm3MRS3S",
	"AY5WzyYSkGZjy4DBWthiLRSJpzJ7D9TpYfEoCMLdbEMRRqVPC+DmhznIXsK38hW8/ZuDt9/8G/Qdr+JK",
	"f0F1687eGLmDHA9h5J62BR8hP2BXiMPpL2H/5X37Be99VjhsxzojvFgZS8nkToS1UtTQMRHrBMwok8de",
	"hgrdLmuQuWNoSlME/EJGW6vnhtYWDgQmOLlk/7hAajMwHEK7bGNf4ug3iyNH3J8vjfh9fvst9bXFC9+v",
	"87drx9CV8oBHA9xZ+VOgZRoWHskGc7JFW3ZH2qRXb+pM+6vWj6vnA+xaloHw6EiSKq5kO5DQhcHquqKn",
	"tg6HwDNc8UYuK5IO5pKBhtBFJgxtTawrSFJ0Cw/lf1fu6hLVxbdV4TGMdQAcQsedFdgf1E+Uz1ERc3zR",
	"9m+m7VXECJH5KoX8hrzBVfpZ1q7jTrEQfaZ5FQW/sp34jVImJTlKQxY25pyQgC5ZWIOHBZrFUcGeWm2U",
	"CPiRPxRlFj/hF2n95tS9FfTdTFsHy8Dj79Hr3xLH1WbuFRIjnTh1Ta0JXKOuQ+O8Voils7LRnertrMDK",
	"9w/xwr6hPYq9fzmO/uF5bntRVfpLPfylzqhVVrRXys8KPA6yNe3CcX6quN5bCf7yEH15iD4pZee3KRzH",
	"juWCDe0ovvjt7+G3sW+sNrurGIb7F4kqfb/nRbXKsvl2P8Ha8A9/F32x21/GbjlKxvOTjUz3I158Zu/f",
	"kcOysTvYBYNxexsDe+TQwttszS/rxG82/Hni/nxc5ff56018rIIIe8r7tUWIkKgSgaGOjoeJliWW7pv8",
	"T6DzCYY5Os2XU/hfUaeLXnUMPe3J34+/0//bsTYXWFKPjkiIgJgHmFORYSxbosI5r+IjmdBUoSNZw0Pt",
	"eux0PbJzzWw6NGq4W+4rvPWVrtBfprx/tikvgWbSe6k4v+ytxSlzL4tWfLPwHcxYqwT2E8SX8q8XX1/v",
	"pV9rntogIvk8x9Ps8Uon9w01oJe19KN1JlnXxeTXTxD1DCK75mIpMhEgkg15DORyLWJDDQ3FR0cD/GR5",
	"kgnm4u88ZGpACR4jfZASSeIIS5bDKvRb0hhMWWH5Wxvi+rlUtTCGmhvUXvcNLIHdRfdYQX3N0qEE37Ux",
	"wCMY+2TjReX77DaWEDwoFzM8QxjXcrH1FyQH6sihh1CBNhEhaNIUGIi3nNOAYbBfeu2b3dMtxq5prGDf",
	"jsge8+WPhHh6H5llyj+RwzFrmU4c+4D5ZyIQfU4lY9C+OcFRBPpIWvAXKgor0ZJFvs4mMYagRue2Jc2g",
	"Kk3gnL2dIdZtC2F3a/wnwBJwHDCnapXtqQbS6BxE8tMnptChiNl46Er1c98OjgjxWJDoALtjxEtwxik7",
	"IcbUoPs+BAnogX+nyPvgfRnWCMWIssrQhcsy6BLCyA2ebyuMhNHu0LBmaQlIOgKGNZIQ8V0b7JYGGMOR",
	"xWbgDKd+XmVEADG7RI/AI8orWDAxKyUi2EOYUJY8xLdtThFgKZMS0HUHEhLhRH7/YmgCZEi6ReErmcDV",
	"xpThAKzzMiIjVutkpRY0W0+zHCfMuyJdVRK8FwJpQ+Xj+fJig2nJciRtbBGIY7rthE/r98VZ9tyhP/jX",
	"wBbw4RfD6TmT3Y2f3jAEOICPMsxJ4p/bOKCAsZA3UI9p79Jr148+A8O55Xs3ZY0DjrIPIFxG8Rddpwwm",
	"cPcBTbMclm0qjpUkUKWOZ9uWw1pwwwEepCKI90IpaZASnbmHFFUsHcquJUfvU/qPZfNUMZaRTlEO4dEA",
	"J4tdvtH/poX8Fv7BF/bXyIKuAzCxgcM6MzlQjuKW/z1v3fSiOZDNDwwSTOIH5wc1hRDPmnv1sMbQk9lQ",
	"Ho8KSll0gJI06LgcRFCkyNFV2rWqVCqWcyu4PMB8nf8MUp6DTxF0h6fsGUxO2Y2fsp9ld27DU/alHHyZ",
	"+m8gNJazgZD8FZmFfEGWQiwRNKJsiEoXDTjOnN6xzzVWFSrNAMgkm4mtK7wwexMb29SHlBUxw56pRpyM",
	"zg7PIuIT9BIe04Xd9/CT5B9l0wgPrWRmjqhYonTMbpmOdUzBalXLc+PCETdqNAfMl6i19PzdH2pBoR//",
	"eivKZ754Pg2sYTqNwPUA+xYH6wetW3/O3TCSQrp27D9hNorbqIT0t871SH+CRCrqjqEUdLn0ndjL2ZC/",
	"DL963YJEwlbQeFACeC5xFYR3AFkKtyNJqrsSwsSFQA+YvIi8yTm6ZAPHncdogwPM6nX4LxrecJBEPopR",
	"mHkD/0DR9bW+taNReeiLK51LJbwi1+M5BNK1qn8beypnYa1bdawZfQH4kUTrRzn6M149P378fwEAAP//",
	"ZCOUDEypAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/main/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
