// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9eXPiurY4+lVUvF/VvrcKp80Y6H9+j5CQQAJJmDIc+qVkW4CCLTuWDYGu/u6vJNnG",
	"Bpsp6els6tatszvIGpbWpDV+T6mmYZkEEYemvn5PWdCGBnKQzf8Fdd1UoYNNUj+/839hP2iIqja22C+p",
	"r6kKsBE1XVtFYPkFqJ+fpNIpzAZY0Bmn0ikCDZT6Gpk1lU7Z6M3FNtJSXx3bRekUVcfIgGyV/2OjYepr",
	"6v/5stzjF/Er/RKaREv9+JFOjWzTtbC2cZsuwW8uAnxo8v68mQ7eGv/e25UJXWecvbPNqYbszUAkQAwG",
	"lm1OsYbs5B36Iz4Av+XG+ETebu0RJHixw40TEB6bvNPojIfvNjyN2Ktlm69IdbYgpjdqIyjFNAfvzZ9B",
	"bMtGQ2QjoqLd6CUYnrC94PeN23PmFhtMHRuTEd8GRfYUq6iiqqZLtgHJGwygGJ0MrNVZD4bZykQCdC5F",
	"9oUBsb6Zhimy/6EAsYEAapqNKA22++Yie77cLx+U2gwpNt8W+LAhyUARExwMCv45A8APMQOizpmpYbTC",
	"gNviJ/ZH1SQOIvw/oWXpWAz48krZdr+n0Ds0LB2x/zSQAzXo8D34uyUaGmKCtBTDEgup0WVo6ut/uEww",
	"sOOwo2TSqQkmWuprStVdygUD2ye7QPaz/CMdGZ4LhvMRK6Mz8o9v6RRmP8M8Oh1qmirlS5mslFeGUCrn",
	"lbyUVTKZ0zxUT5HMcN6bbOIqyCbIQdTbhUDyPSXFg40dJCAdveKqjaCDKIBxguxk7Wp/pFOMe5q2x5G2",
	"3827NJvNpKFpG5Jr64iopsYmi1yWqmNEnBcOHbWg5NWSUpKG8FSR8mUtL8EyUiUIIRoWh4VCRi4wDDQZ",
	"Z/iaUtqde7tpt9sVvlcN20h1Xlwbp76mxo5j0a9fvojpT0x7dKKaxhcV6roC1Ym4H8skFL14xME2x4nG",
	"5P80LUSwQJfd4B0DmltLIFcM7G/r51XAvkHE8cAFPDqIhbzK7+qSydgP08SaUEM6dhBg+AyJZjJ9gW/C",
	"o53uGEkVqYugESYe29RR/ZwRTqqYV/PFYaYo5XNKRsqXC5pUQignyXlZKeWyGbkga6lv69yZffzNZ0V8",
	"JkVWZU0tZyUlk81J+YyMJAVqRem0ALPZYkGFRZRJfdudCLhOkoj/Z6Y2Bz6kgWMCAWQAhaq04R5uQ4L5",
	"s69DNRBD1X9oRNcI3QdUDRS+ifCwrsBlqI1NdQ9mEZ5if3CRtZ0mgO1O6AyfxdSNueRpIWFwCD1U4JOm",
	"aahYRkNJUQpZxnMLUhmVkQSRVioU1aJcOB3ug0/ecokg8g7oUzJYvitioaKbI/xJbFTI/K+pVxOdKLo5",
	"GtH/F3qYxJiaAx2uGcwbY+VSxbe4Ue8t6pkWrtM6aRfUar1Yn1iP/WqjfILmjYX2UMe3uP7efG3Kre5T",
	"7vZ8MqvjGVaMmvPc4YOn8DI/al+WdfZ3+FCT66/me6t7kW2+NgvN8/p8eH/SGerX77N2o9NE19e17H03",
	"P5xZTdQY5op3t5PivNF/gdo9pbOCujunDUNtA4etEwYxwVkJUhGl0J4ztGXCTp8yMh8iDdnQQRrodG6D",
	"B0jsVUUfDp9M8815hIL+oaDiOmMZ1LW7FbqX2DbkMLoLAVc/T31NZYuZonyaRRIqMfGpFBRJyZaGUvk0",
	"l1GG2bIGUTaV9r7oINVGTupr6jSXV9RyRpFUFSEpj4qqBGUZSSirZPLDXDFTKJWZCkipy/TEQLJC1TBP",
	"+HY4ku3BbCKgPIjdRF+MsRf25poOpAddlPiUq4TrSuCbC4mDnXnqa5YpgWtq3/J3pvbtDBSxZiIwKrpu",
	"zihwxghQ5DiYjIA5BOKj2ONHZa3Q9D5bUq29oIamDTSTbY467nAYwl1jLnmDJW9wEsuWIVRgSdak4ika",
	"SvnTcllSilpZKpSHuVOUVVEWavuw7CggDtAFVg4ZC23HnKCfoA+jQknLl2UkFbPDkpQvw5yknGqypJQV",
	"pBQzBQ0qCiNoprlGmHvtXm7Xb3r9LuPNT7l2of5q4o6u9di/nx8Kr+zf9916pjXRzrudOq0b/Rmc14to",
	"3rC1q4mYY87+3ppruF6s6xWn1a2/s+8RFxY1rMqFcS9zNn/KPRXa/QZ9MGr27VX/XM325W62loXdRl7p",
	"ZBz4WLt7eO1P741aq521HFUuVBUs5+FFKX/fK58rl+3sbb+Z0871udY9u1DOx1BZ1C7U7vj99qJZeOhZ",
	"8sNlYwjlJ3xTbfCz3D/0cv1O5lydOPQp127cPj4tmnKbdh9qtCM/nz1Pyk9qNXOP+uXFs/xU6L5qEMqF",
	"1v2kfd6e9K8VuWa355lal4y76qKebV4UDGSM8h3SIB1y1lZ6tdrD1Xj6LFvmw5WVfXp4bt53GuWbasOG",
	"D/dcNj5fjXNqtnzd058v7o337pPxPu0YZXaORnfSmGmXja6SzTz29LNndVK4QQ+t2n2/3GYw1K70WXAn",
	"RD45ce22obxfZV8UUrpp6vDkaSbD3Bt1rpqVa/IOZ5P6E3Gu1Olt9RW+vy6m/UxDN56aUrbaVaoZnO07",
	"FdqqX5u3eq1RKF5lW3LJaj6Vb63nrOpOqld3mbP7d3rdpGo+05/p9een6WvNXjzUL9C5WStna4ZVbV8+",
	"LBx3po7PHrTTu4v7J2uIGrVG9gyNoHo5Rvdvw/bjY67Qbp3PpedbNa89TNxpze6X6h23UpJOX1R0egWz",
	"hY7ddjttaHeHzZezm0rGPa+83JUrD69jOr+8vr3O1iYuPO/Jj8ajfvNwvihq19r1vNxuOO0X0uupVH91",
	"YN1oPL62WncVo/GWkUmjIGcurl/qxWb5LNdt9+w3qN+eGfkJPZWmRu1lpF5kKLydZisqvijfZc+aE7WY",
	"K0zgea5auNLnD91yoTPRitWX2syyXu9706fekzw/vXjLtizSH04e827nzigNe+d5xe68Xj6Qq2brorTI",
	"N7Mvd3ozf915rmB00zaaldenwvtD6fHpxa0+2gWiSKWOUXm5k/TXav/27q7yeP548Q6z7513pdKY2k9v",
	"D8i9zNanlUlVhkrRMl/1t54xaT9Mbx8LDnm8h9PC9Db7dlsZVZ9640794XEhS0+lsbpo9zqj8+783iiU",
	"573T97f+WxXPZ9Xx6FG/zWWvZ+MxsYc37y3dbp7lC4+3+mLcuMuoufPq6PT54VS5fbk/rcily9ep/fje",
	"NU5HvXNbeqXaQ3nc7eBW4959eVl0mrW7fr/VfSOLTPO8VkcuxcXLBi73q3LlxXQfqTZWW9ek+Irq5/2y",
	"RprvVfVVue8W3mj14s2Uemr1cnolv8zysDq2dK05Kl1d3qFe53kMzzo3mTmhL3W5Wq5UzmuorBmPreKs",
	"enXmlhrVudTN10z02Nb7neu+e5m9bOASHS4qtdq4iK/H94/vV0bhulV5waZ91uhf3HYec9pN8fq29zjU",
	"6NmwuxjlYNO8mFtZpVFuQag6l0Zt3nhullGx+d4p9d5HreL1FTq91FxVbl3W5me2m6vqzbfs2UId374r",
	"i/P7FxMXnsyO+35jjS713DtuDFukqr/Vum+PzcZpwe1M5JfbyfVoalwhWL6/bENI3wuPlZuOBa0XdVJ9",
	"nraeXi9fzOdxXs5L191XC2ZxY3TRUheo183W8q9vhbJdrVZ6tef+cO7m3pyzCmoYKN8fjYnSncJ6t6FY",
	"NXTWm3dGT9eqe3l/4k7vm69Y7+FSQ9Xmlyh3o0Bn5DH9lymy8RBztez54V5uXjZeny+f5q3uePJ8/jRv",
	"Zu9nrcX9/Lb7JLcum/Lzw/Nrc9ErPL+2jeb5ZPH82p+0zhuT1mt/3HqtvD+fPy2eu/3J0+JJbhqt1+d7",
	"M5VOjWxIHN9KEjFzvHg2kwTbiyfVuOFFqGxL+8vO8jssWjfZU5jGDLInMuAf+C+wNFBNQl3d4aqTjXQ0",
	"hcQBfHQWQKIBbohhiggeemKacj1m6NrOGNlAQw7EeryS5Vra0Sjzs40yAsgbjTJiyNEoEwbXDkYZMfRo",
	"lFmBCkX2B95Lh79plmYaqDp4yo3RrsIh+TX1ao7JiWaipVVndwCxEx3w8GGfJUIIk6H5OQ8eqKqI0hfO",
	"tlNfU0PTTO11stBOttnb/eEnns9SOACEy0nV296/97vvMJXxn4hmmZjHFfzne8S3TlPplGkhO/A4eVZR",
	"DmKopXyCTLG968hBqW9Lv5GmZFE+k5cykGFQoVSWlHIuJ0FNLmZyWlY7LQ1TS/cwXzt2J5gMbUgd21Ud",
	"10ZJOwotXCoWEZQLUrZYKEj5jKJKpUyuIGnlslLMIi2voGJqDzsHVPVY+wbQMXWAOQQCHZjYdmyTyd0f",
	"6Yg/8JA7CrMpfkLGlDGHR1bO5iW5IOUy3Uz+aybzVZafU+nUGEHdGXcc6LiUaTT8n/OUBxSE8oVhLq9I",
	"5WKpIOVlrSSVTrN5KZtTc5lsIavCfDHkKQ18jyuhBmwqLV+UZa2IJFQuFqS8ks9LsCSXpFJ+qGSHMFc8",
	"lbOppdt/Dx8it45RbBJMRsFBgj/+dk8okpUiLGhZCQ3LipQfFjNSSSvlJTmXU0oZqOWGp7nP9oS2GZnF",
	"YR+JOD7XHZ2xSOegd+fL2DH01NfvsRhtjjBhuqQhrM5C+ng2Z2wSwFASDG3T4MqpYLd+SM+fgegwk88O",
	"i/mMdDrUilIeKmUJlk4LUi6fV0+RAjW1kAvpQJLD9NEPYfnOKBtSdXeaPUHVTUEZldVyDko5mD+V8ghm",
	"pLIKh1I2e1o4zWdLsJSRU1GFeLf19lSIE3HTi9vChGNJVKnzsYUegi7/OeLLn4Uv3/ZCGLpZjoox/Ckb",
	"izeMcV3YtmkfyN1GiCAbq+Cq27wBiE0ELDhCfO7X2YQexsAmaO5JIHvKVHepkM1wKcCwIqO9z6jZaPfP",
	"z/SOopsNc+aU660zy1E6pvHQvnuyW9dz9aLycs++ceapr6mLaorfBRNIeJRKp97Z7i8fKop7fUaI/PZI",
	"X0tY0x7Gz68F6bnbzNfyWsFuoGtF0W8v+6pUII1Wr03vlNOJ1BxfvNnl+wouvF4T7VSfGJOrXtYgUJ/R",
	"+7vrVDrF1qxUkFXVHzqlpnlzU128Ne+zip67ni1qp6jzdDNWOzadlCZPbhu2WvmCQfruPb3K5+5v6zcX",
	"Z4XHR3g1nnc67VG/Co3m7PmhN6vY08xkHz2LwfYBKddo3kFOPKY0OrctMEMKmKA5oMg5Ad0xpgBT7vTg",
	"SMQIVQOWq+hYZcMocMbQAdAOhfBpQJnzuQaETcb1eMrmQqEPgQoJULiQ448Mbriae7N5JpsZpIDiEREz",
	"OmNMB8QjQY5VwoR0BjVP2z8MwziqckV4CnWsvXhyOZUWv7xEoeRLbYW9krxPUnt6OjmVxV1BOzz5EGId",
	"aUB8CvhC/Axp4FGwvxXNRBQQ0+EqMsRkQKCuByP4K26Ika7RENCWfuu/T6sYmeZIRxLWkPCr/hpxEXKr",
	"ZzIZuVjO5UrFYl6yTFVWSxltRIeuZsu24lqvsktc+1WdOpksOoGWRU/EnpkI8KDsxWHEONG5bPG/+JAn",
	"fYN2u7SOLn3ma8jxdyoR/0L0+HYYfmxRGNZxJMxBOvw1t0lh2JHvimfhi/hnPNP1WKFjeoJB1SE2Po3r",
	"VghwCXq3kOogjTFXl4wh0diKQo0xVdW1baR58tCAcya5IHBsSCi7dm8cJNqAsF+pq6qIzUV4KK1jz08A",
	"qA+5CAOYkn+E90GFFKWBpSNIGa+2TNsB2AGQAkgAv/oQvHvEf4Ii7WMA9+xrGiKYmyDiIL4SiCou4PMg",
	"Hje7L9Y8e4+46TGkAL1bTIgJWPAg3KpJhnjk2vtagHbc/PoasQZEC5H6ORO6y3FCnWEqNnQdU9IwVc0p",
	"sueMnALrG/cyUddi9400Jq1Hpo2dsSF+GSLouDbyaC3iwvgLLQCqgSTVtK092almGpDnGHjWbT5BjAvF",
	"G5cOpwJ9TSlFpGbzGU1COSUv5eFQleAphFJBloeqUizIWgkd6HfZIFPXXlThP/ylD/I/+fq+HXJ/W2Re",
	"ZOhJyID+NxJfyPP2a5SgsIsLDQtyWdUyknqKilI+OyxJEKJTCcqZTDGvqUVZUw9w6iVbxbwB4Uv7O4nu",
	"r7i2b3ve2xa680fx2/MjdQ+huFCobtRnoaEhdHUn9bUQE0oLPCcCcOYWogCdjE7AdeBhSAN2LtdBaYAc",
	"9SSVTmmYWjqct8SFVZd+kKGNUIKLJBQnHPGXcGsU2+PewcFJtHDvIhsjERwsRgqVJCqioO6FkPxIc1vo",
	"ryOWFW+8Dh3uE4GagQmmjg0dU7jiP5OqLG8ZiS9DdyKR3bGcAzAexT3LGR8BZtgZJxnu4yO0/z73Zkxo",
	"96/nY8OsLMty/lTKlIclKZ8tIqmcU8pSeSjDgjKEMtK0FCc4b1I/7qDrhR38yZkx6RR/E83FfRYkOSdl",
	"8t1M8WtG5vd5aDC8wLkkNI6G9vt4FYO6R6T9dUj7cxAhWctaQQMac/1/itZ1RIDnfUTYyiVu1tfi0WBO",
	"HWTcHm3IRxtygCccJXwDspZoU/aCug+RGyvhgsekp2PS0zHp6Zj0dEx6+jckPQnfEH3BJPU1V5RlJu1j",
	"RUFv0XtvYvFkG2u1svn02DIZ79EuG1ctvXaFJoWH54vCUH19Lj7JF4u2XpvfL3S9ZfTvlJ5118rpdue1",
	"Rru1s/dWryG3ubyoZZ6r9eLDvF546qrvtw+99+dOZvzUHWVuuu1x8/XCeerW582OvGi+tvXWYpR7fnie",
	"tBYj/NhhMigzhg8ztsE3JTt2b4z29Ll3pisPNUupFl6VrMx4vY6uKvj29SJ7273ItBbNfGtxQeuGPtaq",
	"9WKz+1Rodu/zrcV9rtmZYfjYWrBzwau2rF41izfzsq09NHTVKOjaZX9xY/QXT9mxrhotquT6kxujNVXY",
	"WciZ9ZRrZ1Sjx/Zjalftmbowpzc5LafNC0Q1atmnx/ZYxXxf06fH57F2WZvfLMZGy+gVWq/1XOuyOX96",
	"aBit14vcU7dZuD3X9Naird8+9HKtrsafv2quj/n+jLKp4MJEyfYrHhzcp2zZYXKg8vTeMSuziXs9PLOs",
	"gpmhllGZvy3Gk077tDhWXmuZ2+o1yuObTvGseleed56fUF+anFU12cmpWrH/rtwWav37xl3bKU3kt1LJ",
	"VrOZRqU775cmHbVFbCnzWjMqDffxtjiCcjZz3W3fk8ti6by0eG6Vb2ZGs9Me567uas7tW/6mqhr3F50s",
	"1FBjTs3LcrlkGI7bnVn5YcWeQR7SPLQRHf8uNaSrXp3J7Qs595xt99WLRr+VNbPtXJt0J4V5+yIzaRpl",
	"6/nKzLQeWosmztjqhdWG8nu33WucdbrPXU2/L3T0dhGda49NeTLv9coX2qRwrlzVmtrl+LZ1peU6F2PY",
	"O+9f9DO1C2jISzWkV7bv5cJEnfQf2pkG7i9qhduadt1+Hc96ubMmNFpvT6+NfOvhYvHUG9/fXuj5x8Xz",
	"2WOutehlM/LtRX/xpLebynmtq762nzoyG5ef97MWgf2nbPvS6ncutcaTnDEfSKPQm2fcVjWshjQW7cxT",
	"Hsr1+dOkPewvKvnnfqOuvjYe29n2XfNy/N43Co+9nlODF+1u/6Gc0R6fcu2Lgh1WQ7SHggWz5bmCM6/K",
	"ZTnzXC1MVUOdquTehkSTuYpyWz8tPZZUeTzvqPbL+elJ8XLk3OQ7asMu6Xnz3TztTeFEun40W47TO79/",
	"N55JfaI2zkv3FnxBjdtZsfP6cJWrdsqv+uS5XR3ltNNe5tSRFJlOpUzmwTUe9N70tF2jp3nlAk7scg9l",
	"pU5fG7nnsHJzdaGVR9Xpzd1bv3hm3N/kOrZZexj13dMmwnJPxqaNihcSupZeFOfUuOzJcuvxsjsd3TUn",
	"T5fPk5n9WEJqozSHrzdSxpGkVmY+6rYvc+i8lyeT1kXjopbPOG9n5XH1idKXSs+okjqV2zVo9V3pdHw9",
	"ei12F9otKVZmd6+2C+ezqV5/X7zWrGb9ASojs1e5W7zBl86trV9K8LRTzjTd3HjRPlUKeu0u2y1dtvNm",
	"2xzTXstuPzvl+ujZrTQu1X7zNG/ITj73PG10rs/bBRkZp9KiYRcK+TdNh4+lNzc7dt6dp96Zfi7dLd5n",
	"eTpzjZmUyxWajQWkj3eX1Qu7ez7Mo0Xn8ayq1GmhfpVXlfbL3cI5e1Mm/e5z9unOnZ+qt+369T1elHS9",
	"+VydYZtmoXZ6dTV19ZvaqKkXOr2iPi0uxli6f+oqstadqqVz9fpqfKm/zs/vnerT/P2iJl26vVz/EZ9f",
	"lcjlVUM3sv1C+xW2ja51P3mtkJfsWbmnl85Ks1kn0769rWrdvqWqWgdmanIeL+oF9NS9zdTz9N2Byqxs",
	"SxdytjQvav1bx+jcWeoQvpZKF2fllyftLodKD/ZI6y3kl8bdhanNH3ptgxTqxKxeFs3bp6lrDvu489jI",
	"P946r82L0+l4RPLz++GtjpQuUfp6v7h4KvZ1JXt2R077j/1utTJd1B1jONWfajl1lJfcSSYzkW66nc69",
	"bGi6XiyOyKxz9fbauq8bEzKZWf1q1zBcC+mvl7Jy/9BzMo0szd+2puSG3NVKtk6IfftwVp3OSDOX026z",
	"43l55shIs66lejOnX3bucA4/ZvIX3bxp1Qh+Vm6elS62qrO758W0gy7HehM9PnYXo8Kb27pvudbMqWu1",
	"0ZPRgCrJyRnUNtsntx3rrXJa19xJ5VS6unGa+Wq7d5/yHpN+fvIZgjay90wv3iFohQenuvztOXR1Hrlh",
	"I8e1CY/eiaSLiFgWEQHr55iJQCHTEp4YfQ4wUXVX43maPDXNtz14gTB4KGJjeTU6vrgX/ukFxrgET0yb",
	"SKpuutqLatroZZo5yZyeZF6syejFtBCBFn5RTcMwyQt7M1tONJAoetpuKMB0DClQECLA/4yfdoZ1HSgI",
	"DF19iHWd/ZXOiTq2TWK6VJ+fDMiT6fJoKcsMAlL9soJEA4ZJsGPaADsUhM0k/EdhvgHCzjUgjgngDGKH",
	"e+J0xKFqDoUfxc9XOwAOyu+PHU6nHBuqSNR3KZwqaiavlRUtX8wMZaUAT7OaUsrJmXxZKZ7CPRIh94ID",
	"+p0RyfttVTXJUMfqBy/MnyUp/G2JqTPsjEWZJWggHv8OoG4jqM0BesfUoX/8DXoH8Y8snJAAEtMZIzsN",
	"XOpyBsSDEw0ECXccz8EYTlH04Afc1tC0Faxph9r2/OsKpkm4L16ZVrUR55lQp0AzOf4FZwjwzrLxFOto",
	"hOhfQnmM1YtQTaDMo3Il7d2ZiEdVIQ8+5JkSKDqQ8U8mRDyQMB4bAYoQKl6MQOWuHhA0hyujZvLPEpgD",
	"sqyetwQnMIVbO6ja7TvcD8AaTBxkE6j//hjjPxtH/vTI5f2OSUynZrrkg9HNxHRehmyahHsOySmkLdl8",
	"ILI4U//D771HoKIjhqtDTLRQueYDoC6ine9s0+FY5IuLA30xkWJAfsL31/9w39PXL7wm8klQsOJbOqVw",
	"7fzFQM7Y1OhLEBXNv0FQQzYb5R8vXErIi6Y+CRc1ZWxsZRKvajN3xA2xjhhW8Mqo337SpSXAc78IcscE",
	"fuz4ak1oD6hgNkYEjDEv/TggkPFdsWIQaH4Cgvw98TLx2BujX+5pFHOsvlYGRPAETAEi3FOIuIwwhVqg",
	"QrLc29icsSlDWzwEBT1nch/Z9OAw96C0gljYRiNsEkkAK5VOTcXcqa8pto/iyenPotnVs8THUZy5WNeA",
	"tymAQ4Vp/fRc2yX8LRTOd9xvJ+4fkDDyh4vPg9NQmF70L648clBsy8+peRQOhdEhdSoq+8iPhslImWw3",
	"I3/Nl79mcs97VkhKDoIKKnMsyw0dJi21kETzDT5hiYberdTXTC6TyZYy5VM5ncLQ8f8giz9QumUO6iqp",
	"rylFzioyKmelIswPpXw5U5TKKjyVtGxRKxaK2eywVN6/zNK2MttQMV1n+ZIISpuEiSsA5N8ZN/avJ6lv",
	"+yDNlnAhPuQkRKd+Ka64YtPxBaLEY1ak0lnINjClIpeHg9lCtuP1lBnppgL1HcpTXQRls1Zyunb4NlyC",
	"cC0lbM/vb9jDJJTcssPnXqU78eWPtN/2x1T8cnyh48XX846DcAiswmiwfEaxBdZBLUgl3sTsfciHpFf7",
	"EkWrkW2H1nKw30ZI1Kn7T8qbPzTdt83goHujHO+L5CCD7oFTqeWlQNuGc28TwUFiC4GurB4ygKdTiLjG",
	"TpXkYmAdheDux18CdR8QLM+YAIMVStvceY0bKgVXEwVLDGQoyAbmcB0dUfiK9yF+rMVjcUwPuDXgfoBq",
	"w3iMtSTEXWMVGy4wwoa2wG7n+1xhdTFXeucXI0xuUPdb7zHaJW+9R9rKRaRDO0i4lPBVbrgPHzk+6Sru",
	"lvVW124h3C9yrw6WQqtjGo8r3FYR8KRT79LIlLw/+noo1uhJJdrmMhgmYcMybSf0eA99xe4aOuPU19QI",
	"O2NX4SWjI8++QNf9Yk1GX9gnP1YKQ0ItnnsuD2YOg/PGKAhhvfLzXqPeVXeYyAhZ26DW9JcLKXu7VTHs",
	"sNGr+Bns3pstFkGjUyQrADFYEQOwSNHILfly3oRL5PC1myTaDLZQPxeecHPGWRejkkiPujXOK1IxN87J",
	"huw16wqw+RJpwRPCUNgMdFGC9w/EUX/B34GSrjOu6hAbtKKq4te4m2O/eJoIz0azkWUjiogT+Do49yQm",
	"kagDiQZtTXh0TkCdcdYB4aXI6Fj4Ovz3LKBmWJsV5kOAmZrDduyI6ARgWvDNRQPyPzoaQXUOGg8X/xs1",
	"GKmQABsJI6n34OX75Pv2i5zZkFAL2og4A9J46AAV2jxvFxMeE2HOPC8UDSt2IqMiFSRdiWp2drxC5zrj",
	"Jjetr0Ox41vJVw3Mni0+okyKFjSUd4h6sUzuIIn+UYEUq4xOdPri/cLmTdxWUmfEtX0GGSNfgg6Jy8Aa",
	"X/6GOyWu8CTVfplC3UUxU7cDN5BnbWDgpnRZyQ6IL3lVd1fXoaIjv6np2qFCbXriENazuAuhNcSikPba",
	"JF5e+foUV8LQ7v3OUUpUk7Vs07CcnXboR0a/jBNee5aNppjH7ggfnsZ5rbDR7DA/31Di5GK77FeRXs8N",
	"QiKqYIe5Dfj+AkcxzKAJ3wEcIT8YiK+y04xez9DvcWXB+W87zSLAnzDNHncTbZgRL6tGmApXjN8zI9z2",
	"N2bGSDfTreKYD+ZlWX4EPU+/xxjMl8THB+10Os/+tDpdVdAE/zXsBNlpThe/MGGjxxH2DSQjl2OFFagq",
	"WyZcEVVR6IWpe+Wu4mSYCB3YwHHXuTp0tcAz6f2v38tF8+zA6dQQGlifv3imjBGeIuL/A0NHpPqlGB0y",
	"sPgWynTKwn5pd+oqsQxZNTVUHUNdR2SEtgsMNhyo/vg4gdHJFopsZR1iErsibyHTjRXvy3X4oMCktARV",
	"bMOZcPh9/Iq+3fT75hK5oH4etWPEl19OeOavvrf8Jvhb5jn0cXUpTvXT31XLitSJB+HOZBtB7VdpqWEj",
	"xsefU/wQB6uty6+T4LMOlaAA9Za8bI4D/vMopgT1Xp8L20IMXgcZu96IZWFfSL0ivDx4AFNxnl3NEb6r",
	"IYY2gorYu59g5WrWoZEOwJp4TUnPrjAeC/OpiKnillPtT397fQL+bueNuxt4QyXs1y9+WYt6fcVwEeoT",
	"0EEo2qir8XDdAZqpugYizjJkIqY5VwL/jsyfigHF2h+ilbM3Thiqms17OfDnHvuHcBHyCE4C0LsIbwQ5",
	"WwMWtJ058B+pdED8slXoBFTjWpXtdPgopooi6t93u7nQ5axdXRx44rovr2tkXPv348NDatmKRVc0rY7T",
	"fxmz+IcCPiKs+O6iovOA1Php0bulYxU7y7hVX984VKtlswqVVgzlpT51nBCau4zW2mpkEuvFUW+43Ora",
	"fi69uvwiqstAlMIREiXNoIMV3QtxF3PEXEn8rBXgIJsib1bvpOjdgkTjvYiFR+aq273zhjBF7QTwPVIu",
	"VhRIhfGFDQxe+dlo6700UFwhhcTcSBO7ZXu0MXKgPfdyRPgCwh9ZuatTwKPbmRBjC5gU+fOKe1iuF1Yt",
	"19M4wkFUnl0jlV4LiHJJEHP4svpy8OcUT6r0aiiyg5i2Bm2m2LsETiEWSLf8MFjV/wNXi1dWDbVkjFN+",
	"YyK2Vi+0j2yFgclDECB+VfxYcT7DdhxNjrBOxlu/lEg93l7vtWYM6PNjCrOY7W5ZbvRna84xJdkTTxkp",
	"jPK3K9TRgx+smcRMsxv81qG2rK+zg4XOM/0PSCrR2Od3zN8wm7COJsziV+aJ+17kAPIBaSaSsMqTdGZj",
	"ZPPAbwvZomiiG4oVnjMtATp4yoZseJ7uc3HCJLTq/BQ7Ty9Buv3quluN+UHKY/gKfd4sihWl0ikDq7ZJ",
	"zaHDbSCMFGNZXnTxZFdLEuH9fS+An0JwG98EsdWcdnwgxLWqWH8pxNViXze2xsTRx3gCInYjlBj11A2r",
	"I0sPA38OY4IdDB1EV5wmUYlk43ieAbFBX4Jmo+E8hdU9PIwRV1/EN36vnGXaCiYanmKNJ+6F6FwxTR1B",
	"ElptwxqhIl0rhsldrzBow7B6a7wVdWAgjMvuSN5MvHFxucedESzOqBlroPM1p72hxT9ddtQSnr+wPr/j",
	"S9k3hcbsLvDZUDwimIxeoD7y/Fk77lZ8B0JNBpYHYDv3XTy7U643ZcWfMXbfm0SbINc6HwL+B1MqsoH/",
	"N1Zivc4mNNkrEiVP9G6ZFFG/zZR/dt6nit8Sv6Fl4vIuZOsR3X50630UUK4FKeUJ8gCCxkMXCG4bT7n+",
	"gq6NP2XRKYYAgl67nrSc914x2PtpXxLwvwb8651RyP+saWqxaB95RB2+KVHNm6PGGgv1qTb5Nb7XSZII",
	"eD0nbZcTLOXPnqGl4pUZsw/BRQ6UejTISkPv6hgyvuxljYXiBjjjDqiM7kJb0U3xgIH9hAXdEsTwUd4c",
	"CqBIsF9jMjS3gZWp8gFEfUiOkBNJ/BKpEpBE4kj+oUHT7c2wTNLPE5SeNXyIO0yI98bgcYyKsYFuN/CZ",
	"XdEgSVTvKiR3UEs2KmmbRcF2vh2ra68kjGyLcv6g7SO82i+wfKy2zdl6vF9u8bA/Yt8IW0sOfmytTrIN",
	"RuuQ8XvtxKpH3FouRgT1clZmC7BpbFInKQ1DvL6rLnVMQ3TpidFCCA8XFaUC/DgnEdKseh8ybdNnyWJK",
	"YEACR/ydHdrWgHAfClcLmfjhVQyIo8+BSxgDjdUU1/sL7X6BvvgO9yGKA2j93Afj0l9gMh6dFqHbvJAG",
	"d/g4yDZ8n49LPdD5z92TAakPwRDq4kPsxZxRnkwNFBfrTDgEa6R5+SfbFasQPiqKFgPim82BSVBSAoIw",
	"DPixPVu6toQGr2L2GuS2oXa87edcmJg9HImV4LFIC0BFA2NTXflkQPzqNdARmWSe40DVXYqnSJ8DqGme",
	"Rhz4fYTTV4TZ0zG2AKgQDRgudQYM1QAE/zCxImHCvvvH812dAHAuqGpt2ytbMOBcRKUNCFvXGSNsR71Y",
	"ab6a389bhZQbwwTJrNvEaJrPPiAGtKjIqPToW2DFRiMa1Mammkr7POPbFipKtpqts+2/0F722Qyc7pxy",
	"s7uVbK313Loa6mUUxAcZRVNaDtUcvISSX6A0hNt8bTjOX+4b8ZNADsW68PfJUIrJeQ0FwW2N3mDjVjcX",
	"/LBhV4nxNZHL+/v4xSddGt0lEWxnBhFpixfLG6JCP0kCe5VcdNOcuFZEwUmL+xp4CdODVBoIuRioKX7n",
	"f/+LAeER3pdcwfvS9P01wUQRxcWfbkWmcE1Ki/cEicTtlVzsOFnGm58lsRKKCdM/+ZgYX+GyeVycHggN",
	"ns5helU5Q/lRMzjnGRwuDathmDhoJMqQBo3o4ub1fhSJB77yE2wxbrINLv0KmHpOfabtQBIkFM3YnoOZ",
	"gY4N7NBNCQmtxARuXhBRVCYdm66uAQX5WQqexYhoflp/zPyiX94+EPYtUuzLeJgk53vxNK9QQlXslpZ9",
	"+uKmMOA7NlwjaXvxO1p2+9v7pF7JNm414lQFXcekKtQjj6DQWqKZ4CEQXXlYBXPG57oFYPKW9O4yHaKc",
	"0MGjmBTF2yVJxHHNgIa35dCKToc7M84lb4hhm/zHRDm2mXP8aei35foSYc6P/zOALuCaBHWaxK/Xl4zC",
	"3e/8ueO1x8YTe3MkwoQm4sQn7m4J+D22t55Quw1zeWSdAyeYjADmBZa9HEVtTqCB1ZUE2F8lHj9IPr+O",
	"1cbTVSz32+3CPpnWYjBig6eNe+I25OKsO/p8dezNRfacs384MhBxYjWxiJtsl2W4lT+SgyoSfUSCT6jN",
	"izDrg8g/Qj961dPjRof/SkwSHzlpmzpK4kjst99rqU56hcQinBmbK7fELz5gd/TyAZPk9Nx0zUuvpn+9",
	"QZ1OPwfOr9cZdymxXUtjTkbQbLVT4d9pL4geWLxAw2W69vhWfLPt/RpMHodJK1k38a+rlXaxH7M/dVby",
	"fH66GSqmHer2Qx5x67NxK7ksSRS7IjkDv9rsFQuEXTbNR8aVLAj1oY5LpCcjoOMp0qIlJ8JhLn6YhhYq",
	"6r5SdDEuS8BrJRvr2uPuLe8EnvikQHORiAqxsI0iBK5BB0kOjvMmrqYMiFW3Qzb5PZbQmjq5KsSfZViM",
	"o8AD7IurDXw3xc2ste/dNb4opk10jPxfjRDcpAqsBSiG1YKLTiGTjdcBllmhmw7KR23M5yYA2gp2bJFK",
	"xIbvlNgdlND8Hlse1gdtGvD+DcLMqgkLaFDTC8Ck3OCERLgK8VyHw1CDBu4dXk0yExFAsSdJKlHiCUJe",
	"ncRbAFM/HzgNeL2BXabfEPopfgO99s2OBda8yeLQ3YlnkMsgNsGlbERd3Unisi8JswSb1XZkm14Pytj0",
	"Bmwg9uSlSDWJRkPxaLyFkg6pw8Ad/xxetrOMy12on1cjNVpi3l2RtoSxxQt5MSPgjdwwV7itVmx9miXM",
	"AgHhmDwS1a/N5NefX6mwdAK6fobLgAy8ll2D1HYcCW0pHb3RyLUkos/OxYcCZEoQKBuq/3hVTurnJ6Dt",
	"N1wJmgoNYspZDFK8eO0genmDVKgexl4liWhCmlI1kqL0yzcXa3CIVpgROaM7byxaL2SnHfhFVuxE8HB7",
	"gT9qp3lDuZi7FTcBt4T7ehKOZdrr4E4g9k1FhLzz+IN4RPhPg+0WvlOJsptAnG1Cq/2L+MQmxS45wJ4t",
	"88JQEY2J4pWPG79IbrRYkte2I9DSxcEC4RJhi1vUlZiJ/6GiLZvorOdH8u2kyOzZMY/z5qQaQYJz+w8S",
	"Xt/OtB0vliuk1nmtXdIpxdTm3BuBIk+AUJmng3eXpBp6JS2VTVsNJ8l4Gk9Mf5VdleYPQPjD94WORQE+",
	"vSjASgr/ajWAcAeqUJ9BgVkv7Feo6+ZsrXKAgTQMfWXGjyYXtqkXxzRfdGiPeLlHYtkmb8Cm6OjFb5SQ",
	"DjXJ+7UlAMJNXr6vdarCTLnkA0LFD5dtbpYK1WcWFtiPRiaugmyCHERvoIL0PtTdWDsDxwNwHYwGOhsu",
	"YjXCSdrcg8ROGKluH0lEGhBMNPTOUzk5INjjniH/ibBYOshma/5//5GlckV6htLi2//836/Lf0kvJ9++",
	"y+li5kdoxP/+3/+T+jALTepflZR1C2O6U4US0vdKyg0ahn0mP00S3D82dR/7WQzdX9lOBGs3Imv8cXvI",
	"97iMs0/sb8Vmj3VOB0dKJ9xqbBJR4hV8nKx3NJOLwtW3Q95L5qenlnxfIYBtGUBr7QVCTDTyklaQbpIR",
	"jS/8sCF+vx4H6m+rLVr8Eyx7hirz2IC9YD82ggf1991eH/0nXdjOXpXVK9wQfx1uKvAZF7dc6tA783fz",
	"WdflT3AVaakUB4dQR29Rujvy3PG1LZdMiDkjQZOmOQ8PG9lQW7ae+4SHwpqpfr2w8Br0uCtF17kvJQo3",
	"0Q/dxk5cifaNKlekCn3oJy8rKNQfHro8ukKYD3nUJdd5DdNGonz1uxMrDvzeO59HKLHqEtMC4eiTRbcD",
	"48s+8jN9O/jS72LabSVQ7rIp/c54ayH+2llp6xX+p4iHRCs/fzZq/wqeyYCC1fa63+v7GhGIpv2iL1ui",
	"lTzCGEXnax15qQG7uBZXW7v9DIEe4XQ/4pu3/Yx1Y7A2RjysDlmByKFig/G9D8uKpe6YbJbhLg2vhVtQ",
	"gTbKgsPKZcQG88mmrphWrusGr30buaYZIzEs/vATVr8BUTCB9hzwgETRUpth9wkA52iKdEZGPNdCo36r",
	"bX89+YT93x7t1gK/77KlIkh8SAQ9czfN5O/YG5wWkZPTzEn2JLddn/HSjf2VPq7zJzCkn6zjb2B8XprT",
	"2Ty5qimYjc0gHWrVDLzutYh0uNydk3oL7M5Jk9zErjDphPrxxO7TMDVuWNt6ci/7a/vJ/Rm3nBxGzx1K",
	"LjsgOIU7oSMg34GDil77PhvFNGIL8tjaq0u9XvNprj1qJvnH8RndgEAyj6of/Nm/1KBdKoygCiJoiB2R",
	"BwyDMsJ4gbQBCbYgDh6pQngogTlwFGv3hSNgQMviWw3CKTyzl+n3UQGgO0YUgTGcIkBMYX2FOk+a5m3M",
	"RbTSHASUKQqQ24hxS8QtvWyISxETSkFqEU991jT2/1gozAPi6cQio94Hfpp/7jWPZT+p0EEjXt4VYGdX",
	"TlrxaYCdOpl9xpsRGZ5GsrscONqdUfI5v33GLW6LnGHa/E/ycDAcSioHryUG1HwsgrRHf0m116BvdNIp",
	"mO4UKv/194WLslPsFyTKv/iE0NBg5STYfnoUaKjG9y4HRBvjwkJFzFVITIJVqHPukQYudcUbn6zXN99S",
	"E9xbzd9penOo6nKnG8qWQwFNTAGOtJQNukcvX7jUpRZny/Hv1uXFr19ZwKrFaj4mrF+baEHNl47dNI+f",
	"8iQ/n8orjYs0QE32V9Ur2OG3hSOmA0YutCFxEA9JGhAFcZHD3prsGlTVtRkkNOQdFZjEnxYSlRtcqGND",
	"7IVO7qhYxF5HYlQrP4vQ2r4IJeYX841Dw1mXHGIVWZMiV4N28utgCEc4h/rwmQTEYwtcdg3cVtgt2mbw",
	"RzqlYNsZa4nUwVWNfwAfBfh9iHt3RJCgaXNMcUxQ79yWinJGqDtgjqANmKTh5WFEjpksyzKv6TNGc6CO",
	"TZMijpaOCWw0RVAXv4i3L2cNpr6H6n5AG4X4OZY9qBKrTjpBmSlvNjCGFCgIET9qSosvPBnuZrVpq9S1",
	"E3WsEWM+9sbPxZD4r5cdtDbNMDRtlLgDr9nWpu/btWqhmC8C3e9KFq/xpVMG1jQdbd+QGMdlx//Q/91o",
	"9U0+lKvryborwepk6xT+oPhqU17TsfWIgPaNH+7kzeMNTShahYbItpH2wgbHb8mPPRUMkxOTH3jqoWRC",
	"wTA/xWyXPYqhwIKjBK+rqySknEbLOXoCO3YO76n6AuO1BxK3IfbE5RIw9M5dm3iGFBorZdYP6g2NnWZh",
	"EhTPpkNYUa+0KqGWUdhAi/iKZOuazEbZsC1Ut7Js4np32+lu6gi6LfBbRD1tC/xOEugbEy+CShi7Pato",
	"UmV0nu6hujZ25h0eFyCcyXzjlUhFstjADXuZH4NtREOVXyNhcTFFznVzth64UfVieSN/7Nl66mtq7DgW",
	"/foleC2dkAk9QS67EWmGqJM/ITzFmj+wxP6/TLNfIjMFkQOpr9/9yO0PzS7uPnyD/KfUD/anZAyv+6XV",
	"Knd1vzINZUo7N1pzBRJD4nBbhT2EKgqMFdxVB3UdmMMhVjHUBwQSLdz/SZhThSfRss13zM0lFco7AQfG",
	"DzaXZ08yXN3BkoMI5H1rTVcbEA1ZujnnbsI0wA5TfSkvOk0AHI1sNBLXrsO5F4Il4uGW2xDWd28v6QHR",
	"MLWgo46ZYqOHWziFQlY90zz/VIHqBBGNaT4xGhtTXuiAsM8USDH1k469qD+P3lSTfaQDqNompb7HlUGj",
	"ZtrAx3pguTYv9p0ekDChCghGootFZCEvciMyEKBfB4Eiyu3oFi+1jxFx0sAZu3RAfN2MxyQidnym8ruG",
	"5w0BHDlN4nDdjKEYVJh00KHDu3Ko7Dte1U9h4n6CyIDwWjjUtf3kD9v0WnhhpjIRTWcgcEzDCyLjy3j7",
	"9OL9hKUwSB+hA8KW0TDjSIrrHQ5BdRxY5zGhDn+w0DlRx7ZJeHdfzsywwyRfKozTIUv811TmJJM7kf0e",
	"DNDCqa+p3Il8kvNMI5wLfDmZIV2XuOvzi4gck9TNzRrq7JklPNlhbFuGjLHdjeLyFdrc1e74FZWXMWZM",
	"KPvhFXORS6ZHkdMP2RUgHJBQ3ehI2pnps8a6xoNknQek69fsdLcxjSiWZQ04MLKynMTQg3FfYhpatL0f",
	"OUN6l8YihtOLcH+XiCn5SC95B+LgEyPYN3G3EISQScmhZqtXsR5Y/ukXs7LC1JOG2+C+Ho54COw/JRDy",
	"47cFLfxlmvkCVT0uLtvh7LpSvWFKlKli7hsJsjN4NXCvOm6oLLvfDYh3YQfts0oVcPFumA6KyhbH9Bns",
	"gPQeN1yp49qMc0Z58lKTimQgxl5hxcL9TEXVD7oqqOpLQKdTeTnz2dcb7uwWXqrw+ZjE9QECdRF8yqPd",
	"I1jkIwz3TsbrcP/59uNbArpFVaU1NBPzWRva+ehMp/PqMDNc5Xmzc+ogw48Si+vzI4wbQbVZD8kGBNNQ",
	"JHSoablQgWLq03InYKBNuRRATxYPSChkjuEu9HLVhAdthgBBUfRfqcUbUE24imAsut9gptJ4h14vuZuM",
	"37cr0D0E18Wyt9G2S78J+/Ny7rOXCtIS/k4qi9DSlmK/cZQUrfsLwGrxZAPORQFMXtJ6QKI4nPY6vgk3",
	"J0U6Uh2vhvQ6IRmQcD9CekBM268K7enWK5TBJk37Xy6JM1qXWqjq3jyYHcxRx2yyEWSK5Vph7kA9Xdva",
	"gGBD1Ntm6jI/BdKWNbRj9wgFNHkutL0kaF6V215uffXttcKQ6HYRF1+iWTCZwK6E2cAgcf8EgPoQQDIg",
	"UdMnpsuNeYkdPLVNRHN6J/LcFBzm1OUPQs7tLBtPsY5GwjE9RuoEYF4igCfex+yCu8rX6konMKoI6jIV",
	"3utQQRNjYpZDuCHigp30zv8bD3s4QP0Nb+O/nMfl5fxnr0NMp2a65K9RWKhrGNCeB1mxK0goIob/k4oi",
	"57cf6ZRlxkYnCAIK6rvwaFyCZms9LaI0cGfSeCLwjBlnpjZPBqE/BCP6RbjjbiNF2UVW4I81asjuRw1R",
	"zPn0K1Wg5m31qFn86ZrFl++RBJ3zH0EEdWwJb/b31frZac/ayM2HXHlIex3800GNcWFOwmRoQ+rYbuCE",
	"iRKPmH+dfNaaCcWh/4rhOZLHRD3DGnulTpF2cpQC/61SYAXt00e1+S9Wmy+Rs8psdtQ6t3EM+SMC8yjH",
	"fotax7Ah0oZho1K315sjKgOjDw/LjcHMngiS2oqcd+5uyLmnbigc8LvphvIW4UhdbncdurycgBcgLxxb",
	"7NH63ywty5+9jl+C4+8jLg+hd6SvnbXJwz0Pad8g7Dl/43r2/Q1eiQ2Uf3RY/BaHxecJh93JQLyHDjDj",
	"ei+pEwAu+X8ABQeZKAybV6urct8/r64u3Bhsfq/+UJC+4tOKSC73Yix4AuzQ7yIpvhBV2gfEWxrayOsJ",
	"GThddEwmHgF6Lz1hy/RKqY2DVccIQAXrTO1zzAHxt7BSIiAgIZpmcmnMdhVJTVp/Qe5obxVgXKZ5+mf1",
	"ifjDOqaA0UH0LPZ2NMr8m5RZbqMc+Tjjy1kPiT5Zgd3PvhlUCd7FsJlIAwcZO/n3yZpsZkdSOlLSX2VO",
	"OurhIb4gGowIIoxjDPuqHF++8//F2kbDrscMuC3Jq54hfH4ibZhJ3gS2sJvJVmz/UuwktcsTlY+Nvk2D",
	"+hxHavuvd+F5noZEMkgf9ehfoUdX/CgCLzhYNDD3Cq2butet7EBdeTM72FvOHxnCfzNDuETOJm7wSdpy",
	"euunnjTdwUQc0E6YaEKZU3sbitep5iCr8RYlezdZvMFOfNS3j/r2X2f3/gR9+7Dg57i6pj83BJrrFcuM",
	"sqQA6ITw55AHGIWzBMKsCuoxcc2eCjU3Xc4Kebn2uenawJyRaHYOOhmxCSci5X5DDPWK9+0ful84dTKn",
	"/YxIa/NfFWN91FXWI09+tgXPMxXsQAWHWfPiqGBPjSNKBB+y7K1O9V9OTv96EX1o/OKqHP7y3f/Pg4Ib",
	"dyOn3axgKwR1F+xrJ4tYfU2SH61jx9DGo3r5MfXylxkOlvKLk/zBMWY7ynfX+Rg3+kmCfkswWtzVLm0m",
	"R852fPX/FpXCt8lvLGvgm+BDDDgIcAbgzjfr8yKz0Zg3L17az5nwyrIw5PcnlfwWGqaOpLgKJicDUo+Y",
	"9CPm/pVStGMEqqZhuY7o8BNqMhUqx2KqqmtTvj9MAPR3svFJzhNBAgfGp4XW+LA76B3ub+cY9fKnRL1Y",
	"y+v0zW3BDX/7Ze9m6oW7+GQbFPIOh3X+Qw9K99uAvgfFxXgzfCj/z/LnOMbGHF/oPydoxUOxeLreX9ry",
	"lztvQbXLw5361Tc4NcdFlYffFlpQ8ZML1gGJVgsSdfiCKr4QqJCqUFTnDSra8UZMWNe9pzcTfqIUPOTe",
	"f1V32WPJ0we8MAPvj/RQE4IP0DsfMqlDeMGeTQ1VFVnOKpkdWcfRlPF5gT4bWUf6qHQnJ0jS6LCDlesN",
	"HEU+ahdHFvF7Q3+28IdfZsULNJKd7Xcb6XMHM108fR4U+bP1GRFjnbvzAwtjon+OAT9H09/fGvDzE98q",
	"X6Cum2pS4bZmxD8TGnoCQGX5L17AGFCdp62aQ/Dmmg6kXhUV4JgO1AFBU2QPCHpXkdfTzBvllQPj+svy",
	"7+wlE0p7OwGgTjQ8xZoL9WWKLHvRDIjqxRaENjQbIwKgH+jMlZtoFDGb30YqwlPhyxFlxZwxdAbE/0p0",
	"pAdDVx9iXUdaWgRCB70IRbh00L5s5leiX1tpQELtOn87+99sZyIhOH7MhBQIgRCmHCIPlvv5UExGeJqj",
	"4nc0K/0ZXpokXvzl+/IfW0xKgeq2mXQPtNmEiLcS2tFOda2WHxzDP47hH0e94qfqFRtsLpsZwyF2l525",
	"gny4YD7yhWPc8c/Vhrd/FRbC+1hRtmjR7udS3E9QqOWjQn00sRz19t30dt6LDxEV0S/fg//eqLPXNWRY",
	"poPWmmLxoq+YjAB6F0cFy8n9ZuZBM3jet/xTtPx2sEjwX+uyPB9Xu8gbHVXwj6Vr/+UKfsjrGeBvJNqb",
	"LBXcEwDagbIrUJyI/mtBZDfTmJfzLFVjruNj6vcw5gEOmIyxgkMxUkGREJc4WAeQzJkqLiYTdZb96VY1",
	"cJ8mfrvZbvtXwWZ30FISmQ/UtCTWw7vDbWI8h+g0O3GdzM5cB2ra0c9zVEKcv7oIpMLV+D21EmHyiHWI",
	"itSWaKJNwBp570cvoYYiUeslyKAR33iVYdCABE0cg2QHSDQxhQhZM0w3Ov9a1jNQIeFhZ9Q10AkA98JU",
	"48eyDCG2gUvhCDEBEWnk6S/uRb8IEwoPi+FmFrGLgCNBHaB33qKeV4wJFlJd20bEYbzCsvS5V651QKJV",
	"xymAYDY2dRSsRUzesJK6CrcVIY0dloyC6ODN9hfPIPVpIebiMAfZWsRWjuHlf0p4+Zt/lb5j17vbX1AV",
	"vLM3au4g4kOouadRwsfMDxgk4pD7qAccvXu/3krAa6jtWFRF1G3juaXCMbFWxRvZBub9mDmhiljQUHXg",
	"ZTk2Z4wMMMXQr+O0teRwaG3PKcEFqpD4HxdUbQ6GQ0iZb+wopv4UMWV7F+lLKXGx335LdXLPKODXPty1",
	"b+tKycSTAems/ClQQ3WTjCSde/CiHdQjXeurN3WuHlbrX6rnA+KYpo7J6ASAigMsG1G2MFxd12txrqEh",
	"dHXHe1aXZaDBOdDxEDnYQKGteet6tOk1bw9ltFfu6oAp69tqD+n6OgAOIejOCuwP6uoq5qh4cxyJ/E8h",
	"8lUMCdH7Kqn8htTHVUJaFvMT7rYQoaZFgQi/1J/3GyNRRnuMmEyizwVFQQ2YREWHRbrFkcOeam+UGsSR",
	"PxTmFj/hkcb+lLzDFTzeTGQHS8Uv36N4sCWErM39NTRGXgkym5oTtEZmh4aYrVBNZ2WjO9UXWoGV73AS",
	"5Y9De/T2fvRE/YvS8/aisPRRefyl3q1VtrRXatIKPA6yUO3CfX6qDN9bRT76m47+pp+TV/TbdJEvtunA",
	"Db09juz397Df2HdYm99VDP/9h0b1wd/z6lrl4GK7n2Ca+Fe8nY7c99dzX4Gh8exlIw/+SIgAdxrsyHD5",
	"2B1sisG4vQ2JPXpoqXK+5tGg8acYDV3vIn2kFRf7682DvD4Kf/37lVOoJ2kBRaGmmoeJnCW67lvLgCL7",
	"E4x6bJqju/lfV6OMXXsMbe3J9L98Z/+zY10yuKQkDdMQMXHfsqAoXV92qEVzUa8IGMhQkA3M4aFmQX66",
	"Ht25xDgbGrX7LfcV3vpKq+6jJfDfYwlMoJ/0XjrQL3ubCSrdyyAW3819ByvYKrH9BLEmH8Xa8X31O61b",
	"26Qnsin/PMm3pLhY14A3DGAyNG0jiIXaGFbFZE30a+pAw0IawESEaQHbJby3pYIJtOcAOn7yyYA42EBp",
	"0SKAjRA9CahnrwIjIY1NNjUezgF6h6qjz8FsjNVxkMEicsMt3Zxv6HrpAeAgyt3rjr2Xrrfgb6L4v6d+",
	"nOhsLC4vsBJMg9vyEdq/P98sEKkKG7IPiIW/TLNfVkZsqA+/bLsRrTXLW7wmmwaCfAMYOaZQzyITQQos",
	"JIKOl2tRC6l46H10MiBPpgsMOPf+LoISBwyXCdYGKa+0AybAtHkzDxOM4ZT3oLi1EKmfg6pJCFKdoE2D",
	"b4wMbJSay3tvqKaGAHpXx5CMUCy5iP4TfX59SwgelDUdniGMn7nYCirARhq22SEUqE68IE8whToWPS1V",
	"qOv8l177ZvfUp7Fj6CvouiOBxHz5IyGTxcd+iekO2BaYtUz8j33U/3ci0J1JN2DQvtn7UQT6SAL/ERXX",
	"WOTrbBJjJW10bltghhQwQXNuT0JEs0xMnK2qACQA2jacsyeF5So6VtkcFPiJS54Ubzx0Qf3c9xlhSl0e",
	"hj0gzhiLortxin6IMTXYvg9BAnbg3ywmP3hlujnCMdKsMnTQsjkCwAQ7gSVjhZdw8h3q5iwNINAw1M0R",
	"wNT3BPKLGhCCRiafQfCc+nmV0wEi/B5dik4Yu+AR+7wGkMchwrSyZCOBVMeQZzADqGk2ojTCjPx+6ciA",
	"WAeaaUBMgAEddcx4DiSaqP8z4kWKVkrC8/VU07bD7CvSgynB2RdSYb2q82J5b4NpYNpAHZsUkZjeXOHT",
	"+l20lh262A/+NQgd2YNfDLMXfHY3lnrDEeAAVsoxJ4mFbmOCHow9kcN0+7VmUL12/eQzMFx4hnbT1wTg",
	"GAeBnoc1/qLrjMcE3nGoqqbNk7+9YyXJVNBxLcu0ect/NCCDVATxXhglDVJCTeQud/YHyTGl6H2C/zEt",
	"kafJi0UwlMNkNCDJklds9H8FbnAp7nnUX/gPkTUdGxJqQZu3crORFEWvE+A98Ni2Ah9cFANdiigwujcd",
	"z+I5IJZtWnDE5ZxlY6JiC+ppQEwHQA/kfP3NiNr1PHx7Iypf4UOy3pthz9Q4gYJnh6e8iQl6H3mSiSl+",
	"kuxgLI697JMZIWYsndGAs2IFAFAxXScuKHajQnDAfIlCv+fv/lDjG/v4tzzHP/PN8GmQDZNqBLQHWEcF",
	"ZD9oG/2rrocTFtbUL/47YKPAisoYf/dCE/MnSKSl7hiBoMOsb65bzob9ZcTtayainFP7MWKQzIEQ4qKV",
	"Tlg2gLoDMKEOghrwlSsv1Ctna8CCtjOP0acGhBeg8Z8FwnpHIx/FqJyOKcKhPFXR15vWjsaEni86NVGp",
	"haxIxng+gTW16t/GnupNWG9VbHPGdGg/dG39KCd/zdPhx4//PwAA//+mKM0O06YBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.1/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
