// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unikorn-cloud/identity/pkg/openapi (interfaces: ClientWithResponsesInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock/client.go -package mock github.com/unikorn-cloud/identity/pkg/openapi ClientWithResponsesInterface
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	openapi "github.com/unikorn-cloud/identity/pkg/openapi"
	gomock "go.uber.org/mock/gomock"
)

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDGroupsGroupidResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDGroupsGroupidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDUsersUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDUsersUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDUsersUserIDWithResponse), varargs...)
}

// DeleteApiV1OrganizationsOrganizationIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiV1OrganizationsOrganizationIDWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.DeleteApiV1OrganizationsOrganizationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiV1OrganizationsOrganizationIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.DeleteApiV1OrganizationsOrganizationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiV1OrganizationsOrganizationIDWithResponse indicates an expected call of DeleteApiV1OrganizationsOrganizationIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiV1OrganizationsOrganizationIDWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiV1OrganizationsOrganizationIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiV1OrganizationsOrganizationIDWithResponse), varargs...)
}

// GetApiV1AclWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1AclWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetApiV1AclResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1AclWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1AclResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1AclWithResponse indicates an expected call of GetApiV1AclWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1AclWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1AclWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1AclWithResponse), varargs...)
}

// GetApiV1Oauth2providersWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1Oauth2providersWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetApiV1Oauth2providersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1Oauth2providersWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1Oauth2providersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1Oauth2providersWithResponse indicates an expected call of GetApiV1Oauth2providersWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1Oauth2providersWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1Oauth2providersWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1Oauth2providersWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDAclWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDAclWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDAclResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDAclWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDAclResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDAclWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDAclWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDAclWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDAclWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDAclWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDGroupsGroupidResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDGroupsGroupidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDGroupsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDGroupsWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDGroupsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDGroupsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDGroupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDGroupsWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDGroupsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDGroupsWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDGroupsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDGroupsWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDOauth2providersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDOauth2providersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDOauth2providersWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDProjectsProjectIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDProjectsProjectIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDProjectsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDProjectsWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDProjectsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDProjectsWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDProjectsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDProjectsWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDProjectsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDProjectsWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDQuotasWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDQuotasWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDQuotasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDQuotasWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDQuotasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDQuotasWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDQuotasWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDQuotasWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDQuotasWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDQuotasWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDRolesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDRolesWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDRolesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDRolesWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDRolesWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDRolesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDRolesWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDRolesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDRolesWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDServiceaccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDServiceaccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDServiceaccountsWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDUsersWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDUsersWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDUsersWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDUsersWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDUsersWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDUsersWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDUsersWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDUsersWithResponse), varargs...)
}

// GetApiV1OrganizationsOrganizationIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsOrganizationIDWithResponse(arg0 context.Context, arg1 string, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsOrganizationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsOrganizationIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsOrganizationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsOrganizationIDWithResponse indicates an expected call of GetApiV1OrganizationsOrganizationIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsOrganizationIDWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsOrganizationIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsOrganizationIDWithResponse), varargs...)
}

// GetApiV1OrganizationsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1OrganizationsWithResponse(arg0 context.Context, arg1 *openapi.GetApiV1OrganizationsParams, arg2 ...openapi.RequestEditorFn) (*openapi.GetApiV1OrganizationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1OrganizationsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1OrganizationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1OrganizationsWithResponse indicates an expected call of GetApiV1OrganizationsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1OrganizationsWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1OrganizationsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1OrganizationsWithResponse), varargs...)
}

// GetApiV1SignupWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1SignupWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetApiV1SignupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1SignupWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetApiV1SignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1SignupWithResponse indicates an expected call of GetApiV1SignupWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1SignupWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1SignupWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1SignupWithResponse), varargs...)
}

// GetOauth2V2AuthorizationWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetOauth2V2AuthorizationWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetOauth2V2AuthorizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOauth2V2AuthorizationWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetOauth2V2AuthorizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOauth2V2AuthorizationWithResponse indicates an expected call of GetOauth2V2AuthorizationWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetOauth2V2AuthorizationWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOauth2V2AuthorizationWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetOauth2V2AuthorizationWithResponse), varargs...)
}

// GetOauth2V2JwksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetOauth2V2JwksWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetOauth2V2JwksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOauth2V2JwksWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetOauth2V2JwksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOauth2V2JwksWithResponse indicates an expected call of GetOauth2V2JwksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetOauth2V2JwksWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOauth2V2JwksWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetOauth2V2JwksWithResponse), varargs...)
}

// GetOauth2V2UserinfoWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetOauth2V2UserinfoWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetOauth2V2UserinfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOauth2V2UserinfoWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetOauth2V2UserinfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOauth2V2UserinfoWithResponse indicates an expected call of GetOauth2V2UserinfoWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetOauth2V2UserinfoWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOauth2V2UserinfoWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetOauth2V2UserinfoWithResponse), varargs...)
}

// GetOidcCallbackWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetOidcCallbackWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetOidcCallbackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOidcCallbackWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetOidcCallbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOidcCallbackWithResponse indicates an expected call of GetOidcCallbackWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetOidcCallbackWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOidcCallbackWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetOidcCallbackWithResponse), varargs...)
}

// GetWellKnownOpenidConfigurationWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetWellKnownOpenidConfigurationWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetWellKnownOpenidConfigurationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWellKnownOpenidConfigurationWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetWellKnownOpenidConfigurationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWellKnownOpenidConfigurationWithResponse indicates an expected call of GetWellKnownOpenidConfigurationWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetWellKnownOpenidConfigurationWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWellKnownOpenidConfigurationWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetWellKnownOpenidConfigurationWithResponse), varargs...)
}

// GetWellKnownOpenidProtectedResourceWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetWellKnownOpenidProtectedResourceWithResponse(arg0 context.Context, arg1 ...openapi.RequestEditorFn) (*openapi.GetWellKnownOpenidProtectedResourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWellKnownOpenidProtectedResourceWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.GetWellKnownOpenidProtectedResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWellKnownOpenidProtectedResourceWithResponse indicates an expected call of GetWellKnownOpenidProtectedResourceWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetWellKnownOpenidProtectedResourceWithResponse(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWellKnownOpenidProtectedResourceWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetWellKnownOpenidProtectedResourceWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDGroupsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDGroupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDGroupsWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDGroupsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDGroupsWithResponse(arg0 context.Context, arg1 string, arg2 openapi.GroupWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDGroupsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDGroupsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDGroupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDGroupsWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDGroupsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDGroupsWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDGroupsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDGroupsWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDOauth2providersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDOauth2providersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDOauth2providersWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse(arg0 context.Context, arg1 string, arg2 openapi.Oauth2ProviderWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDOauth2providersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDOauth2providersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDOauth2providersWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 io.Reader, arg5 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse(arg0 context.Context, arg1, arg2 string, arg3 openapi.AllocationWrite, arg4 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDProjectsWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDProjectsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDProjectsWithResponse(arg0 context.Context, arg1 string, arg2 openapi.ProjectWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDProjectsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDProjectsWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDProjectsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDProjectsWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDProjectsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDProjectsWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse(arg0 context.Context, arg1, arg2 string, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotateWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDServiceaccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDServiceaccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDServiceaccountsWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse(arg0 context.Context, arg1 string, arg2 openapi.ServiceAccountWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDServiceaccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDServiceaccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDServiceaccountsWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDUsersWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsOrganizationIDUsersWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsOrganizationIDUsersWithResponse(arg0 context.Context, arg1 string, arg2 openapi.UserWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsOrganizationIDUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsOrganizationIDUsersWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsOrganizationIDUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsOrganizationIDUsersWithResponse indicates an expected call of PostApiV1OrganizationsOrganizationIDUsersWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsOrganizationIDUsersWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsOrganizationIDUsersWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsOrganizationIDUsersWithResponse), varargs...)
}

// PostApiV1OrganizationsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsWithBodyWithResponse(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsWithBodyWithResponse indicates an expected call of PostApiV1OrganizationsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsWithBodyWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsWithBodyWithResponse), varargs...)
}

// PostApiV1OrganizationsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostApiV1OrganizationsWithResponse(arg0 context.Context, arg1 openapi.OrganizationWrite, arg2 ...openapi.RequestEditorFn) (*openapi.PostApiV1OrganizationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostApiV1OrganizationsWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostApiV1OrganizationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostApiV1OrganizationsWithResponse indicates an expected call of PostApiV1OrganizationsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostApiV1OrganizationsWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostApiV1OrganizationsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostApiV1OrganizationsWithResponse), varargs...)
}

// PostOauth2V2AuthorizationWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2AuthorizationWithBodyWithResponse(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2AuthorizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2AuthorizationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2AuthorizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2AuthorizationWithBodyWithResponse indicates an expected call of PostOauth2V2AuthorizationWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2AuthorizationWithBodyWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2AuthorizationWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2AuthorizationWithBodyWithResponse), varargs...)
}

// PostOauth2V2AuthorizationWithFormdataBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2AuthorizationWithFormdataBodyWithResponse(arg0 context.Context, arg1 openapi.AuthorizationRequestOptions, arg2 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2AuthorizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2AuthorizationWithFormdataBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2AuthorizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2AuthorizationWithFormdataBodyWithResponse indicates an expected call of PostOauth2V2AuthorizationWithFormdataBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2AuthorizationWithFormdataBodyWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2AuthorizationWithFormdataBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2AuthorizationWithFormdataBodyWithResponse), varargs...)
}

// PostOauth2V2LoginWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2LoginWithBodyWithResponse(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2LoginWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2LoginWithBodyWithResponse indicates an expected call of PostOauth2V2LoginWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2LoginWithBodyWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2LoginWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2LoginWithBodyWithResponse), varargs...)
}

// PostOauth2V2LoginWithFormdataBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2LoginWithFormdataBodyWithResponse(arg0 context.Context, arg1 openapi.LoginRequestOptions, arg2 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2LoginWithFormdataBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2LoginWithFormdataBodyWithResponse indicates an expected call of PostOauth2V2LoginWithFormdataBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2LoginWithFormdataBodyWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2LoginWithFormdataBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2LoginWithFormdataBodyWithResponse), varargs...)
}

// PostOauth2V2OnboardWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2OnboardWithBodyWithResponse(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2OnboardResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2OnboardWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2OnboardResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2OnboardWithBodyWithResponse indicates an expected call of PostOauth2V2OnboardWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2OnboardWithBodyWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2OnboardWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2OnboardWithBodyWithResponse), varargs...)
}

// PostOauth2V2OnboardWithFormdataBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2OnboardWithFormdataBodyWithResponse(arg0 context.Context, arg1 openapi.OnboardRequestOptions, arg2 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2OnboardResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2OnboardWithFormdataBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2OnboardResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2OnboardWithFormdataBodyWithResponse indicates an expected call of PostOauth2V2OnboardWithFormdataBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2OnboardWithFormdataBodyWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2OnboardWithFormdataBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2OnboardWithFormdataBodyWithResponse), varargs...)
}

// PostOauth2V2TokenWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2TokenWithBodyWithResponse(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2TokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2TokenWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2TokenWithBodyWithResponse indicates an expected call of PostOauth2V2TokenWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2TokenWithBodyWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2TokenWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2TokenWithBodyWithResponse), varargs...)
}

// PostOauth2V2TokenWithFormdataBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2TokenWithFormdataBodyWithResponse(arg0 context.Context, arg1 openapi.TokenRequestOptions, arg2 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2TokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2TokenWithFormdataBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2TokenWithFormdataBodyWithResponse indicates an expected call of PostOauth2V2TokenWithFormdataBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2TokenWithFormdataBodyWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2TokenWithFormdataBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2TokenWithFormdataBodyWithResponse), varargs...)
}

// PostOauth2V2UserinfoWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2UserinfoWithBodyWithResponse(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2UserinfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2UserinfoWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2UserinfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2UserinfoWithBodyWithResponse indicates an expected call of PostOauth2V2UserinfoWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2UserinfoWithBodyWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2UserinfoWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2UserinfoWithBodyWithResponse), varargs...)
}

// PostOauth2V2UserinfoWithFormdataBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostOauth2V2UserinfoWithFormdataBodyWithResponse(arg0 context.Context, arg1 openapi.UserinfoRequestOptions, arg2 ...openapi.RequestEditorFn) (*openapi.PostOauth2V2UserinfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOauth2V2UserinfoWithFormdataBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PostOauth2V2UserinfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOauth2V2UserinfoWithFormdataBodyWithResponse indicates an expected call of PostOauth2V2UserinfoWithFormdataBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostOauth2V2UserinfoWithFormdataBodyWithResponse(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOauth2V2UserinfoWithFormdataBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostOauth2V2UserinfoWithFormdataBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 io.Reader, arg5 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDGroupsGroupidResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDGroupsGroupidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDGroupsGroupidWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse(arg0 context.Context, arg1, arg2 string, arg3 openapi.GroupWrite, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDGroupsGroupidResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDGroupsGroupidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDGroupsGroupidWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 io.Reader, arg5 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 openapi.Oauth2ProviderWrite, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDOauth2providersProviderIDWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3, arg4 string, arg5 io.Reader, arg6 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4, arg5}
	for _, a := range arg6 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4, arg5 any, arg6 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4, arg5}, arg6...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 openapi.AllocationWrite, arg5 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 io.Reader, arg5 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 openapi.ProjectWrite, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDProjectsProjectIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDProjectsProjectIDWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDQuotasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDQuotasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDQuotasWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDQuotasWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDQuotasWithResponse(arg0 context.Context, arg1 string, arg2 openapi.QuotasWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDQuotasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDQuotasWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDQuotasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDQuotasWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDQuotasWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDQuotasWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDQuotasWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDQuotasWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 io.Reader, arg5 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 openapi.ServiceAccountWrite, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse(arg0 context.Context, arg1, arg2, arg3 string, arg4 io.Reader, arg5 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDUsersUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDUsersUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDUsersUserIDWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse(arg0 context.Context, arg1, arg2 string, arg3 openapi.UserWrite, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDUsersUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDUsersUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDUsersUserIDWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDWithBodyWithResponse(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDWithBodyWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDWithBodyWithResponse(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDWithBodyWithResponse), varargs...)
}

// PutApiV1OrganizationsOrganizationIDWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PutApiV1OrganizationsOrganizationIDWithResponse(arg0 context.Context, arg1 string, arg2 openapi.OrganizationWrite, arg3 ...openapi.RequestEditorFn) (*openapi.PutApiV1OrganizationsOrganizationIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutApiV1OrganizationsOrganizationIDWithResponse", varargs...)
	ret0, _ := ret[0].(*openapi.PutApiV1OrganizationsOrganizationIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutApiV1OrganizationsOrganizationIDWithResponse indicates an expected call of PutApiV1OrganizationsOrganizationIDWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PutApiV1OrganizationsOrganizationIDWithResponse(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutApiV1OrganizationsOrganizationIDWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PutApiV1OrganizationsOrganizationIDWithResponse), varargs...)
}
