apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-identity
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - oauth2clients
  - oauth2providers
  - roles
  - organizations
  - projects
  verbs:
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
