{{ range $name, $spec := .Values.providers }}
---
apiVersion: identity.unikorn-cloud.org/v1alpha1
kind: OAuth2Provider
metadata:
  name: {{ include "resource.id" $name }}
  labels:
    {{- include "unikorn.labels" $ | nindent 4 }}
    unikorn-cloud.org/name: {{ $name }}
  {{- if $spec.description }}
  annotations:
    unikorn-cloud.org/description: {{ $spec.description }}
  {{- end }}
spec:
  type: {{ $spec.type }}
  issuer: {{ $spec.issuer }}
  clientID: {{ $spec.clientID }}
  clientSecret: {{ $spec.clientSecret }}
{{- end }}
