{{ range $provider := .Values.providers }}
---
apiVersion: identity.unikorn-cloud.org/v1alpha1
kind: OAuth2Provider
metadata:
  name: {{ include "resource.id" $provider.name }}
  labels:
    {{- include "unikorn.labels" $ | nindent 4 }}
    unikorn-cloud.org/name: {{ $provider.name }}
  annotations:
    unikorn-cloud.org/description: {{ $provider.description }}
spec:
  type: {{ $provider.type }}
  issuer: {{ $provider.issuer }}
  clientID: {{ $provider.clientID }}
  clientSecret: {{ $provider.clientSecret }}
{{- end }}
