{{ range $provider := .Values.providers }}
---
apiVersion: identity.unikorn-cloud.org/v1alpha1
kind: OAuth2Provider
metadata:
  name: {{ $provider.name }}
  labels:
    {{- include "unikorn.labels" $ | nindent 4 }}
spec:
  type: {{ $provider.type }}
  displayName: {{ $provider.displayName }}
  issuer: {{ $provider.issuer }}
  clientID: {{ $provider.clientID }}
  clientSecret: {{ $provider.clientSecret }}
{{- end }}
