{{ range $org := .Values.organizations }}
---
apiVersion: identity.unikorn-cloud.org/v1alpha1
kind: Organization
metadata:
  name: {{ $org.name }}
  labels:
    {{- include "unikorn.labels" $ | nindent 4 }}
spec:
  owner: {{ $org.owner }}
  domain: {{ $org.domain }}
  providerName: {{ $org.provider }}
  {{- with $options := $org.providerOptions }}
  providerOptions:
    {{- with $google := $options.google }}
    google:
      customerId: {{ $google.customerId }}
    {{- end }}
  {{- end }}
{{- with $groups := $org.groups }}
  groups:
{{- range $group := $groups }}
  - id: {{ $group.id }}
    name: {{ $group.name }}
  {{- with $roles := $group.roles }}
    roles:
  {{- range $role := $roles }}
    - {{ $role }}
  {{- end }}
  {{- end }}
  {{- with $users := $group.users }}
    users:
  {{- range $user := $users }}
    - {{ $user }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
