apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-identity
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - allocations
  - groups
  - oauth2clients
  - oauth2providers
  - organizations
  - projects
  - quotas
  - quotametadata
  - roles
  - serviceaccounts
  - users
  verbs:
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - signingkeys
  verbs:
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
