apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - groups
  - oauth2clients
  - oauth2providers
  - organizations
  - projects
  - quotas
  - quotametadata
  - roles
  - serviceaccounts
  - users
  - organizationusers
  - auth0organizations
  - auth0users
  - auth0organizationmembers
  verbs:
  - list
  - watch
  - update
  - patch
  - create
  - delete
# These are for the Auth0 migration webhooks.
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - auth0organizations/status
  - auth0users/status
  - auth0organizationmembers/status
  verbs:
  - patch
# These are special, hopefully temporarily...
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - allocations
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - identity.unikorn-cloud.org
  resources:
  - signingkeys
  verbs:
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
