apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-identity
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-identity
  template:
    metadata:
      labels:
        app: unikorn-identity
    spec:
      containers:
      - name: unikorn-identity
        image: {{ include "unikorn.image" . }}
        args:
        {{- include "unikorn.core.flags" . | nindent 8 }}
        {{- include "unikorn.cors.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        - --host=https://{{ include "unikorn.identity.host" . }}
        - --jose-tls-secret=unikorn-identity-jose-tls
        - --refresh-token-duration={{ printf "%dh" (mul .Values.issuer.maxTokenDurationDays 24) }}
        {{- $adminRoles := list }}
        {{- range $index, $name := .Values.platformAdministrators.roles }}
          {{- $adminRoles = append $adminRoles (include "resource.id" $name) }}
        {{- end }}
        - --platform-administrator-role-ids={{ join "," $adminRoles }}
        - --platform-administrator-subjects={{ join "," .Values.platformAdministrators.subjects }}
        {{- $systemAccounts := list }}
        {{- range $k, $v := .Values.systemAccounts }}
          {{- $systemAccounts = append $systemAccounts (printf "%s=%s" $k (include "resource.id" $v)) }}
        {{- end }}
        - --system-account-roles-ids={{ join "," $systemAccounts }}
        {{- with $signup := .Values.signup }}
          {{- if $signup.enabled }}
        - --user-email-verification
          {{- end }}
          {{- if $signup.tokenDuration }}
        - --user-email-verification-token-duration={{ $signup.tokenDuration }}
          {{- end }}
          {{- if $signup.signupTemplateConfigMap }}
        - --user-email-verification-template-configmap={{ $signup.signupTemplateConfigMap }}
          {{- end }}
        {{- end }}
        {{- with $smtp := .Values.smtp -}}
          {{- if $smtp.host }}
        - --smtp-server={{ $smtp.host }}
          {{- end }}
          {{- if $smtp.credentialsSecret }}
        - --smtp-credentials-secret={{ $smtp.credentialsSecret }}
          {{- end }}
        {{- end }}
        {{- with $onboarding := .Values.onboarding }}
          {{- if $onboarding.enabled }}
        - --account-creation-enabled
          {{- end }}
          {{- with $webhook := $onboarding.webhook }}
        - --account-creation-webhook-uri=[{ $webhook.uri }}
          {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: 6080
        resources:
          requests:
            cpu: "50m"
            memory: 50Mi
          limits:
            cpu: "100m"
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-identity
      securityContext:
        runAsNonRoot: true
