apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-identity
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-identity
  template:
    metadata:
      labels:
        app: unikorn-identity
    spec:
      containers:
      - name: unikorn-identity
        image: {{ include "unikorn.image" . }}
        args:
        - --namespace={{ .Release.Namespace }}
        - --host=https://{{ include "unikorn.identity.host" . }}
        - --jose-tls-secret=unikorn-identity-jose-tls
        - --refresh-token-duration={{ printf "%dh" (mul .Values.issuer.maxTokenDurationDays 24) }}
        {{- include "unikorn.cors.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        ports:
        - name: http
          containerPort: 6080
        resources:
          requests:
            cpu: "1"
            memory: 50Mi
          limits:
            cpu: "2"
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-identity
      securityContext:
        runAsNonRoot: true
