{{- range $role, $spec := .Values.roles }}
---
apiVersion: identity.unikorn-cloud.org/v1alpha1
kind: Role
metadata:
  name: {{ $role }}
spec:
  {{- if $spec.isDefault }}
  isDefault: true
  {{- end }}
  {{- with $scopes := $spec.scopes }}
  scopes:
    {{- range $scope, $permissions := $scopes }}
      {{- printf "- name: %s" $scope | nindent 4 }}
      {{- printf "permissions: [%v]" ($permissions | join ", ") | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
