{{- if (not .Values.ingress.issuer) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: unikorn-identity-ingress
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
