apiVersion: v1
kind: Service
metadata:
  name: unikorn-identity
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  selector:
    app: unikorn-identity
  ports:
  - name: http
    port: 80
    targetPort: http
