apiVersion: v2
name: unikorn-identity
description: A Helm chart for deploying Unikorn's IdP

type: application

# sentinel: patched at release time by release.yaml; overridden by --version for nightly builds
version: 0.0.0
appVersion: 0.0.0

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: 0.1.17
  repository: https://nscaledev.github.io/uni-helm-common
