# Set the global container repo.
repository: ghcr.io

# Set the global container repo organization.
organization: unikorn-cloud

# Set the global container tag.
# Defaults to the chart revision, which should be in lock-step with the
# actual release.
tag: ~

# Set the image pull secret on the service accounts of all the controllers.
# This is an alternative to dockerConfigs, but unlikely to play ball with
# ArgoCD as it's a foreign object that needs pruning.
imagePullSecret: ~

# Allows override of the global default image.
image: ~

# Organization controller specifc configuration.
organizationController:
  # Allows override of the global default image.
  image:

# Project controller specific configuration.
projectController:
  # Allows override of the global default image.
  image:

# Sets the DNS hosts, X.509 certificate subject alternative names and
# oauth2 issuer etc.
identity:
  host: identity.acme.org

# Issuer related configuration.
issuer:
  # maxTokenDurationDays defines the maximum length of time an issued JWT
  # can last for.  Due to key rotation by cert-manager, the certificate will
  # live twice as long as this value, but refresh at this age, so JWT tokens
  # issued just before the rotation will function for their lifetime (or near
  # enough).
  maxTokenDurationDays: 90

# A static list of registered client applications.
# clients:
#   # Must be a valid Kubernetes resource name.
#   foo:
#     # A redirect URI to return control back to the client.
#     redirectURI: http://app.acme.org
#     # An optional, trusted, login dialog.
#     loginURI: http://app.acme.org/login

# A static list of registered oauth2 providers.
# providers:
#   # Must be a valid Kubernetes label name.
#   google-identity:
#     # A human readable name, most often used for UIs.
#     description: Google Identity
#     # Must be one of {google,microsoft}
#     type: google
#     # The issuer is usually provided by the oidc provider and will have
#     # a discovery endpoint attached to it at /.well-known/openid-configuration.
#     issuer: https://accounts.google.com
#     # The client ID assigned by the identity provider.
#     clientID: foo.apps.googleusercontent.com
#     # The client secret assigned by the identity provider.
#     clientSecret:  GOCSPX-akjfdns3238r328r9832rewjbds

# A static list of roles.
# Any unscoped API resources are to be managed by the platform operator
# and are assumed to be read only for all.  Global permissions are applied
# regardless of organization or project scoping.  Organization permissions
# are applied to the organization, regardless of project scoping etc.
roles:
  # A platform-admin can do anything anywhere.
  platform-adminstrator:
    description: Platform administrator
    protected: true
    scopes:
      global:
        organizations: [create,read,update,delete]
        oauth2providers: [create,read,update,delete]
        roles: [create,read,update,delete]
        groups: [create,read,update,delete]
        projects: [create,read,update,delete]
        infrastructure: [create,read,update,delete]
        kubernetesclustermanagers: [create,read,update,delete]
        kubernetesclusters: [create,read,update,delete]
  # An administrator can do anything within an organization.
  adminstrator:
    description: Organization administrator
    scopes:
      organization:
        organizations: [read,update]
        oauth2providers: [create,read,update,delete]
        roles: [create,read,update,delete]
        groups: [create,read,update,delete]
        projects: [create,read,update,delete]
        infrastructure: [create,read,update,delete]
        kubernetesclustermanagers: [create,read,update,delete]
        kubernetesclusters: [create,read,update,delete]
  # A user can view projects they are a member of and
  # provision kubernetes clusters.
  user:
    description: Project user
    scopes:
      project:
        projects: [read]
        infrastructure: [create,read]
        kubernetesclustermanagers: [read]
        kubernetesclusters: [create,read,update,delete]
  # A reader can view projects they are a member of and view
  # kubernetes clusters.
  reader:
    description: Project reader
    scopes:
      project:
        projects: [read]
        infrastructure: [read]
        kubernetesclustermanagers: [read]
        kubernetesclusters: [read]

ingress:
  # Sets the ingress class to use.
  class: ~

  # clusterIssuer to use.
  # This defaults to the self-signed CA defined in Unikorn core.
  clusterIssuer: unikorn-issuer

  # If true, will add the external DNS hostname annotation.
  externalDns: false

# Allows CORS to be configured/secured
# cors:
#   # Broswers must send requests from these origin servers, defaults to * if not set.
#   allowOrigin: ['*']
#   # How long to cache the CORS preflight for, mostly useless as browsers override this.
#   maxAge: 86400

# Sets the OTLP endpoint for shipping spans.
# otlpEndpoint: jaeger-collector.default:4318
